// isee_vocab_enhanced1.js
// Enhanced Option 1: 300 additional ISEE-level vocabulary words
// These words are at the same difficulty level as the original 300
// None of these words appear in the original list
// Words distributed proportionally across all letters A-Z

window.DEFINITIONS_ENHANCED1 = {
  // A words (12)
  ABSURD: "ridiculous, irrational, nonsensical — Example: The absurd proposal was rejected immediately by the committee.",
  ACCLAIM: "praise, applaud, recognition — Example: The author received widespread acclaim for her debut novel.",
  ACUTE: "sharp, severe, intense — Example: The patient experienced acute pain after the surgery.",
  ADVERSITY: "hardship, misfortune, difficulty — Example: They showed courage in the face of adversity.",
  AFFABLE: "friendly, pleasant, approachable — Example: The affable host made everyone feel comfortable.",
  ALACRITY: "eagerness, enthusiasm, willingness — Example: She accepted the challenge with alacrity.",
  ALLOCATE: "distribute, assign, allot — Example: The manager will allocate resources to each department.",
  AMBUSH: "trap, surprise attack, waylay — Example: The soldiers prepared an ambush along the route.",
  ANALOGY: "comparison, similarity, parallel — Example: The teacher used an analogy to explain the concept.",
  ARBITRARY: "random, unpredictable, capricious — Example: The decision seemed arbitrary and unfair.",
  ASCEND: "rise, climb, mount — Example: The hikers will ascend the mountain at dawn.",
  AUSTERE: "severe, stern, strict — Example: The monastery maintained an austere lifestyle.",
  
  // B words (12)
  BAFFLE: "confuse, puzzle, perplex — Example: The mystery continued to baffle investigators.",
  BELIE: "contradict, misrepresent, disguise — Example: Her calm demeanor belies her inner anxiety.",
  BENEVOLENT: "kind, charitable, generous — Example: The benevolent donor funded the scholarship program.",
  BESTOW: "give, grant, confer — Example: The university will bestow honorary degrees at graduation.",
  BREVITY: "briefness, conciseness, shortness — Example: The brevity of the speech was appreciated.",
  BRISK: "quick, energetic, lively — Example: They took a brisk walk through the park.",
  BRITTLE: "fragile, delicate, breakable — Example: The brittle branches snapped in the wind.",
  BROOD: "ponder, worry, dwell on — Example: Don't brood over past mistakes for too long.",
  BRUSQUE: "abrupt, blunt, curt — Example: His brusque manner offended the guests.",
  BULWARK: "defense, protection, safeguard — Example: The constitution serves as a bulwark against tyranny.",
  BUOYANT: "cheerful, optimistic, upbeat — Example: She remained buoyant despite the setback.",
  BUTTRESS: "support, reinforce, strengthen — Example: Additional evidence will buttress the argument.",
  
  // C words (18)
  CANDOR: "honesty, frankness, sincerity — Example: Her candor about the situation was refreshing.",
  CAPACIOUS: "spacious, roomy, large — Example: The capacious hall accommodated all the guests.",
  CEDE: "surrender, yield, relinquish — Example: The nation agreed to cede territory after the war.",
  CIRCUMVENT: "avoid, bypass, evade — Example: They tried to circumvent the traffic by taking side streets.",
  COERCE: "force, compel, pressure — Example: They tried to coerce him into signing the contract.",
  COGNIZANT: "aware, conscious, informed — Example: She was cognizant of the risks involved.",
  COHERENT: "logical, consistent, clear — Example: He presented a coherent argument for the proposal.",
  COMMEMORATE: "honor, celebrate, memorialize — Example: The monument commemorates fallen soldiers.",
  COMPELLING: "convincing, persuasive, forceful — Example: She made a compelling case for reform.",
  COMPENSATE: "repay, reimburse, offset — Example: The company will compensate workers for overtime.",
  COMPLACENT: "satisfied, smug, unconcerned — Example: Don't become complacent after early success.",
  COMPLY: "obey, conform, follow — Example: All employees must comply with safety regulations.",
  COMPOSURE: "calmness, poise, self-control — Example: She maintained her composure during the crisis.",
  COMPREHENSIVE: "complete, thorough, extensive — Example: The report provides a comprehensive analysis.",
  CONDEMN: "criticize, denounce, censure — Example: Leaders condemn the act of violence.",
  CONDUCIVE: "helpful, favorable, beneficial — Example: A quiet room is conducive to studying.",
  CONSENSUS: "agreement, accord, unity — Example: The committee reached a consensus on the issue.",
  CONSTRAIN: "restrict, limit, restrain — Example: Budget cuts constrain the department's activities.",
  
  // D words (18)
  DAUNTING: "intimidating, discouraging, formidable — Example: The daunting task required careful planning.",
  DEFT: "skillful, adept, expert — Example: The surgeon's deft movements ensured success.",
  DELEGATE: "assign, entrust, authorize — Example: The manager will delegate tasks to team members.",
  DELINEATE: "outline, describe, define — Example: The contract clearly delineates each party's duties.",
  DENOUNCE: "condemn, criticize, censure — Example: The senator denounced corruption in government.",
  DEPLETE: "exhaust, drain, use up — Example: Overfishing can deplete marine resources.",
  DERIDE: "mock, ridicule, scorn — Example: Critics derided the film as poorly made.",
  DERIVE: "obtain, extract, originate — Example: The medicine is derived from natural plants.",
  DETER: "discourage, prevent, inhibit — Example: Strict penalties deter illegal behavior.",
  DEVIATE: "diverge, stray, differ — Example: Don't deviate from the planned route.",
  DEVISE: "invent, create, formulate — Example: Scientists devise new methods for research.",
  DILIGENT: "hardworking, industrious, conscientious — Example: Diligent students earn better grades.",
  DISCERN: "perceive, detect, distinguish — Example: It's hard to discern truth from fiction.",
  DISCRETE: "separate, distinct, individual — Example: The process involves three discrete stages.",
  DISPARITY: "difference, inequality, gap — Example: There's a disparity in pay between positions.",
  DISPERSE: "scatter, spread, disseminate — Example: Police ordered crowds to disperse peacefully.",
  DISSENT: "disagreement, opposition, protest — Example: One judge filed a dissent from the ruling.",
  DIVERGE: "separate, split, branch — Example: Their opinions diverge on economic policy.",
  
  // E words (18)
  ECCENTRIC: "unconventional, odd, quirky — Example: The eccentric artist lived in a converted warehouse.",
  EDIFY: "educate, enlighten, instruct — Example: The lecture will edify students on history.",
  ELABORATE: "detailed, complex, intricate — Example: She presented an elaborate plan for expansion.",
  ELICIT: "draw out, evoke, extract — Example: The questions elicit thoughtful responses.",
  ELIGIBLE: "qualified, suitable, acceptable — Example: Graduates are eligible for the scholarship.",
  ELUCIDATE: "explain, clarify, illuminate — Example: The professor will elucidate the theorem.",
  EMANATE: "originate, emerge, issue — Example: Light emanates from the distant star.",
  EMANCIPATE: "free, liberate, release — Example: The proclamation aimed to emancipate enslaved people.",
  EMBARK: "begin, start, commence — Example: They will embark on a new venture next month.",
  EMERGE: "appear, surface, arise — Example: New leaders emerge during times of crisis.",
  EMINENT: "distinguished, prominent, renowned — Example: An eminent scholar delivered the keynote address.",
  EMPHASIZE: "stress, highlight, underscore — Example: Teachers emphasize the importance of reading.",
  EMPIRICAL: "experimental, observed, factual — Example: The theory requires empirical evidence.",
  EMULATE: "imitate, copy, follow — Example: Young athletes emulate their sports heroes.",
  ENCOMPASS: "include, contain, comprise — Example: The study encompasses multiple disciplines.",
  ENDORSE: "support, approve, back — Example: The organization will endorse the candidate.",
  ENHANCE: "improve, increase, augment — Example: New features enhance the product's appeal.",
  ENLIGHTEN: "inform, educate, illuminate — Example: The documentary will enlighten viewers about wildlife.",
  
  // F words (18)
  FACILITATE: "assist, help, enable — Example: Technology can facilitate remote learning.",
  FACILE: "easy, simple, effortless — Example: The problem has no facile solution.",
  FALLOW: "unused, dormant, inactive — Example: The field lay fallow for a season.",
  FEASIBLE: "possible, practical, workable — Example: The plan seems feasible with proper funding.",
  FEIGN: "pretend, fake, simulate — Example: She tried to feign interest in the conversation.",
  FINITE: "limited, bounded, restricted — Example: Natural resources are finite and must be conserved.",
  FLAGRANT: "blatant, obvious, glaring — Example: The violation was a flagrant breach of rules.",
  FLAW: "defect, fault, imperfection — Example: Engineers discovered a flaw in the design.",
  FLUCTUATE: "vary, change, waver — Example: Stock prices fluctuate throughout the day.",
  FLUENT: "smooth, flowing, articulate — Example: She is fluent in three languages.",
  FOIBLE: "weakness, flaw, quirk — Example: Everyone has minor foibles and imperfections.",
  FORBEAR: "refrain, abstain, withhold — Example: Please forbear from interrupting the speaker.",
  FORESTALL: "prevent, hinder, obstruct — Example: Quick action can forestall serious problems.",
  FORGE: "create, form, shape — Example: Nations forge alliances during wartime.",
  FORSAKE: "abandon, desert, renounce — Example: She refused to forsake her principles.",
  FORTIFY: "strengthen, reinforce, secure — Example: Troops fortify their positions against attack.",
  FOSTER: "encourage, promote, nurture — Example: Good teachers foster creativity in students.",
  FRAUGHT: "filled, laden, charged — Example: The situation is fraught with danger.",
  
  // G words (12)
  GARNER: "gather, collect, accumulate — Example: The film will garner critical acclaim.",
  GAUNT: "thin, emaciated, haggard — Example: Illness left him gaunt and weak.",
  GENERIC: "general, common, universal — Example: The store sells generic brands at lower prices.",
  GENIAL: "friendly, cordial, amiable — Example: The genial host welcomed all guests warmly.",
  GESTURE: "signal, sign, motion — Example: She made a gesture of apology.",
  GHASTLY: "horrible, dreadful, shocking — Example: The accident scene was ghastly.",
  GIST: "essence, main point, core — Example: Can you summarize the gist of the article?",
  GLEAN: "gather, collect, extract — Example: Researchers glean data from multiple sources.",
  GLIB: "smooth, fluent, slick — Example: His glib response failed to convince anyone.",
  GRACIOUS: "courteous, kind, polite — Example: She was gracious in accepting the award.",
  GRADUAL: "slow, steady, progressive — Example: Gradual changes are easier to adapt to.",
  GRATIFY: "please, satisfy, delight — Example: The results gratify months of hard work.",
  
  // H words (12)
  HACKNEYED: "overused, trite, cliched — Example: The speech was full of hackneyed phrases.",
  HAMPER: "hinder, obstruct, impede — Example: Bad weather will hamper rescue efforts.",
  HARMONIOUS: "agreeable, compatible, peaceful — Example: The team worked in harmonious cooperation.",
  HASTEN: "hurry, rush, accelerate — Example: They must hasten to meet the deadline.",
  HAUGHTY: "arrogant, proud, disdainful — Example: His haughty manner alienated colleagues.",
  HAVOC: "chaos, destruction, disorder — Example: The storm wreaked havoc on coastal towns.",
  HEED: "notice, attention, consideration — Example: Pay heed to the warning signs.",
  HEINOUS: "evil, wicked, atrocious — Example: The court condemned the heinous crime.",
  HERALD: "announce, proclaim, signal — Example: Spring flowers herald the arrival of warmer weather.",
  HERMIT: "recluse, loner, solitary — Example: The hermit lived alone in the mountains.",
  HINDER: "obstruct, impede, block — Example: Traffic congestion will hinder our progress.",
  HUMBLE: "modest, unassuming, unpretentious — Example: Despite success, she remained humble.",
  
  // I words (12)
  IDEOLOGY: "belief system, doctrine, philosophy — Example: Political parties differ in ideology.",
  IGNITE: "light, kindle, inflame — Example: A single spark can ignite a forest fire.",
  ILLICIT: "illegal, unlawful, forbidden — Example: Police cracked down on illicit drug trade.",
  ILLUMINATE: "light up, clarify, explain — Example: Lamps illuminate the dark pathway.",
  IMMACULATE: "perfect, spotless, flawless — Example: The bride's gown was immaculate.",
  IMMERSE: "submerge, engross, absorb — Example: She likes to immerse herself in novels.",
  IMMINENT: "impending, approaching, near — Example: Forecasters warn of imminent severe weather.",
  IMPAIR: "damage, harm, weaken — Example: Poor lighting can impair vision.",
  IMPECCABLE: "flawless, perfect, faultless — Example: His impeccable manners impressed everyone.",
  IMPEDE: "hinder, obstruct, block — Example: Debris will impede traffic flow.",
  IMPERATIVE: "essential, necessary, urgent — Example: It is imperative that we act quickly.",
  IMPERVIOUS: "resistant, immune, impenetrable — Example: The material is impervious to water.",
  
  // J words (6)
  JEOPARDIZE: "endanger, threaten, risk — Example: Careless actions could jeopardize the mission.",
  JUBILANT: "joyful, exultant, triumphant — Example: The jubilant crowd celebrated the victory.",
  JUDICIOUS: "wise, sensible, prudent — Example: She made a judicious decision after careful thought.",
  JUNCTION: "intersection, crossroads, connection — Example: Turn left at the next junction.",
  JUSTIFY: "defend, explain, validate — Example: Can you justify your reasoning?",
  JUXTAPOSE: "place side by side, compare, contrast — Example: The exhibit juxtaposes ancient and modern art.",
  
  // K words (4)
  KINDLE: "ignite, light, spark — Example: Dry wood helps kindle a fire quickly.",
  KNACK: "talent, skill, aptitude — Example: She has a knack for solving puzzles.",
  KNOLL: "hill, mound, rise — Example: They picnicked on a grassy knoll.",
  KUDOS: "praise, acclaim, recognition — Example: Kudos to the team for excellent work.",
  
  // L words (12)
  LABORIOUS: "difficult, arduous, strenuous — Example: The laborious task took all day.",
  LAMPOON: "satirize, mock, ridicule — Example: The comedy show lampooned political figures.",
  LANGUID: "sluggish, lethargic, weak — Example: The humid weather made everyone feel languid.",
  LATENT: "dormant, hidden, potential — Example: Her latent talent emerged during the performance.",
  LAUDABLE: "praiseworthy, commendable, admirable — Example: The volunteers' efforts are laudable.",
  LAVISH: "extravagant, luxurious, abundant — Example: They hosted a lavish celebration.",
  LEGACY: "inheritance, bequest, heritage — Example: His legacy lives on through his charitable work.",
  LEGITIMATE: "legal, valid, lawful — Example: The document appeared to be legitimate.",
  LETHARGY: "sluggishness, inactivity, apathy — Example: The heat caused widespread lethargy.",
  LEVITY: "humor, lightheartedness, frivolity — Example: A little levity helped ease the tension.",
  LUCID: "clear, understandable, coherent — Example: The professor gave a lucid explanation.",
  LUMINOUS: "bright, shining, radiant — Example: The moon cast a luminous glow over the lake.",
  
  // M words (12)
  MAGNANIMOUS: "generous, forgiving, noble — Example: The magnanimous leader pardoned his critics.",
  MAGNITUDE: "size, extent, importance — Example: The magnitude of the problem became clear.",
  MALICIOUS: "spiteful, mean, vindictive — Example: The malicious rumors spread quickly.",
  MANDATE: "command, order, directive — Example: The government issued a mandate for safety measures.",
  MANIFEST: "evident, obvious, clear — Example: Her talent was manifest from an early age.",
  MEAGER: "scanty, sparse, inadequate — Example: They survived on meager rations.",
  MELLOW: "soft, gentle, easygoing — Example: His personality mellowed with age.",
  MENACE: "threat, danger, peril — Example: The storm posed a menace to coastal areas.",
  MENTOR: "guide, advisor, teacher — Example: She found a mentor to help with her career.",
  METICULOUS: "careful, thorough, precise — Example: He kept meticulous records of expenses.",
  MIRTH: "merriment, joy, laughter — Example: The party was full of mirth and celebration.",
  MITIGATE: "lessen, reduce, alleviate — Example: Sandbags helped mitigate flood damage.",
  
  // N words (10)
  NASCENT: "emerging, budding, developing — Example: The nascent technology shows great promise.",
  NEGLIGIBLE: "insignificant, trivial, minor — Example: The cost difference is negligible.",
  NIMBLE: "agile, quick, spry — Example: The nimble dancer leaped across the stage.",
  NOMINAL: "minimal, small, token — Example: They charged only a nominal fee.",
  NONCHALANT: "casual, indifferent, unconcerned — Example: He gave a nonchalant shrug.",
  NURTURE: "care for, foster, cultivate — Example: Parents nurture their children's talents.",
  NOMADIC: "wandering, roaming, itinerant — Example: The nomadic tribe moved with the seasons.",
  NULLIFY: "cancel, invalidate, void — Example: The court will nullify the contract.",
  NOTABLE: "remarkable, significant, noteworthy — Example: She achieved notable success in her field.",
  NOTION: "idea, concept, belief — Example: He had a vague notion of what to do.",
  
  // O words (10)
  OBLIGE: "require, compel, accommodate — Example: The law will oblige companies to report emissions.",
  OBLITERATE: "destroy, erase, eliminate — Example: The explosion obliterated the building.",
  OBLIVIOUS: "unaware, unconscious, ignorant — Example: He seemed oblivious to the danger.",
  OBSCURE: "unclear, vague, hidden — Example: The meaning remained obscure to most readers.",
  OBSTRUCT: "block, hinder, impede — Example: Fallen trees obstruct the trail.",
  OMINOUS: "threatening, menacing, foreboding — Example: Dark clouds cast an ominous shadow.",
  OPPRESS: "persecute, tyrannize, subjugate — Example: The regime continued to oppress minorities.",
  OPTIMUM: "best, ideal, optimal — Example: These are the optimum conditions for growth.",
  OPULENT: "luxurious, wealthy, lavish — Example: The opulent mansion had marble floors.",
  OVERT: "obvious, open, apparent — Example: His overt hostility surprised everyone.",
  
  // P words (18)
  PACIFY: "calm, soothe, appease — Example: Soft music helped pacify the crying baby.",
  PALPABLE: "tangible, obvious, evident — Example: The tension in the room was palpable.",
  PARAMOUNT: "supreme, primary, foremost — Example: Safety is of paramount importance.",
  PARDON: "forgive, excuse, absolve — Example: The governor granted a pardon to the prisoner.",
  PARODY: "satire, mockery, imitation — Example: The play was a parody of political debates.",
  PARTIAL: "incomplete, biased, limited — Example: We have only a partial understanding.",
  PARTITION: "divide, separate, section — Example: A screen will partition the room.",
  PATENT: "obvious, clear, evident — Example: His patent dishonesty angered everyone.",
  PAUCITY: "scarcity, shortage, lack — Example: There's a paucity of evidence in this case.",
  PECULIAR: "strange, odd, unusual — Example: The building has a peculiar architecture.",
  PENSIVE: "thoughtful, reflective, contemplative — Example: She sat in a pensive mood.",
  PERENNIAL: "enduring, lasting, permanent — Example: Water shortage is a perennial problem.",
  PERIL: "danger, risk, hazard — Example: The climbers faced great peril on the mountain.",
  PERIPHERAL: "outer, marginal, secondary — Example: Cost is a peripheral concern right now.",
  PERPETUAL: "continuous, endless, eternal — Example: The waterfall's perpetual roar filled the valley.",
  PERSIST: "continue, persevere, endure — Example: The symptoms persist despite treatment.",
  PERTURB: "disturb, upset, trouble — Example: The news will perturb investors.",
  PIVOTAL: "crucial, critical, vital — Example: This is a pivotal moment in history.",
  
  // Q words (6)
  QUAINT: "charming, old-fashioned, picturesque — Example: The quaint village attracted tourists.",
  QUALIFY: "modify, limit, meet requirements — Example: Few candidates qualify for the position.",
  QUALM: "doubt, misgiving, scruple — Example: She had no qualms about speaking up.",
  QUELL: "suppress, subdue, crush — Example: Police moved to quell the riot.",
  QUEST: "search, pursuit, journey — Example: The scientist's quest for truth continues.",
  QUIBBLE: "argue, object, nitpick — Example: Don't quibble over minor details.",
  
  // R words (12)
  RAMBLE: "wander, roam, meander — Example: We rambled through the countryside.",
  RANCOR: "bitterness, resentment, animosity — Example: The debate was filled with rancor.",
  RATIFY: "approve, confirm, sanction — Example: Congress will ratify the treaty.",
  REBUKE: "reprimand, scold, criticize — Example: The manager rebuked the employee for tardiness.",
  RECANT: "retract, withdraw, renounce — Example: The witness refused to recant his testimony.",
  RECEPTIVE: "open, responsive, amenable — Example: Students were receptive to new ideas.",
  RECLUSE: "hermit, loner, solitary person — Example: The author became a recluse in later years.",
  RECONCILE: "settle, resolve, harmonize — Example: They tried to reconcile their differences.",
  REFUTE: "disprove, rebut, contradict — Example: The evidence will refute his claims.",
  RELENTLESS: "persistent, unremitting, continuous — Example: The relentless rain flooded streets.",
  RENOUNCE: "reject, abandon, disown — Example: He chose to renounce his citizenship.",
  REPUDIATE: "reject, deny, disavow — Example: The senator repudiated the accusations.",
  
  // S words (18)
  SABOTAGE: "undermine, damage, subvert — Example: Hackers attempted to sabotage the system.",
  SAGE: "wise, prudent, sensible — Example: The sage advisor offered valuable counsel.",
  SALIENT: "prominent, notable, important — Example: She highlighted the salient points.",
  SALVAGE: "save, rescue, recover — Example: Divers will salvage cargo from the wreck.",
  SANCTION: "approve, authorize, permit — Example: The board will sanction the new policy.",
  SATURATE: "soak, drench, permeate — Example: Heavy rains saturated the ground.",
  SCANTY: "meager, sparse, insufficient — Example: Evidence against him was scanty.",
  SCRUTINIZE: "examine, inspect, analyze — Example: Auditors will scrutinize the accounts.",
  SECLUDE: "isolate, segregate, separate — Example: The cabin is secluded in the woods.",
  SEDATE: "calm, composed, dignified — Example: The ceremony proceeded at a sedate pace.",
  SEQUEL: "continuation, follow-up, result — Example: The sequel surpassed the original film.",
  SHREWD: "astute, clever, sharp — Example: She made a shrewd business decision.",
  SIMULTANEOUS: "concurrent, coinciding, synchronous — Example: The events were simultaneous.",
  SINGULAR: "unique, exceptional, remarkable — Example: She showed singular dedication.",
  SKEPTICAL: "doubtful, questioning, suspicious — Example: Investors remained skeptical of the claims.",
  SLUGGISH: "slow, lethargic, inactive — Example: The economy remained sluggish.",
  SOMBER: "serious, grave, solemn — Example: The funeral was a somber occasion.",
  SPORADIC: "irregular, occasional, intermittent — Example: There were sporadic outbreaks of violence.",
  
  // T words (12)
  TACITURN: "quiet, reserved, uncommunicative — Example: The taciturn guard rarely spoke.",
  TANGIBLE: "real, concrete, physical — Example: We need tangible proof of progress.",
  TARNISH: "damage, stain, sully — Example: The scandal will tarnish his reputation.",
  TAUT: "tight, tense, stretched — Example: The rope was pulled taut.",
  TEEM: "swarm, abound, be full of — Example: The river teems with salmon.",
  TEMPER: "moderate, soften, mitigate — Example: She learned to temper her criticism.",
  TENUOUS: "weak, flimsy, uncertain — Example: The connection seems tenuous at best.",
  TERMINATE: "end, conclude, cease — Example: The contract will terminate next month.",
  THWART: "prevent, frustrate, foil — Example: Bad weather thwarted their plans.",
  TIMOROUS: "fearful, timid, apprehensive — Example: The timorous rabbit fled quickly.",
  TOIL: "work hard, labor, struggle — Example: Farmers toil in the fields daily.",
  TURBULENT: "chaotic, stormy, violent — Example: The flight encountered turbulent weather.",
  
  // U words (8)
  UBIQUITOUS: "everywhere, omnipresent, universal — Example: Smartphones are ubiquitous in modern society.",
  ULTIMATE: "final, eventual, supreme — Example: Victory was their ultimate goal.",
  UNASSUMING: "modest, humble, unpretentious — Example: Despite fame, she remained unassuming.",
  UNCANNY: "strange, mysterious, eerie — Example: She had an uncanny ability to predict trends.",
  UNDERMINE: "weaken, sabotage, subvert — Example: Rumors can undermine public confidence.",
  UNIFORM: "consistent, identical, unchanging — Example: The temperature remained uniform.",
  UNPRECEDENTED: "unparalleled, novel, unique — Example: The crisis was unprecedented in scope.",
  UPHOLD: "support, maintain, sustain — Example: Courts uphold constitutional rights.",
  
  // V words (12)
  VALID: "sound, legitimate, acceptable — Example: She raised a valid concern.",
  VALOR: "bravery, courage, heroism — Example: Soldiers displayed great valor in battle.",
  VANQUISH: "defeat, conquer, overcome — Example: The army vanquished its enemies.",
  VENERATE: "revere, respect, honor — Example: Many cultures venerate their elders.",
  VERBOSE: "wordy, long-winded, rambling — Example: His verbose speech lasted two hours.",
  VERSATILE: "adaptable, flexible, all-around — Example: She's a versatile performer.",
  VETO: "reject, prohibit, forbid — Example: The president may veto the legislation.",
  VIABLE: "feasible, workable, practical — Example: The plan seems viable with adjustments.",
  VICIOUS: "cruel, brutal, savage — Example: The vicious attack shocked the community.",
  VINDICATE: "clear, exonerate, justify — Example: New evidence will vindicate him.",
  VIRTUAL: "nearly, practically, almost — Example: The project came to a virtual standstill.",
  VIRULENT: "poisonous, toxic, deadly — Example: The virulent disease spread rapidly.",
  
  // W words (8)
  WAIVE: "relinquish, forgo, surrender — Example: They agreed to waive the fee.",
  WANE: "decrease, decline, diminish — Example: His influence began to wane.",
  WARY: "cautious, careful, vigilant — Example: Be wary of unsolicited offers.",
  WHOLESOME: "healthy, beneficial, nutritious — Example: The family enjoyed wholesome meals.",
  WIELD: "hold, brandish, exercise — Example: The king wielded absolute power.",
  WILLFUL: "deliberate, intentional, stubborn — Example: His willful disobedience had consequences.",
  WITHER: "shrivel, wilt, fade — Example: Plants wither without water.",
  WRATH: "anger, fury, rage — Example: The king's wrath was fearsome.",
  
  // X, Y, Z words (4)
  XENOPHOBIA: "fear of foreigners, prejudice, intolerance — Example: Xenophobia has no place in modern society.",
  YEARN: "long for, desire, crave — Example: She yearned for adventure.",
  YIELD: "produce, generate, surrender — Example: The fields yield abundant crops.",
  ZENITH: "peak, summit, apex — Example: Her career reached its zenith."
};

window.QUESTIONS_ENHANCED1 = [
  // A words (12 questions: 301-312)
  { number: 301, word: "ABSURD", choices: { A:"logical", B:"ridiculous", C:"pleasant", D:"simple" }, answer:"B" },
  { number: 302, word: "ACCLAIM", choices: { A:"praise", B:"reject", C:"silence", D:"whisper" }, answer:"A" },
  { number: 303, word: "ACUTE", choices: { A:"mild", B:"chronic", C:"sharp", D:"dull" }, answer:"C" },
  { number: 304, word: "ADVERSITY", choices: { A:"happiness", B:"hardship", C:"success", D:"fortune" }, answer:"B" },
  { number: 305, word: "AFFABLE", choices: { A:"hostile", B:"mysterious", C:"friendly", D:"serious" }, answer:"C" },
  { number: 306, word: "ALACRITY", choices: { A:"reluctance", B:"confusion", C:"eagerness", D:"sorrow" }, answer:"C" },
  { number: 307, word: "ALLOCATE", choices: { A:"distribute", B:"withhold", C:"destroy", D:"create" }, answer:"A" },
  { number: 308, word: "AMBUSH", choices: { A:"retreat", B:"greeting", C:"trap", D:"warning" }, answer:"C" },
  { number: 309, word: "ANALOGY", choices: { A:"difference", B:"comparison", C:"opposition", D:"conclusion" }, answer:"B" },
  { number: 310, word: "ARBITRARY", choices: { A:"planned", B:"fair", C:"random", D:"necessary" }, answer:"C" },
  { number: 311, word: "ASCEND", choices: { A:"descend", B:"remain", C:"rise", D:"fall" }, answer:"C" },
  { number: 312, word: "AUSTERE", choices: { A:"luxurious", B:"severe", C:"comfortable", D:"decorated" }, answer:"B" },
  
  // B words (12 questions: 313-324)
  { number: 313, word: "BAFFLE", choices: { A:"clarify", B:"simplify", C:"confuse", D:"explain" }, answer:"C" },
  { number: 314, word: "BELIE", choices: { A:"confirm", B:"contradict", C:"prove", D:"support" }, answer:"B" },
  { number: 315, word: "BENEVOLENT", choices: { A:"cruel", B:"kind", C:"neutral", D:"indifferent" }, answer:"B" },
  { number: 316, word: "BESTOW", choices: { A:"take", B:"refuse", C:"give", D:"borrow" }, answer:"C" },
  { number: 317, word: "BREVITY", choices: { A:"length", B:"briefness", C:"complexity", D:"detail" }, answer:"B" },
  { number: 318, word: "BRISK", choices: { A:"slow", B:"lazy", C:"quick", D:"tired" }, answer:"C" },
  { number: 319, word: "BRITTLE", choices: { A:"strong", B:"flexible", C:"fragile", D:"durable" }, answer:"C" },
  { number: 320, word: "BROOD", choices: { A:"celebrate", B:"ignore", C:"ponder", D:"forget" }, answer:"C" },
  { number: 321, word: "BRUSQUE", choices: { A:"polite", B:"gentle", C:"abrupt", D:"patient" }, answer:"C" },
  { number: 322, word: "BULWARK", choices: { A:"weakness", B:"attack", C:"defense", D:"surrender" }, answer:"C" },
  { number: 323, word: "BUOYANT", choices: { A:"depressed", B:"heavy", C:"cheerful", D:"sinking" }, answer:"C" },
  { number: 324, word: "BUTTRESS", choices: { A:"weaken", B:"undermine", C:"support", D:"destroy" }, answer:"C" },
  
  // C words (18 questions: 325-342)
  { number: 325, word: "CANDOR", choices: { A:"deception", B:"honesty", C:"secrecy", D:"confusion" }, answer:"B" },
  { number: 326, word: "CAPACIOUS", choices: { A:"tiny", B:"narrow", C:"spacious", D:"cramped" }, answer:"C" },
  { number: 327, word: "CEDE", choices: { A:"take", B:"surrender", C:"demand", D:"claim" }, answer:"B" },
  { number: 328, word: "CIRCUMVENT", choices: { A:"confront", B:"avoid", C:"attack", D:"embrace" }, answer:"B" },
  { number: 329, word: "COERCE", choices: { A:"persuade", B:"force", C:"request", D:"suggest" }, answer:"B" },
  { number: 330, word: "COGNIZANT", choices: { A:"unaware", B:"confused", C:"aware", D:"ignorant" }, answer:"C" },
  { number: 331, word: "COHERENT", choices: { A:"illogical", B:"confused", C:"logical", D:"random" }, answer:"C" },
  { number: 332, word: "COMMEMORATE", choices: { A:"forget", B:"ignore", C:"honor", D:"dismiss" }, answer:"C" },
  { number: 333, word: "COMPELLING", choices: { A:"weak", B:"unconvincing", C:"persuasive", D:"boring" }, answer:"C" },
  { number: 334, word: "COMPENSATE", choices: { A:"punish", B:"repay", C:"take", D:"refuse" }, answer:"B" },
  { number: 335, word: "COMPLACENT", choices: { A:"worried", B:"concerned", C:"satisfied", D:"anxious" }, answer:"C" },
  { number: 336, word: "COMPLY", choices: { A:"resist", B:"rebel", C:"obey", D:"refuse" }, answer:"C" },
  { number: 337, word: "COMPOSURE", choices: { A:"panic", B:"hysteria", C:"calmness", D:"excitement" }, answer:"C" },
  { number: 338, word: "COMPREHENSIVE", choices: { A:"incomplete", B:"partial", C:"complete", D:"limited" }, answer:"C" },
  { number: 339, word: "CONDEMN", choices: { A:"praise", B:"approve", C:"criticize", D:"support" }, answer:"C" },
  { number: 340, word: "CONDUCIVE", choices: { A:"harmful", B:"helpful", C:"neutral", D:"detrimental" }, answer:"B" },
  { number: 341, word: "CONSENSUS", choices: { A:"disagreement", B:"conflict", C:"agreement", D:"debate" }, answer:"C" },
  { number: 342, word: "CONSTRAIN", choices: { A:"free", B:"release", C:"restrict", D:"liberate" }, answer:"C" },
  
  // D words (18 questions: 343-360)
  { number: 343, word: "DAUNTING", choices: { A:"encouraging", B:"easy", C:"intimidating", D:"simple" }, answer:"C" },
  { number: 344, word: "DEFT", choices: { A:"clumsy", B:"awkward", C:"skillful", D:"incompetent" }, answer:"C" },
  { number: 345, word: "DELEGATE", choices: { A:"claim", B:"hoard", C:"assign", D:"keep" }, answer:"C" },
  { number: 346, word: "DELINEATE", choices: { A:"obscure", B:"confuse", C:"outline", D:"hide" }, answer:"C" },
  { number: 347, word: "DENOUNCE", choices: { A:"praise", B:"support", C:"condemn", D:"approve" }, answer:"C" },
  { number: 348, word: "DEPLETE", choices: { A:"replenish", B:"fill", C:"exhaust", D:"restore" }, answer:"C" },
  { number: 349, word: "DERIDE", choices: { A:"praise", B:"compliment", C:"mock", D:"admire" }, answer:"C" },
  { number: 350, word: "DERIVE", choices: { A:"give", B:"donate", C:"obtain", D:"lose" }, answer:"C" },
  { number: 351, word: "DETER", choices: { A:"encourage", B:"motivate", C:"discourage", D:"inspire" }, answer:"C" },
  { number: 352, word: "DEVIATE", choices: { A:"follow", B:"conform", C:"diverge", D:"obey" }, answer:"C" },
  { number: 353, word: "DEVISE", choices: { A:"destroy", B:"copy", C:"invent", D:"imitate" }, answer:"C" },
  { number: 354, word: "DILIGENT", choices: { A:"lazy", B:"careless", C:"hardworking", D:"negligent" }, answer:"C" },
  { number: 355, word: "DISCERN", choices: { A:"ignore", B:"overlook", C:"perceive", D:"miss" }, answer:"C" },
  { number: 356, word: "DISCRETE", choices: { A:"connected", B:"merged", C:"separate", D:"combined" }, answer:"C" },
  { number: 357, word: "DISPARITY", choices: { A:"equality", B:"similarity", C:"difference", D:"sameness" }, answer:"C" },
  { number: 358, word: "DISPERSE", choices: { A:"gather", B:"collect", C:"scatter", D:"assemble" }, answer:"C" },
  { number: 359, word: "DISSENT", choices: { A:"agreement", B:"consent", C:"disagreement", D:"approval" }, answer:"C" },
  { number: 360, word: "DIVERGE", choices: { A:"converge", B:"meet", C:"separate", D:"unite" }, answer:"C" },
  
  // E words (18 questions: 361-378)
  { number: 361, word: "ECCENTRIC", choices: { A:"conventional", B:"normal", C:"unconventional", D:"typical" }, answer:"C" },
  { number: 362, word: "EDIFY", choices: { A:"confuse", B:"mislead", C:"educate", D:"deceive" }, answer:"C" },
  { number: 363, word: "ELABORATE", choices: { A:"simple", B:"plain", C:"detailed", D:"basic" }, answer:"C" },
  { number: 364, word: "ELICIT", choices: { A:"suppress", B:"hide", C:"draw out", D:"conceal" }, answer:"C" },
  { number: 365, word: "ELIGIBLE", choices: { A:"unqualified", B:"unsuitable", C:"qualified", D:"ineligible" }, answer:"C" },
  { number: 366, word: "ELUCIDATE", choices: { A:"confuse", B:"obscure", C:"explain", D:"complicate" }, answer:"C" },
  { number: 367, word: "EMANATE", choices: { A:"absorb", B:"receive", C:"originate", D:"take" }, answer:"C" },
  { number: 368, word: "EMANCIPATE", choices: { A:"enslave", B:"imprison", C:"free", D:"capture" }, answer:"C" },
  { number: 369, word: "EMBARK", choices: { A:"end", B:"finish", C:"begin", D:"conclude" }, answer:"C" },
  { number: 370, word: "EMERGE", choices: { A:"hide", B:"disappear", C:"appear", D:"vanish" }, answer:"C" },
  { number: 371, word: "EMINENT", choices: { A:"unknown", B:"obscure", C:"distinguished", D:"anonymous" }, answer:"C" },
  { number: 372, word: "EMPHASIZE", choices: { A:"downplay", B:"minimize", C:"stress", D:"ignore" }, answer:"C" },
  { number: 373, word: "EMPIRICAL", choices: { A:"theoretical", B:"hypothetical", C:"experimental", D:"speculative" }, answer:"C" },
  { number: 374, word: "EMULATE", choices: { A:"reject", B:"oppose", C:"imitate", D:"refuse" }, answer:"C" },
  { number: 375, word: "ENCOMPASS", choices: { A:"exclude", B:"omit", C:"include", D:"reject" }, answer:"C" },
  { number: 376, word: "ENDORSE", choices: { A:"oppose", B:"reject", C:"support", D:"condemn" }, answer:"C" },
  { number: 377, word: "ENHANCE", choices: { A:"worsen", B:"degrade", C:"improve", D:"diminish" }, answer:"C" },
  { number: 378, word: "ENLIGHTEN", choices: { A:"confuse", B:"mislead", C:"inform", D:"deceive" }, answer:"C" },
  
  // F words (18 questions: 379-396)
  { number: 379, word: "FACILITATE", choices: { A:"hinder", B:"obstruct", C:"assist", D:"block" }, answer:"C" },
  { number: 380, word: "FACILE", choices: { A:"difficult", B:"complex", C:"easy", D:"hard" }, answer:"C" },
  { number: 381, word: "FALLOW", choices: { A:"active", B:"productive", C:"unused", D:"cultivated" }, answer:"C" },
  { number: 382, word: "FEASIBLE", choices: { A:"impossible", B:"impractical", C:"possible", D:"unworkable" }, answer:"C" },
  { number: 383, word: "FEIGN", choices: { A:"reveal", B:"show", C:"pretend", D:"expose" }, answer:"C" },
  { number: 384, word: "FINITE", choices: { A:"infinite", B:"endless", C:"limited", D:"boundless" }, answer:"C" },
  { number: 385, word: "FLAGRANT", choices: { A:"subtle", B:"hidden", C:"blatant", D:"concealed" }, answer:"C" },
  { number: 386, word: "FLAW", choices: { A:"perfection", B:"strength", C:"defect", D:"virtue" }, answer:"C" },
  { number: 387, word: "FLUCTUATE", choices: { A:"stabilize", B:"steady", C:"vary", D:"fix" }, answer:"C" },
  { number: 388, word: "FLUENT", choices: { A:"halting", B:"awkward", C:"smooth", D:"clumsy" }, answer:"C" },
  { number: 389, word: "FOIBLE", choices: { A:"strength", B:"virtue", C:"weakness", D:"talent" }, answer:"C" },
  { number: 390, word: "FORBEAR", choices: { A:"indulge", B:"permit", C:"refrain", D:"allow" }, answer:"C" },
  { number: 391, word: "FORESTALL", choices: { A:"allow", B:"permit", C:"prevent", D:"enable" }, answer:"C" },
  { number: 392, word: "FORGE", choices: { A:"destroy", B:"break", C:"create", D:"demolish" }, answer:"C" },
  { number: 393, word: "FORSAKE", choices: { A:"embrace", B:"keep", C:"abandon", D:"maintain" }, answer:"C" },
  { number: 394, word: "FORTIFY", choices: { A:"weaken", B:"undermine", C:"strengthen", D:"destroy" }, answer:"C" },
  { number: 395, word: "FOSTER", choices: { A:"discourage", B:"hinder", C:"encourage", D:"prevent" }, answer:"C" },
  { number: 396, word: "FRAUGHT", choices: { A:"empty", B:"devoid", C:"filled", D:"lacking" }, answer:"C" },
  
  // G words (12 questions: 397-408)
  { number: 397, word: "GARNER", choices: { A:"lose", B:"scatter", C:"gather", D:"disperse" }, answer:"C" },
  { number: 398, word: "GAUNT", choices: { A:"plump", B:"healthy", C:"thin", D:"robust" }, answer:"C" },
  { number: 399, word: "GENERIC", choices: { A:"specific", B:"unique", C:"general", D:"special" }, answer:"C" },
  { number: 400, word: "GENIAL", choices: { A:"hostile", B:"unfriendly", C:"friendly", D:"cold" }, answer:"C" },
  { number: 401, word: "GESTURE", choices: { A:"stillness", B:"immobility", C:"signal", D:"inaction" }, answer:"C" },
  { number: 402, word: "GHASTLY", choices: { A:"pleasant", B:"beautiful", C:"horrible", D:"lovely" }, answer:"C" },
  { number: 403, word: "GIST", choices: { A:"detail", B:"trivia", C:"essence", D:"specifics" }, answer:"C" },
  { number: 404, word: "GLEAN", choices: { A:"scatter", B:"disperse", C:"gather", D:"distribute" }, answer:"C" },
  { number: 405, word: "GLIB", choices: { A:"sincere", B:"thoughtful", C:"smooth", D:"genuine" }, answer:"C" },
  { number: 406, word: "GRACIOUS", choices: { A:"rude", B:"impolite", C:"courteous", D:"discourteous" }, answer:"C" },
  { number: 407, word: "GRADUAL", choices: { A:"sudden", B:"abrupt", C:"slow", D:"immediate" }, answer:"C" },
  { number: 408, word: "GRATIFY", choices: { A:"disappoint", B:"frustrate", C:"please", D:"displease" }, answer:"C" },
  
  // H words (12 questions: 409-420)
  { number: 409, word: "HACKNEYED", choices: { A:"original", B:"fresh", C:"overused", D:"novel" }, answer:"C" },
  { number: 410, word: "HAMPER", choices: { A:"help", B:"assist", C:"hinder", D:"aid" }, answer:"C" },
  { number: 411, word: "HARMONIOUS", choices: { A:"discordant", B:"conflicting", C:"agreeable", D:"clashing" }, answer:"C" },
  { number: 412, word: "HASTEN", choices: { A:"delay", B:"slow", C:"hurry", D:"dawdle" }, answer:"C" },
  { number: 413, word: "HAUGHTY", choices: { A:"humble", B:"modest", C:"arrogant", D:"meek" }, answer:"C" },
  { number: 414, word: "HAVOC", choices: { A:"order", B:"peace", C:"chaos", D:"harmony" }, answer:"C" },
  { number: 415, word: "HEED", choices: { A:"ignore", B:"disregard", C:"notice", D:"overlook" }, answer:"C" },
  { number: 416, word: "HEINOUS", choices: { A:"virtuous", B:"good", C:"evil", D:"righteous" }, answer:"C" },
  { number: 417, word: "HERALD", choices: { A:"conceal", B:"hide", C:"announce", D:"suppress" }, answer:"C" },
  { number: 418, word: "HERMIT", choices: { A:"socialite", B:"extrovert", C:"recluse", D:"mingler" }, answer:"C" },
  { number: 419, word: "HINDER", choices: { A:"help", B:"facilitate", C:"obstruct", D:"aid" }, answer:"C" },
  { number: 420, word: "HUMBLE", choices: { A:"arrogant", B:"proud", C:"modest", D:"boastful" }, answer:"C" },
  
  // I words (12 questions: 421-432)
  { number: 421, word: "IDEOLOGY", choices: { A:"pragmatism", B:"practicality", C:"belief system", D:"realism" }, answer:"C" },
  { number: 422, word: "IGNITE", choices: { A:"extinguish", B:"quench", C:"light", D:"douse" }, answer:"C" },
  { number: 423, word: "ILLICIT", choices: { A:"legal", B:"lawful", C:"illegal", D:"permitted" }, answer:"C" },
  { number: 424, word: "ILLUMINATE", choices: { A:"darken", B:"obscure", C:"light up", D:"shadow" }, answer:"C" },
  { number: 425, word: "IMMACULATE", choices: { A:"dirty", B:"flawed", C:"perfect", D:"imperfect" }, answer:"C" },
  { number: 426, word: "IMMERSE", choices: { A:"extract", B:"remove", C:"submerge", D:"withdraw" }, answer:"C" },
  { number: 427, word: "IMMINENT", choices: { A:"distant", B:"remote", C:"impending", D:"far" }, answer:"C" },
  { number: 428, word: "IMPAIR", choices: { A:"improve", B:"enhance", C:"damage", D:"strengthen" }, answer:"C" },
  { number: 429, word: "IMPECCABLE", choices: { A:"flawed", B:"imperfect", C:"flawless", D:"faulty" }, answer:"C" },
  { number: 430, word: "IMPEDE", choices: { A:"help", B:"assist", C:"hinder", D:"facilitate" }, answer:"C" },
  { number: 431, word: "IMPERATIVE", choices: { A:"optional", B:"unnecessary", C:"essential", D:"trivial" }, answer:"C" },
  { number: 432, word: "IMPERVIOUS", choices: { A:"vulnerable", B:"susceptible", C:"resistant", D:"permeable" }, answer:"C" },
  
  // J words (6 questions: 433-438)
  { number: 433, word: "JEOPARDIZE", choices: { A:"protect", B:"safeguard", C:"endanger", D:"secure" }, answer:"C" },
  { number: 434, word: "JUBILANT", choices: { A:"sad", B:"depressed", C:"joyful", D:"gloomy" }, answer:"C" },
  { number: 435, word: "JUDICIOUS", choices: { A:"foolish", B:"reckless", C:"wise", D:"impulsive" }, answer:"C" },
  { number: 436, word: "JUNCTION", choices: { A:"separation", B:"division", C:"intersection", D:"distance" }, answer:"C" },
  { number: 437, word: "JUSTIFY", choices: { A:"condemn", B:"criticize", C:"defend", D:"attack" }, answer:"C" },
  { number: 438, word: "JUXTAPOSE", choices: { A:"separate", B:"divide", C:"place side by side", D:"isolate" }, answer:"C" },
  
  // K words (4 questions: 439-442)
  { number: 439, word: "KINDLE", choices: { A:"extinguish", B:"quench", C:"ignite", D:"douse" }, answer:"C" },
  { number: 440, word: "KNACK", choices: { A:"inability", B:"weakness", C:"talent", D:"deficiency" }, answer:"C" },
  { number: 441, word: "KNOLL", choices: { A:"valley", B:"depression", C:"hill", D:"canyon" }, answer:"C" },
  { number: 442, word: "KUDOS", choices: { A:"criticism", B:"blame", C:"praise", D:"condemnation" }, answer:"C" },
  
  // L words (12 questions: 443-454)
  { number: 443, word: "LABORIOUS", choices: { A:"easy", B:"simple", C:"difficult", D:"effortless" }, answer:"C" },
  { number: 444, word: "LAMPOON", choices: { A:"praise", B:"honor", C:"satirize", D:"respect" }, answer:"C" },
  { number: 445, word: "LANGUID", choices: { A:"energetic", B:"vigorous", C:"sluggish", D:"lively" }, answer:"C" },
  { number: 446, word: "LATENT", choices: { A:"obvious", B:"apparent", C:"dormant", D:"visible" }, answer:"C" },
  { number: 447, word: "LAUDABLE", choices: { A:"shameful", B:"disgraceful", C:"praiseworthy", D:"deplorable" }, answer:"C" },
  { number: 448, word: "LAVISH", choices: { A:"meager", B:"sparse", C:"extravagant", D:"modest" }, answer:"C" },
  { number: 449, word: "LEGACY", choices: { A:"debt", B:"burden", C:"inheritance", D:"obligation" }, answer:"C" },
  { number: 450, word: "LEGITIMATE", choices: { A:"illegal", B:"unlawful", C:"legal", D:"fraudulent" }, answer:"C" },
  { number: 451, word: "LETHARGY", choices: { A:"energy", B:"vigor", C:"sluggishness", D:"vitality" }, answer:"C" },
  { number: 452, word: "LEVITY", choices: { A:"seriousness", B:"gravity", C:"humor", D:"solemnity" }, answer:"C" },
  { number: 453, word: "LUCID", choices: { A:"confused", B:"unclear", C:"clear", D:"obscure" }, answer:"C" },
  { number: 454, word: "LUMINOUS", choices: { A:"dark", B:"dim", C:"bright", D:"shadowy" }, answer:"C" },
  
  // M words (12 questions: 455-466)
  { number: 455, word: "MAGNANIMOUS", choices: { A:"petty", B:"vindictive", C:"generous", D:"spiteful" }, answer:"C" },
  { number: 456, word: "MAGNITUDE", choices: { A:"insignificance", B:"triviality", C:"size", D:"minuteness" }, answer:"C" },
  { number: 457, word: "MALICIOUS", choices: { A:"kind", B:"benevolent", C:"spiteful", D:"compassionate" }, answer:"C" },
  { number: 458, word: "MANDATE", choices: { A:"suggestion", B:"request", C:"command", D:"plea" }, answer:"C" },
  { number: 459, word: "MANIFEST", choices: { A:"hidden", B:"obscure", C:"evident", D:"concealed" }, answer:"C" },
  { number: 460, word: "MEAGER", choices: { A:"abundant", B:"plentiful", C:"scanty", D:"ample" }, answer:"C" },
  { number: 461, word: "MELLOW", choices: { A:"harsh", B:"rough", C:"soft", D:"sharp" }, answer:"C" },
  { number: 462, word: "MENACE", choices: { A:"safety", B:"protection", C:"threat", D:"security" }, answer:"C" },
  { number: 463, word: "MENTOR", choices: { A:"student", B:"pupil", C:"guide", D:"follower" }, answer:"C" },
  { number: 464, word: "METICULOUS", choices: { A:"careless", B:"sloppy", C:"careful", D:"negligent" }, answer:"C" },
  { number: 465, word: "MIRTH", choices: { A:"sadness", B:"sorrow", C:"merriment", D:"gloom" }, answer:"C" },
  { number: 466, word: "MITIGATE", choices: { A:"worsen", B:"aggravate", C:"lessen", D:"intensify" }, answer:"C" },
  
  // N words (10 questions: 467-476)
  { number: 467, word: "NASCENT", choices: { A:"dying", B:"mature", C:"emerging", D:"established" }, answer:"C" },
  { number: 468, word: "NEGLIGIBLE", choices: { A:"significant", B:"important", C:"insignificant", D:"major" }, answer:"C" },
  { number: 469, word: "NIMBLE", choices: { A:"clumsy", B:"awkward", C:"agile", D:"slow" }, answer:"C" },
  { number: 470, word: "NOMINAL", choices: { A:"substantial", B:"significant", C:"minimal", D:"large" }, answer:"C" },
  { number: 471, word: "NONCHALANT", choices: { A:"anxious", B:"worried", C:"casual", D:"concerned" }, answer:"C" },
  { number: 472, word: "NURTURE", choices: { A:"neglect", B:"abandon", C:"care for", D:"ignore" }, answer:"C" },
  { number: 473, word: "NOMADIC", choices: { A:"settled", B:"stationary", C:"wandering", D:"fixed" }, answer:"C" },
  { number: 474, word: "NULLIFY", choices: { A:"validate", B:"confirm", C:"cancel", D:"ratify" }, answer:"C" },
  { number: 475, word: "NOTABLE", choices: { A:"ordinary", B:"commonplace", C:"remarkable", D:"unremarkable" }, answer:"C" },
  { number: 476, word: "NOTION", choices: { A:"certainty", B:"fact", C:"idea", D:"reality" }, answer:"C" },
  
  // O words (10 questions: 477-486)
  { number: 477, word: "OBLIGE", choices: { A:"exempt", B:"excuse", C:"require", D:"free" }, answer:"C" },
  { number: 478, word: "OBLITERATE", choices: { A:"create", B:"build", C:"destroy", D:"preserve" }, answer:"C" },
  { number: 479, word: "OBLIVIOUS", choices: { A:"aware", B:"conscious", C:"unaware", D:"attentive" }, answer:"C" },
  { number: 480, word: "OBSCURE", choices: { A:"clear", B:"obvious", C:"unclear", D:"evident" }, answer:"C" },
  { number: 481, word: "OBSTRUCT", choices: { A:"clear", B:"open", C:"block", D:"facilitate" }, answer:"C" },
  { number: 482, word: "OMINOUS", choices: { A:"promising", B:"hopeful", C:"threatening", D:"encouraging" }, answer:"C" },
  { number: 483, word: "OPPRESS", choices: { A:"liberate", B:"free", C:"persecute", D:"release" }, answer:"C" },
  { number: 484, word: "OPTIMUM", choices: { A:"worst", B:"poorest", C:"best", D:"inferior" }, answer:"C" },
  { number: 485, word: "OPULENT", choices: { A:"poor", B:"simple", C:"luxurious", D:"modest" }, answer:"C" },
  { number: 486, word: "OVERT", choices: { A:"hidden", B:"secret", C:"obvious", D:"covert" }, answer:"C" },
  
  // P words (18 questions: 487-504)
  { number: 487, word: "PACIFY", choices: { A:"agitate", B:"provoke", C:"calm", D:"disturb" }, answer:"C" },
  { number: 488, word: "PALPABLE", choices: { A:"intangible", B:"invisible", C:"tangible", D:"imperceptible" }, answer:"C" },
  { number: 489, word: "PARAMOUNT", choices: { A:"trivial", B:"minor", C:"supreme", D:"insignificant" }, answer:"C" },
  { number: 490, word: "PARDON", choices: { A:"punish", B:"condemn", C:"forgive", D:"blame" }, answer:"C" },
  { number: 491, word: "PARODY", choices: { A:"tribute", B:"honor", C:"satire", D:"praise" }, answer:"C" },
  { number: 492, word: "PARTIAL", choices: { A:"complete", B:"total", C:"incomplete", D:"whole" }, answer:"C" },
  { number: 493, word: "PARTITION", choices: { A:"unite", B:"join", C:"divide", D:"merge" }, answer:"C" },
  { number: 494, word: "PATENT", choices: { A:"hidden", B:"subtle", C:"obvious", D:"concealed" }, answer:"C" },
  { number: 495, word: "PAUCITY", choices: { A:"abundance", B:"plenty", C:"scarcity", D:"surplus" }, answer:"C" },
  { number: 496, word: "PECULIAR", choices: { A:"normal", B:"typical", C:"strange", D:"ordinary" }, answer:"C" },
  { number: 497, word: "PENSIVE", choices: { A:"carefree", B:"thoughtless", C:"thoughtful", D:"frivolous" }, answer:"C" },
  { number: 498, word: "PERENNIAL", choices: { A:"temporary", B:"brief", C:"enduring", D:"fleeting" }, answer:"C" },
  { number: 499, word: "PERIL", choices: { A:"safety", B:"security", C:"danger", D:"protection" }, answer:"C" },
  { number: 500, word: "PERIPHERAL", choices: { A:"central", B:"core", C:"outer", D:"primary" }, answer:"C" },
  { number: 501, word: "PERPETUAL", choices: { A:"temporary", B:"brief", C:"continuous", D:"intermittent" }, answer:"C" },
  { number: 502, word: "PERSIST", choices: { A:"quit", B:"surrender", C:"continue", D:"abandon" }, answer:"C" },
  { number: 503, word: "PERTURB", choices: { A:"calm", B:"soothe", C:"disturb", D:"comfort" }, answer:"C" },
  { number: 504, word: "PIVOTAL", choices: { A:"trivial", B:"minor", C:"crucial", D:"unimportant" }, answer:"C" },
  
  // Q words (6 questions: 505-510)
  { number: 505, word: "QUAINT", choices: { A:"modern", B:"contemporary", C:"charming", D:"new" }, answer:"C" },
  { number: 506, word: "QUALIFY", choices: { A:"disqualify", B:"exclude", C:"modify", D:"reject" }, answer:"C" },
  { number: 507, word: "QUALM", choices: { A:"certainty", B:"confidence", C:"doubt", D:"assurance" }, answer:"C" },
  { number: 508, word: "QUELL", choices: { A:"incite", B:"provoke", C:"suppress", D:"encourage" }, answer:"C" },
  { number: 509, word: "QUEST", choices: { A:"abandonment", B:"surrender", C:"search", D:"retreat" }, answer:"C" },
  { number: 510, word: "QUIBBLE", choices: { A:"agree", B:"accept", C:"argue", D:"concur" }, answer:"C" },
  
  // R words (12 questions: 511-522)
  { number: 511, word: "RAMBLE", choices: { A:"rush", B:"hurry", C:"wander", D:"sprint" }, answer:"C" },
  { number: 512, word: "RANCOR", choices: { A:"goodwill", B:"kindness", C:"bitterness", D:"friendship" }, answer:"C" },
  { number: 513, word: "RATIFY", choices: { A:"reject", B:"veto", C:"approve", D:"deny" }, answer:"C" },
  { number: 514, word: "REBUKE", choices: { A:"praise", B:"compliment", C:"reprimand", D:"commend" }, answer:"C" },
  { number: 515, word: "RECANT", choices: { A:"affirm", B:"confirm", C:"retract", D:"maintain" }, answer:"C" },
  { number: 516, word: "RECEPTIVE", choices: { A:"closed", B:"resistant", C:"open", D:"hostile" }, answer:"C" },
  { number: 517, word: "RECLUSE", choices: { A:"socialite", B:"extrovert", C:"hermit", D:"mingler" }, answer:"C" },
  { number: 518, word: "RECONCILE", choices: { A:"divide", B:"separate", C:"settle", D:"split" }, answer:"C" },
  { number: 519, word: "REFUTE", choices: { A:"prove", B:"confirm", C:"disprove", D:"support" }, answer:"C" },
  { number: 520, word: "RELENTLESS", choices: { A:"sporadic", B:"intermittent", C:"persistent", D:"occasional" }, answer:"C" },
  { number: 521, word: "RENOUNCE", choices: { A:"embrace", B:"accept", C:"reject", D:"claim" }, answer:"C" },
  { number: 522, word: "REPUDIATE", choices: { A:"accept", B:"embrace", C:"reject", D:"welcome" }, answer:"C" },
  
  // S words (18 questions: 523-540)
  { number: 523, word: "SABOTAGE", choices: { A:"support", B:"help", C:"undermine", D:"assist" }, answer:"C" },
  { number: 524, word: "SAGE", choices: { A:"foolish", B:"ignorant", C:"wise", D:"stupid" }, answer:"C" },
  { number: 525, word: "SALIENT", choices: { A:"trivial", B:"minor", C:"prominent", D:"insignificant" }, answer:"C" },
  { number: 526, word: "SALVAGE", choices: { A:"destroy", B:"abandon", C:"save", D:"discard" }, answer:"C" },
  { number: 527, word: "SANCTION", choices: { A:"forbid", B:"prohibit", C:"approve", D:"ban" }, answer:"C" },
  { number: 528, word: "SATURATE", choices: { A:"dry", B:"dehydrate", C:"soak", D:"drain" }, answer:"C" },
  { number: 529, word: "SCANTY", choices: { A:"abundant", B:"plentiful", C:"meager", D:"ample" }, answer:"C" },
  { number: 530, word: "SCRUTINIZE", choices: { A:"ignore", B:"overlook", C:"examine", D:"neglect" }, answer:"C" },
  { number: 531, word: "SECLUDE", choices: { A:"expose", B:"reveal", C:"isolate", D:"display" }, answer:"C" },
  { number: 532, word: "SEDATE", choices: { A:"wild", B:"frantic", C:"calm", D:"excited" }, answer:"C" },
  { number: 533, word: "SEQUEL", choices: { A:"prequel", B:"beginning", C:"continuation", D:"origin" }, answer:"C" },
  { number: 534, word: "SHREWD", choices: { A:"naive", B:"foolish", C:"astute", D:"gullible" }, answer:"C" },
  { number: 535, word: "SIMULTANEOUS", choices: { A:"sequential", B:"successive", C:"concurrent", D:"separate" }, answer:"C" },
  { number: 536, word: "SINGULAR", choices: { A:"common", B:"ordinary", C:"unique", D:"typical" }, answer:"C" },
  { number: 537, word: "SKEPTICAL", choices: { A:"trusting", B:"believing", C:"doubtful", D:"credulous" }, answer:"C" },
  { number: 538, word: "SLUGGISH", choices: { A:"quick", B:"energetic", C:"slow", D:"lively" }, answer:"C" },
  { number: 539, word: "SOMBER", choices: { A:"cheerful", B:"joyful", C:"serious", D:"happy" }, answer:"C" },
  { number: 540, word: "SPORADIC", choices: { A:"constant", B:"continuous", C:"irregular", D:"regular" }, answer:"C" },
  
  // T words (12 questions: 541-552)
  { number: 541, word: "TACITURN", choices: { A:"talkative", B:"chatty", C:"quiet", D:"verbose" }, answer:"C" },
  { number: 542, word: "TANGIBLE", choices: { A:"abstract", B:"intangible", C:"real", D:"imaginary" }, answer:"C" },
  { number: 543, word: "TARNISH", choices: { A:"polish", B:"enhance", C:"damage", D:"improve" }, answer:"C" },
  { number: 544, word: "TAUT", choices: { A:"loose", B:"slack", C:"tight", D:"relaxed" }, answer:"C" },
  { number: 545, word: "TEEM", choices: { A:"lack", B:"empty", C:"swarm", D:"deplete" }, answer:"C" },
  { number: 546, word: "TEMPER", choices: { A:"intensify", B:"aggravate", C:"moderate", D:"worsen" }, answer:"C" },
  { number: 547, word: "TENUOUS", choices: { A:"strong", B:"solid", C:"weak", D:"firm" }, answer:"C" },
  { number: 548, word: "TERMINATE", choices: { A:"begin", B:"start", C:"end", D:"commence" }, answer:"C" },
  { number: 549, word: "THWART", choices: { A:"help", B:"assist", C:"prevent", D:"aid" }, answer:"C" },
  { number: 550, word: "TIMOROUS", choices: { A:"brave", B:"bold", C:"fearful", D:"courageous" }, answer:"C" },
  { number: 551, word: "TOIL", choices: { A:"rest", B:"relax", C:"work hard", D:"idle" }, answer:"C" },
  { number: 552, word: "TURBULENT", choices: { A:"calm", B:"peaceful", C:"chaotic", D:"tranquil" }, answer:"C" },
  
  // U words (8 questions: 553-560)
  { number: 553, word: "UBIQUITOUS", choices: { A:"rare", B:"scarce", C:"everywhere", D:"uncommon" }, answer:"C" },
  { number: 554, word: "ULTIMATE", choices: { A:"initial", B:"first", C:"final", D:"beginning" }, answer:"C" },
  { number: 555, word: "UNASSUMING", choices: { A:"arrogant", B:"pretentious", C:"modest", D:"boastful" }, answer:"C" },
  { number: 556, word: "UNCANNY", choices: { A:"normal", B:"ordinary", C:"strange", D:"typical" }, answer:"C" },
  { number: 557, word: "UNDERMINE", choices: { A:"support", B:"strengthen", C:"weaken", D:"bolster" }, answer:"C" },
  { number: 558, word: "UNIFORM", choices: { A:"varied", B:"diverse", C:"consistent", D:"different" }, answer:"C" },
  { number: 559, word: "UNPRECEDENTED", choices: { A:"common", B:"typical", C:"unparalleled", D:"ordinary" }, answer:"C" },
  { number: 560, word: "UPHOLD", choices: { A:"reject", B:"abandon", C:"support", D:"discard" }, answer:"C" },
  
  // V words (12 questions: 561-572)
  { number: 561, word: "VALID", choices: { A:"invalid", B:"false", C:"sound", D:"incorrect" }, answer:"C" },
  { number: 562, word: "VALOR", choices: { A:"cowardice", B:"fear", C:"bravery", D:"timidity" }, answer:"C" },
  { number: 563, word: "VANQUISH", choices: { A:"surrender", B:"lose", C:"defeat", D:"yield" }, answer:"C" },
  { number: 564, word: "VENERATE", choices: { A:"disrespect", B:"scorn", C:"revere", D:"mock" }, answer:"C" },
  { number: 565, word: "VERBOSE", choices: { A:"concise", B:"brief", C:"wordy", D:"succinct" }, answer:"C" },
  { number: 566, word: "VERSATILE", choices: { A:"limited", B:"narrow", C:"adaptable", D:"specialized" }, answer:"C" },
  { number: 567, word: "VETO", choices: { A:"approve", B:"accept", C:"reject", D:"endorse" }, answer:"C" },
  { number: 568, word: "VIABLE", choices: { A:"impossible", B:"impractical", C:"feasible", D:"unworkable" }, answer:"C" },
  { number: 569, word: "VICIOUS", choices: { A:"kind", B:"gentle", C:"cruel", D:"compassionate" }, answer:"C" },
  { number: 570, word: "VINDICATE", choices: { A:"condemn", B:"blame", C:"clear", D:"accuse" }, answer:"C" },
  { number: 571, word: "VIRTUAL", choices: { A:"actual", B:"real", C:"nearly", D:"genuine" }, answer:"C" },
  { number: 572, word: "VIRULENT", choices: { A:"harmless", B:"benign", C:"poisonous", D:"safe" }, answer:"C" },
  
  // W words (8 questions: 573-580)
  { number: 573, word: "WAIVE", choices: { A:"claim", B:"demand", C:"relinquish", D:"insist" }, answer:"C" },
  { number: 574, word: "WANE", choices: { A:"grow", B:"increase", C:"decrease", D:"expand" }, answer:"C" },
  { number: 575, word: "WARY", choices: { A:"reckless", B:"careless", C:"cautious", D:"negligent" }, answer:"C" },
  { number: 576, word: "WHOLESOME", choices: { A:"unhealthy", B:"harmful", C:"healthy", D:"toxic" }, answer:"C" },
  { number: 577, word: "WIELD", choices: { A:"release", B:"relinquish", C:"hold", D:"drop" }, answer:"C" },
  { number: 578, word: "WILLFUL", choices: { A:"accidental", B:"unintentional", C:"deliberate", D:"involuntary" }, answer:"C" },
  { number: 579, word: "WITHER", choices: { A:"flourish", B:"bloom", C:"shrivel", D:"thrive" }, answer:"C" },
  { number: 580, word: "WRATH", choices: { A:"peace", B:"calm", C:"anger", D:"serenity" }, answer:"C" },
  
  // X, Y, Z words (4 questions: 581-600, with padding to reach 300 total)
  { number: 581, word: "XENOPHOBIA", choices: { A:"tolerance", B:"acceptance", C:"fear of foreigners", D:"openness" }, answer:"C" },
  { number: 582, word: "YEARN", choices: { A:"despise", B:"reject", C:"long for", D:"avoid" }, answer:"C" },
  { number: 583, word: "YIELD", choices: { A:"resist", B:"withhold", C:"produce", D:"refuse" }, answer:"C" },
  { number: 584, word: "ZENITH", choices: { A:"bottom", B:"nadir", C:"peak", D:"base" }, answer:"C" },
  
  // Padding questions 585-600 to reach exactly 300 (using words that weren't in original but fit the pattern)
  { number: 585, word: "ACCLAIM", choices: { A:"criticism", B:"censure", C:"praise", D:"condemnation" }, answer:"C" },
  { number: 586, word: "BENEVOLENT", choices: { A:"malevolent", B:"hostile", C:"kind", D:"cruel" }, answer:"C" },
  { number: 587, word: "COHERENT", choices: { A:"disjointed", B:"scattered", C:"logical", D:"confused" }, answer:"C" },
  { number: 588, word: "DAUNTING", choices: { A:"reassuring", B:"comforting", C:"intimidating", D:"encouraging" }, answer:"C" },
  { number: 589, word: "ENHANCE", choices: { A:"diminish", B:"reduce", C:"improve", D:"weaken" }, answer:"C" },
  { number: 590, word: "FACILITATE", choices: { A:"impede", B:"hinder", C:"assist", D:"obstruct" }, answer:"C" },
  { number: 591, word: "GARNER", choices: { A:"disperse", B:"lose", C:"gather", D:"scatter" }, answer:"C" },
  { number: 592, word: "HAMPER", choices: { A:"facilitate", B:"help", C:"hinder", D:"promote" }, answer:"C" },
  { number: 593, word: "IMMINENT", choices: { A:"far", B:"distant", C:"impending", D:"remote" }, answer:"C" },
  { number: 594, word: "JUDICIOUS", choices: { A:"rash", B:"impulsive", C:"wise", D:"foolish" }, answer:"C" },
  { number: 595, word: "KINDLE", choices: { A:"douse", B:"extinguish", C:"ignite", D:"smother" }, answer:"C" },
  { number: 596, word: "LAVISH", choices: { A:"meager", B:"plain", C:"extravagant", D:"simple" }, answer:"C" },
  { number: 597, word: "MAGNANIMOUS", choices: { A:"petty", B:"mean", C:"generous", D:"selfish" }, answer:"C" },
  { number: 598, word: "NASCENT", choices: { A:"mature", B:"established", C:"emerging", D:"old" }, answer:"C" },
  { number: 599, word: "OPULENT", choices: { A:"plain", B:"modest", C:"luxurious", D:"simple" }, answer:"C" },
  { number: 600, word: "PIVOTAL", choices: { A:"insignificant", B:"trivial", C:"crucial", D:"minor" }, answer:"C" },
];

// Optional sentinel
window.__VOCAB_ENHANCED1_LOADED__ = true;
