// isee_vocab_enhanced_improved.js
// Enhanced Option 1: 300 additional ISEE-level vocabulary words
// These words are at the same difficulty level as the original 300
// None of these words appear in the original list
// Words distributed proportionally across all letters A-Z
// NOTE: This version contains improved questions with more challenging distractors.

window.DEFINITIONS_ENHANCED1 = {
  // A words (12)
  ABSURD: "ridiculous, irrational, nonsensical — Example: The absurd proposal was rejected immediately by the committee.",
  ACCLAIM: "praise, applaud, recognition — Example: The author received widespread acclaim for her debut novel.",
  ACUTE: "sharp, severe, intense — Example: The patient experienced acute pain after the surgery.",
  ADVERSITY: "hardship, misfortune, difficulty — Example: They showed courage in the face of adversity.",
  AFFABLE: "friendly, pleasant, approachable — Example: The affable host made everyone feel comfortable.",
  ALACRITY: "eagerness, enthusiasm, willingness — Example: She accepted the challenge with alacrity.",
  ALLOCATE: "distribute, assign, allot — Example: The manager will allocate resources to each department.",
  AMBUSH: "trap, surprise attack, waylay — Example: The soldiers prepared an ambush along the route.",
  ANALOGY: "comparison, similarity, parallel — Example: The teacher used an analogy to explain the concept.",
  ARBITRARY: "random, unpredictable, capricious — Example: The decision seemed arbitrary and unfair.",
  ASCEND: "rise, climb, mount — Example: The hikers will ascend the mountain at dawn.",
  AUSTERE: "severe, stern, strict — Example: The monastery maintained an austere lifestyle.",

  // B words (12)
  BAFFLE: "confuse, puzzle, perplex — Example: The mystery continued to baffle investigators.",
  BELIE: "contradict, misrepresent, disguise — Example: Her calm demeanor belies her inner anxiety.",
  BENEVOLENT: "kind, charitable, generous — Example: The benevolent donor funded the scholarship program.",
  BESTOW: "give, grant, confer — Example: The university will bestow honorary degrees at graduation.",
  BREVITY: "briefness, conciseness, shortness — Example: The brevity of the speech was appreciated.",
  BRISK: "quick, energetic, lively — Example: They took a brisk walk through the park.",
  BRITTLE: "fragile, delicate, breakable — Example: The brittle branches snapped in the wind.",
  BROOD: "ponder, worry, dwell on — Example: Don't brood over past mistakes for too long.",
  BRUSQUE: "abrupt, blunt, curt — Example: His brusque manner offended the guests.",
  BULWARK: "defense, protection, safeguard — Example: The constitution serves as a bulwark against tyranny.",
  BUOYANT: "cheerful, optimistic, upbeat — Example: She remained buoyant despite the setback.",
  BUTTRESS: "support, reinforce, strengthen — Example: Additional evidence will buttress the argument.",

  // C words (18)
  CANDOR: "honesty, frankness, sincerity — Example: Her candor about the situation was refreshing.",
  CAPACIOUS: "spacious, roomy, large — Example: The capacious hall accommodated all the guests.",
  CEDE: "surrender, yield, relinquish — Example: The nation agreed to cede territory after the war.",
  CIRCUMVENT: "avoid, bypass, evade — Example: They tried to circumvent the traffic by taking side streets.",
  COERCE: "force, compel, pressure — Example: They tried to coerce him into signing the contract.",
  COGNIZANT: "aware, conscious, informed — Example: She was cognizant of the risks involved.",
  COHERENT: "logical, consistent, clear — Example: He presented a coherent argument for the proposal.",
  COMMEMORATE: "honor, celebrate, memorialize — Example: The monument commemorates fallen soldiers.",
  COMPELLING: "convincing, persuasive, forceful — Example: She made a compelling case for reform.",
  COMPENSATE: "repay, reimburse, offset — Example: The company will compensate workers for overtime.",
  COMPLACENT: "satisfied, smug, unconcerned — Example: Don't become complacent after early success.",
  COMPLY: "obey, conform, follow — Example: All employees must comply with safety regulations.",
  COMPOSURE: "calmness, poise, self-control — Example: She maintained her composure during the crisis.",
  COMPREHENSIVE: "complete, thorough, extensive — Example: The report provides a comprehensive analysis.",
  CONDEMN: "criticize, denounce, censure — Example: Leaders condemn the act of violence.",
  CONDUCIVE: "helpful, favorable, beneficial — Example: A quiet room is conducive to studying.",
  CONSENSUS: "agreement, accord, unity — Example: The committee reached a consensus on the issue.",
  CONSTRAIN: "restrict, limit, restrain — Example: Budget cuts constrain the department's activities.",

  // D words (18)
  DAUNTING: "intimidating, discouraging, formidable — Example: The daunting task required careful planning.",
  DEFT: "skillful, adept, expert — Example: The surgeon's deft movements ensured success.",
  DELEGATE: "assign, entrust, authorize — Example: The manager will delegate tasks to team members.",
  DELINEATE: "outline, describe, define — Example: The contract clearly delineates each party's duties.",
  DENOUNCE: "condemn, criticize, censure — Example: The senator denounced corruption in government.",
  DEPLETE: "exhaust, drain, use up — Example: Overfishing can deplete marine resources.",
  DERIDE: "mock, ridicule, scorn — Example: Critics derided the film as poorly made.",
  DERIVE: "obtain, extract, originate — Example: The medicine is derived from natural plants.",
  DETER: "discourage, prevent, inhibit — Example: Strict penalties deter illegal behavior.",
  DEVIATE: "diverge, stray, differ — Example: Don't deviate from the planned route.",
  DEVISE: "invent, create, formulate — Example: Scientists devise new methods for research.",
  DILIGENT: "hardworking, industrious, conscientious — Example: Diligent students earn better grades.",
  DISCERN: "perceive, detect, distinguish — Example: It's hard to discern truth from fiction.",
  DISCRETE: "separate, distinct, individual — Example: The process involves three discrete stages.",
  DISPARITY: "difference, inequality, gap — Example: There's a disparity in pay between positions.",
  DISPERSE: "scatter, spread, disseminate — Example: Police ordered crowds to disperse peacefully.",
  DISSENT: "disagreement, opposition, protest — Example: One judge filed a dissent from the ruling.",
  DIVERGE: "separate, split, branch — Example: Their opinions diverge on economic policy.",

  // E words (18)
  ECCENTRIC: "unconventional, odd, quirky — Example: The eccentric artist lived in a converted warehouse.",
  EDIFY: "educate, enlighten, instruct — Example: The lecture will edify students on history.",
  ELABORATE: "detailed, complex, intricate — Example: She presented an elaborate plan for expansion.",
  ELICIT: "draw out, evoke, extract — Example: The questions elicit thoughtful responses.",
  ELIGIBLE: "qualified, suitable, acceptable — Example: Graduates are eligible for the scholarship.",
  ELUCIDATE: "explain, clarify, illuminate — Example: The professor will elucidate the theorem.",
  EMANATE: "originate, emerge, issue — Example: Light emanates from the distant star.",
  EMANCIPATE: "free, liberate, release — Example: The proclamation aimed to emancipate enslaved people.",
  EMBARK: "begin, start, commence — Example: They will embark on a new venture next month.",
  EMERGE: "appear, surface, arise — Example: New leaders emerge during times of crisis.",
  EMINENT: "distinguished, prominent, renowned — Example: An eminent scholar delivered the keynote address.",
  EMPHASIZE: "stress, highlight, underscore — Example: Teachers emphasize the importance of reading.",
  EMPIRICAL: "experimental, observed, factual — Example: The theory requires empirical evidence.",
  EMULATE: "imitate, copy, follow — Example: Young athletes emulate their sports heroes.",
  ENCOMPASS: "include, contain, comprise — Example: The study encompasses multiple disciplines.",
  ENDORSE: "support, approve, back — Example: The organization will endorse the candidate.",
  ENHANCE: "improve, increase, augment — Example: New features enhance the product's appeal.",
  ENLIGHTEN: "inform, educate, illuminate — Example: The documentary will enlighten viewers about wildlife.",

  // F words (18)
  FACILITATE: "assist, help, enable — Example: Technology can facilitate remote learning.",
  FACILE: "easy, simple, effortless — Example: The problem has no facile solution.",
  FALLOW: "unused, dormant, inactive — Example: The field lay fallow for a season.",
  FEASIBLE: "possible, practical, workable — Example: The plan seems feasible with proper funding.",
  FEIGN: "pretend, fake, simulate — Example: She tried to feign interest in the conversation.",
  FINITE: "limited, bounded, restricted — Example: Natural resources are finite and must be conserved.",
  FLAGRANT: "blatant, obvious, glaring — Example: The violation was a flagrant breach of rules.",
  FLAW: "defect, fault, imperfection — Example: Engineers discovered a flaw in the design.",
  FLUCTUATE: "vary, change, waver — Example: Stock prices fluctuate throughout the day.",
  FLUENT: "smooth, flowing, articulate — Example: She is fluent in three languages.",
  FOIBLE: "weakness, flaw, quirk — Example: Everyone has minor foibles and imperfections.",
  FORBEAR: "refrain, abstain, withhold — Example: Please forbear from interrupting the speaker.",
  FORESTALL: "prevent, hinder, obstruct — Example: Quick action can forestall serious problems.",
  FORGE: "create, form, shape — Example: Nations forge alliances during wartime.",
  FORSAKE: "abandon, desert, renounce — Example: She refused to forsake her principles.",
  FORTIFY: "strengthen, reinforce, secure — Example: Troops fortify their positions against attack.",
  FOSTER: "encourage, promote, nurture — Example: Good teachers foster creativity in students.",
  FRAUGHT: "filled, laden, charged — Example: The situation is fraught with danger.",

  // G words (12)
  GARNER: "gather, collect, accumulate — Example: The film will garner critical acclaim.",
  GAUNT: "thin, emaciated, haggard — Example: Illness left him gaunt and weak.",
  GENERIC: "general, common, universal — Example: The store sells generic brands at lower prices.",
  GENIAL: "friendly, cordial, amiable — Example: The genial host welcomed all guests warmly.",
  GESTURE: "signal, sign, motion — Example: She made a gesture of apology.",
  GHASTLY: "horrible, dreadful, shocking — Example: The accident scene was ghastly.",
  GIST: "essence, main point, core — Example: Can you summarize the gist of the article?",
  GLEAN: "gather, collect, extract — Example: Researchers glean data from multiple sources.",
  GLIB: "smooth, fluent, slick — Example: His glib response failed to convince anyone.",
  GRACIOUS: "courteous, kind, polite — Example: She was gracious in accepting the award.",
  GRADUAL: "slow, steady, progressive — Example: Gradual changes are easier to adapt to.",
  GRATIFY: "please, satisfy, delight — Example: The results gratify months of hard work.",

  // H words (12)
  HACKNEYED: "overused, trite, cliched — Example: The speech was full of hackneyed phrases.",
  HAMPER: "hinder, obstruct, impede — Example: Bad weather will hamper rescue efforts.",
  HARMONIOUS: "agreeable, compatible, peaceful — Example: The team worked in harmonious cooperation.",
  HASTEN: "hurry, rush, accelerate — Example: They must hasten to meet the deadline.",
  HAUGHTY: "arrogant, proud, disdainful — Example: His haughty manner alienated colleagues.",
  HAVOC: "chaos, destruction, disorder — Example: The storm wreaked havoc on coastal towns.",
  HEED: "notice, attention, consideration — Example: Pay heed to the warning signs.",
  HEINOUS: "evil, wicked, atrocious — Example: The court condemned the heinous crime.",
  HERALD: "announce, proclaim, signal — Example: Spring flowers herald the arrival of warmer weather.",
  HERMIT: "recluse, loner, solitary — Example: The hermit lived alone in the mountains.",
  HINDER: "obstruct, impede, block — Example: Traffic congestion will hinder our progress.",
  HUMBLE: "modest, unassuming, unpretentious — Example: Despite success, she remained humble.",

  // I words (12)
  IDEOLOGY: "belief system, doctrine, philosophy — Example: Political parties differ in ideology.",
  IGNITE: "light, kindle, inflame — Example: A single spark can ignite a forest fire.",
  ILLICIT: "illegal, unlawful, forbidden — Example: Police cracked down on illicit drug trade.",
  ILLUMINATE: "light up, clarify, explain — Example: Lamps illuminate the dark pathway.",
  IMMACULATE: "perfect, spotless, flawless — Example: The bride's gown was immaculate.",
  IMMERSE: "submerge, engross, absorb — Example: She likes to immerse herself in novels.",
  IMMINENT: "impending, approaching, near — Example: Forecasters warn of imminent severe weather.",
  IMPAIR: "damage, harm, weaken — Example: Poor lighting can impair vision.",
  IMPECCABLE: "flawless, perfect, faultless — Example: His impeccable manners impressed everyone.",
  IMPEDE: "hinder, obstruct, block — Example: Debris will impede traffic flow.",
  IMPERATIVE: "essential, necessary, urgent — Example: It is imperative that we act quickly.",
  IMPERVIOUS: "resistant, immune, impenetrable — Example: The material is impervious to water.",

  // J words (6)
  JEOPARDIZE: "endanger, threaten, risk — Example: Careless actions could jeopardize the mission.",
  JUBILANT: "joyful, exultant, triumphant — Example: The jubilant crowd celebrated the victory.",
  JUDICIOUS: "wise, sensible, prudent — Example: She made a judicious decision after careful thought.",
  JUNCTION: "intersection, crossroads, connection — Example: Turn left at the next junction.",
  JUSTIFY: "defend, explain, validate — Example: Can you justify your reasoning?",
  JUXTAPOSE: "place side by side, compare, contrast — Example: The exhibit juxtaposes ancient and modern art.",

  // K words (4)
  KINDLE: "ignite, light, spark — Example: Dry wood helps kindle a fire quickly.",
  KNACK: "talent, skill, aptitude — Example: She has a knack for solving puzzles.",
  KNOLL: "hill, mound, rise — Example: They picnicked on a grassy knoll.",
  KUDOS: "praise, acclaim, recognition — Example: Kudos to the team for excellent work.",

  // L words (12)
  LABORIOUS: "difficult, arduous, strenuous — Example: The laborious task took all day.",
  LAMPOON: "satirize, mock, ridicule — Example: The comedy show lampooned political figures.",
  LANGUID: "sluggish, lethargic, weak — Example: The humid weather made everyone feel languid.",
  LATENT: "dormant, hidden, potential — Example: Her latent talent emerged during the performance.",
  LAUDABLE: "praiseworthy, commendable, admirable — Example: The volunteers' efforts are laudable.",
  LAVISH: "extravagant, luxurious, abundant — Example: They hosted a lavish celebration.",
  LEGACY: "inheritance, bequest, heritage — Example: His legacy lives on through his charitable work.",
  LEGITIMATE: "legal, valid, lawful — Example: The document appeared to be legitimate.",
  LETHARGY: "sluggishness, inactivity, apathy — Example: The heat caused widespread lethargy.",
  LEVITY: "humor, lightheartedness, frivolity — Example: A little levity helped ease the tension.",
  LUCID: "clear, understandable, coherent — Example: The professor gave a lucid explanation.",
  LUMINOUS: "bright, shining, radiant — Example: The moon cast a luminous glow over the lake.",

  // M words (12)
  MAGNANIMOUS: "generous, forgiving, noble — Example: The magnanimous leader pardoned his critics.",
  MAGNITUDE: "size, extent, importance — Example: The magnitude of the problem became clear.",
  MALICIOUS: "spiteful, mean, vindictive — Example: The malicious rumors spread quickly.",
  MANDATE: "command, order, directive — Example: The government issued a mandate for safety measures.",
  MANIFEST: "evident, obvious, clear — Example: Her talent was manifest from an early age.",
  MEAGER: "scanty, sparse, inadequate — Example: They survived on meager rations.",
  MELLOW: "soft, gentle, easygoing — Example: His personality mellowed with age.",
  MENACE: "threat, danger, peril — Example: The storm posed a menace to coastal areas.",
  MENTOR: "guide, advisor, teacher — Example: She found a mentor to help with her career.",
  METICULOUS: "careful, thorough, precise — Example: He kept meticulous records of expenses.",
  MIRTH: "merriment, joy, laughter — Example: The party was full of mirth and celebration.",
  MITIGATE: "lessen, reduce, alleviate — Example: Sandbags helped mitigate flood damage.",

  // N words (10)
  NASCENT: "emerging, budding, developing — Example: The nascent technology shows great promise.",
  NEGLIGIBLE: "insignificant, trivial, minor — Example: The cost difference is negligible.",
  NIMBLE: "agile, quick, spry — Example: The nimble dancer leaped across the stage.",
  NOMINAL: "minimal, small, token — Example: They charged only a nominal fee.",
  NONCHALANT: "casual, indifferent, unconcerned — Example: He gave a nonchalant shrug.",
  NURTURE: "care for, foster, cultivate — Example: Parents nurture their children's talents.",
  NOMADIC: "wandering, roaming, itinerant — Example: The nomadic tribe moved with the seasons.",
  NULLIFY: "cancel, invalidate, void — Example: The court will nullify the contract.",
  NOTABLE: "remarkable, significant, noteworthy — Example: She achieved notable success in her field.",
  NOTION: "idea, concept, belief — Example: He had a vague notion of what to do.",

  // O words (10)
  OBLIGE: "require, compel, accommodate — Example: The law will oblige companies to report emissions.",
  OBLITERATE: "destroy, erase, eliminate — Example: The explosion obliterated the building.",
  OBLIVIOUS: "unaware, unconscious, ignorant — Example: He seemed oblivious to the danger.",
  OBSCURE: "unclear, vague, hidden — Example: The meaning remained obscure to most readers.",
  OBSTRUCT: "block, hinder, impede — Example: Fallen trees obstruct the trail.",
  OMINOUS: "threatening, menacing, foreboding — Example: Dark clouds cast an ominous shadow.",
  OPPRESS: "persecute, tyrannize, subjugate — Example: The regime continued to oppress minorities.",
  OPTIMUM: "best, ideal, optimal — Example: These are the optimum conditions for growth.",
  OPULENT: "luxurious, wealthy, lavish — Example: The opulent mansion had marble floors.",
  OVERT: "obvious, open, apparent — Example: His overt hostility surprised everyone.",

  // P words (18)
  PACIFY: "calm, soothe, appease — Example: Soft music helped pacify the crying baby.",
  PALPABLE: "tangible, obvious, evident — Example: The tension in the room was palpable.",
  PARAMOUNT: "supreme, primary, foremost — Example: Safety is of paramount importance.",
  PARDON: "forgive, excuse, absolve — Example: The governor granted a pardon to the prisoner.",
  PARODY: "satire, mockery, imitation — Example: The play was a parody of political debates.",
  PARTIAL: "incomplete, biased, limited — Example: We have only a partial understanding.",
  PARTITION: "divide, separate, section — Example: A screen will partition the room.",
  PATENT: "obvious, clear, evident — Example: His patent dishonesty angered everyone.",
  PAUCITY: "scarcity, shortage, lack — Example: There's a paucity of evidence in this case.",
  PECULIAR: "strange, odd, unusual — Example: The building has a peculiar architecture.",
  PENSIVE: "thoughtful, reflective, contemplative — Example: She sat in a pensive mood.",
  PERENNIAL: "enduring, lasting, permanent — Example: Water shortage is a perennial problem.",
  PERIL: "danger, risk, hazard — Example: The climbers faced great peril on the mountain.",
  PERIPHERAL: "outer, marginal, secondary — Example: Cost is a peripheral concern right now.",
  PERPETUAL: "continuous, endless, eternal — Example: The waterfall's perpetual roar filled the valley.",
  PERSIST: "continue, persevere, endure — Example: The symptoms persist despite treatment.",
  PERTURB: "disturb, upset, trouble — Example: The news will perturb investors.",
  PIVOTAL: "crucial, critical, vital — Example: This is a pivotal moment in history.",

  // Q words (6)
  QUAINT: "charming, old-fashioned, picturesque — Example: The quaint village attracted tourists.",
  QUALIFY: "modify, limit, meet requirements — Example: Few candidates qualify for the position.",
  QUALM: "doubt, misgiving, scruple — Example: She had no qualms about speaking up.",
  QUELL: "suppress, subdue, crush — Example: Police moved to quell the riot.",
  QUEST: "search, pursuit, journey — Example: The scientist's quest for truth continues.",
  QUIBBLE: "argue, object, nitpick — Example: Don't quibble over minor details.",

  // R words (12)
  RAMBLE: "wander, roam, meander — Example: We rambled through the countryside.",
  RANCOR: "bitterness, resentment, animosity — Example: The debate was filled with rancor.",
  RATIFY: "approve, confirm, sanction — Example: Congress will ratify the treaty.",
  REBUKE: "reprimand, scold, criticize — Example: The manager rebuked the employee for tardiness.",
  RECANT: "retract, withdraw, renounce — Example: The witness refused to recant his testimony.",
  RECEPTIVE: "open, responsive, amenable — Example: Students were receptive to new ideas.",
  RECLUSE: "hermit, loner, solitary person — Example: The author became a recluse in later years.",
  RECONCILE: "settle, resolve, harmonize — Example: They tried to reconcile their differences.",
  REFUTE: "disprove, rebut, contradict — Example: The evidence will refute his claims.",
  RELENTLESS: "persistent, unremitting, continuous — Example: The relentless rain flooded streets.",
  RENOUNCE: "reject, abandon, disown — Example: He chose to renounce his citizenship.",
  REPUDIATE: "reject, deny, disavow — Example: The senator repudiated the accusations.",

  // S words (18)
  SABOTAGE: "undermine, damage, subvert — Example: Hackers attempted to sabotage the system.",
  SAGE: "wise, prudent, sensible — Example: The sage advisor offered valuable counsel.",
  SALIENT: "prominent, notable, important — Example: She highlighted the salient points.",
  SALVAGE: "save, rescue, recover — Example: Divers will salvage cargo from the wreck.",
  SANCTION: "approve, authorize, permit — Example: The board will sanction the new policy.",
  SATURATE: "soak, drench, permeate — Example: Heavy rains saturated the ground.",
  SCANTY: "meager, sparse, insufficient — Example: Evidence against him was scanty.",
  SCRUTINIZE: "examine, inspect, analyze — Example: Auditors will scrutinize the accounts.",
  SECLUDE: "isolate, segregate, separate — Example: The cabin is secluded in the woods.",
  SEDATE: "calm, composed, dignified — Example: The ceremony proceeded at a sedate pace.",
  SEQUEL: "continuation, follow-up, result — Example: The sequel surpassed the original film.",
  SHREWD: "astute, clever, sharp — Example: She made a shrewd business decision.",
  SIMULTANEOUS: "concurrent, coinciding, synchronous — Example: The events were simultaneous.",
  SINGULAR: "unique, exceptional, remarkable — Example: She showed singular dedication.",
  SKEPTICAL: "doubtful, questioning, suspicious — Example: Investors remained skeptical of the claims.",
  SLUGGISH: "slow, lethargic, inactive — Example: The economy remained sluggish.",
  SOMBER: "serious, grave, solemn — Example: The funeral was a somber occasion.",
  SPORADIC: "irregular, occasional, intermittent — Example: There were sporadic outbreaks of violence.",

  // T words (12)
  TACITURN: "quiet, reserved, uncommunicative — Example: The taciturn guard rarely spoke.",
  TANGIBLE: "real, concrete, physical — Example: We need tangible proof of progress.",
  TARNISH: "damage, stain, sully — Example: The scandal will tarnish his reputation.",
  TAUT: "tight, tense, stretched — Example: The rope was pulled taut.",
  TEEM: "swarm, abound, be full of — Example: The river teems with salmon.",
  TEMPER: "moderate, soften, mitigate — Example: She learned to temper her criticism.",
  TENUOUS: "weak, flimsy, uncertain — Example: The connection seems tenuous at best.",
  TERMINATE: "end, conclude, cease — Example: The contract will terminate next month.",
  THWART: "prevent, frustrate, foil — Example: Bad weather thwarted their plans.",
  TIMOROUS: "fearful, timid, apprehensive — Example: The timorous rabbit fled quickly.",
  TOIL: "work hard, labor, struggle — Example: Farmers toil in the fields daily.",
  TURBULENT: "chaotic, stormy, violent — Example: The flight encountered turbulent weather.",

  // U words (8)
  UBIQUITOUS: "everywhere, omnipresent, universal — Example: Smartphones are ubiquitous in modern society.",
  ULTIMATE: "final, eventual, supreme — Example: Victory was their ultimate goal.",
  UNASSUMING: "modest, humble, unpretentious — Example: Despite fame, she remained unassuming.",
  UNCANNY: "strange, mysterious, eerie — Example: She had an uncanny ability to predict trends.",
  UNDERMINE: "weaken, sabotage, subvert — Example: Rumors can undermine public confidence.",
  UNIFORM: "consistent, identical, unchanging — Example: The temperature remained uniform.",
  UNPRECEDENTED: "unparalleled, novel, unique — Example: The crisis was unprecedented in scope.",
  UPHOLD: "support, maintain, sustain — Example: Courts uphold constitutional rights.",

  // V words (12)
  VALID: "sound, legitimate, acceptable — Example: She raised a valid concern.",
  VALOR: "bravery, courage, heroism — Example: Soldiers displayed great valor in battle.",
  VANQUISH: "defeat, conquer, overcome — Example: The army vanquished its enemies.",
  VENERATE: "revere, respect, honor — Example: Many cultures venerate their elders.",
  VERBOSE: "wordy, long-winded, rambling — Example: His verbose speech lasted two hours.",
  VERSATILE: "adaptable, flexible, all-around — Example: She's a versatile performer.",
  VETO: "reject, prohibit, forbid — Example: The president may veto the legislation.",
  VIABLE: "feasible, workable, practical — Example: The plan seems viable with adjustments.",
  VICIOUS: "cruel, brutal, savage — Example: The vicious attack shocked the community.",
  VINDICATE: "clear, exonerate, justify — Example: New evidence will vindicate him.",
  VIRTUAL: "nearly, practically, almost — Example: The project came to a virtual standstill.",
  VIRULENT: "poisonous, toxic, deadly — Example: The virulent disease spread rapidly.",

  // W words (8)
  WAIVE: "relinquish, forgo, surrender — Example: They agreed to waive the fee.",
  WANE: "decrease, decline, diminish — Example: His influence began to wane.",
  WARY: "cautious, careful, vigilant — Example: Be wary of unsolicited offers.",
  WHOLESOME: "healthy, beneficial, nutritious — Example: The family enjoyed wholesome meals.",
  WIELD: "hold, brandish, exercise — Example: The king wielded absolute power.",
  WILLFUL: "deliberate, intentional, stubborn — Example: His willful disobedience had consequences.",
  WITHER: "shrivel, wilt, fade — Example: Plants wither without water.",
  WRATH: "anger, fury, rage — Example: The king's wrath was fearsome.",

  // X, Y, Z words (4)
  XENOPHOBIA: "fear of foreigners, prejudice, intolerance — Example: Xenophobia has no place in modern society.",
  YEARN: "long for, desire, crave — Example: She yearned for adventure.",
  YIELD: "produce, generate, surrender — Example: The fields yield abundant crops.",
  ZENITH: "peak, summit, apex — Example: Her career reached its zenith."
};

window.QUESTIONS_ENHANCED1 = [
  // A words (12 questions: 301-312)
  { number: 301, word: "ABSURD", choices: { A:"ridiculous", B:"unusual", C:"silly", D:"impossible" }, answer:"A" },
  { number: 302, word: "ACCLAIM", choices: { A:"fame", B:"praise", C:"acknowledgment", D:"popularity" }, answer:"B" },
  { number: 303, word: "ACUTE", choices: { A:"sharp", B:"sudden", C:"severe", D:"noticeable" }, answer:"A" },
  { number: 304, word: "ADVERSITY", choices: { A:"disaster", B:"obstacle", C:"hardship", D:"tragedy" }, answer:"C" },
  { number: 305, word: "AFFABLE", choices: { A:"friendly", B:"polite", C:"talkative", D:"welcoming" }, answer:"A" },
  { number: 306, word: "ALACRITY", choices: { A:"eagerness", B:"speed", C:"excitement", D:"happiness" }, answer:"A" },
  { number: 307, word: "ALLOCATE", choices: { A:"organize", B:"share", C:"divide", D:"distribute" }, answer:"D" },
  { number: 308, word: "AMBUSH", choices: { A:"a blockade", B:"an obstacle", C:"a secret plan", D:"a surprise attack" }, answer:"D" },
  { number: 309, word: "ANALOGY", choices: { A:"a puzzle", B:"a comparison", C:"a suggestion", D:"a story" }, answer:"B" },
  { number: 310, word: "ARBITRARY", choices: { A:"random", B:"senseless", C:"reckless", D:"inconsistent" }, answer:"A" },
  { number: 311, word: "ASCEND", choices: { A:"levitate", B:"overcome", C:"soar", D:"rise" }, answer:"D" },
  { number: 312, word: "AUSTERE", choices: { A:"traditional", B:"simple", C:"severe", D:"somber" }, answer:"C" },

  // B words (12 questions: 313-324)
  { number: 313, word: "BAFFLE", choices: { A:"confuse", B:"interrupt", C:"frustrate", D:"amuse" }, answer:"A" },
  { number: 314, word: "BELIE", choices: { A:"disguise", B:"contradict", C:"corrupt", D:"withhold" }, answer:"B" },
  { number: 315, word: "BENEVOLENT", choices: { A:"forgiving", B:"helpful", C:"kind", D:"tolerant" }, answer:"C" },
  { number: 316, word: "BESTOW", choices: { A:"lend", B:"share", C:"offer", D:"give" }, answer:"D" },
  { number: 317, word: "BREVITY", choices: { A:"briefness", B:"simplicity", C:"speed", D:"effectiveness" }, answer:"A" },
  { number: 318, word: "BRISK", choices: { A:"cold", B:"lively", C:"refreshing", D:"sudden" }, answer:"B" },
  { number: 319, word: "BRITTLE", choices: { A:"old", B:"fragile", C:"sharp", D:"stiff" }, answer:"B" },
  { number: 320, word: "BROOD", choices: { A:"ponder", B:"regret", C:"resent", D:"daydream" }, answer:"A" },
  { number: 321, word: "BRUSQUE", choices: { A:"rude", B:"informal", C:"abrupt", D:"hasty" }, answer:"C" },
  { number: 322, word: "BULWARK", choices: { A:"fortress", B:"barrier", C:"weapon", D:"defense" }, answer:"D" },
  { number: 323, word: "BUOYANT", choices: { A:"afloat", B:"successful", C:"cheerful", D:"weightless" }, answer:"C" },
  { number: 324, word: "BUTTRESS", choices: { A:"build", B:"defend", C:"support", D:"enclose" }, answer:"C" },

  // C words (18 questions: 325-342)
  { number: 325, word: "CANDOR", choices: { A:"confidence", B:"honesty", C:"courage", D:"certainty" }, answer:"B" },
  { number: 326, word: "CAPACIOUS", choices: { A:"hollow", B:"huge", C:"spacious", D:"tall" }, answer:"C" },
  { number: 327, word: "CEDE", choices: { A:"surrender", B:"sacrifice", C:"negotiate", D:"withdraw" }, answer:"A" },
  { number: 328, word: "CIRCUMVENT", choices: { A:"disrupt", B:"avoid", C:"cancel", D:"outwit" }, answer:"B" },
  { number: 329, word: "COERCE", choices: { A:"persuade", B:"threaten", C:"bribe", D:"force" }, answer:"D" },
  { number: 330, word: "COGNIZANT", choices: { A:"intelligent", B:"aware", C:"thoughtful", D:"wary" }, answer:"B" },
  { number: 331, word: "COHERENT", choices: { A:"fluent", B:"persuasive", C:"logical", D:"grammatical" }, answer:"C" },
  { number: 332, word: "COMMEMORATE", choices: { A:"celebrate", B:"remember", C:"honor", D:"broadcast" }, answer:"C" },
  { number: 333, word: "COMPELLING", choices: { A:"persuasive", B:"fascinating", C:"forceful", D:"dramatic" }, answer:"A" },
  { number: 334, word: "COMPENSATE", choices: { A:"repay", B:"reward", C:"fix", D:"subsidize" }, answer:"A" },
  { number: 335, word: "COMPLACENT", choices: { A:"lazy", B:"arrogant", C:"satisfied", D:"careless" }, answer:"C" },
  { number: 336, word: "COMPLY", choices: { A:"accept", B:"yield", C:"surrender", D:"obey" }, answer:"D" },
  { number: 337, word: "COMPOSURE", choices: { A:"patience", B:"dignity", C:"calmness", D:"peace" }, answer:"C" },
  { number: 338, word: "COMPREHENSIVE", choices: { A:"complete", B:"accurate", C:"enormous", D:"official" }, answer:"A" },
  { number: 339, word: "CONDEMN", choices: { A:"punish", B:"criticize", C:"blame", D:"forbid" }, answer:"B" },
  { number: 340, word: "CONDUCIVE", choices: { A:"helpful", B:"related", C:"necessary", D:"effective" }, answer:"A" },
  { number: 341, word: "CONSENSUS", choices: { A:"a decision", B:"a compromise", C:"agreement", D:"a majority" }, answer:"C" },
  { number: 342, word: "CONSTRAIN", choices: { A:"frustrate", B:"prevent", C:"restrict", D:"force" }, answer:"C" },

  // D words (18 questions: 343-360)
  { number: 343, word: "DAUNTING", choices: { A:"intimidating", B:"difficult", C:"stressful", D:"unpleasant" }, answer:"A" },
  { number: 344, word: "DEFT", choices: { A:"quick", B:"delicate", C:"skillful", D:"careful" }, answer:"C" },
  { number: 345, word: "DELEGATE", choices: { A:"choose", B:"assign", C:"promote", D:"instruct" }, answer:"B" },
  { number: 346, word: "DELINEATE", choices: { A:"design", B:"illustrate", C:"portray", D:"outline" }, answer:"D" },
  { number: 347, word: "DENOUNCE", choices: { A:"condemn", B:"expose", C:"accuse", D:"disprove" }, answer:"A" },
  { number: 348, word: "DEPLETE", choices: { A:"waste", B:"exhaust", C:"remove", D:"spoil" }, answer:"B" },
  { number: 349, word: "DERIDE", choices: { A:"offend", B:"mock", C:"dislike", D:"underestimate" }, answer:"B" },
  { number: 350, word: "DERIVE", choices: { A:"conclude", B:"obtain", C:"understand", D:"create" }, answer:"B" },
  { number: 351, word: "DETER", choices: { A:"warn", B:"prevent", C:"discourage", D:"frighten" }, answer:"C" },
  { number: 352, word: "DEVIATE", choices: { A:"rebel", B:"diverge", C:"modify", D:"contradict" }, answer:"B" },
  { number: 353, word: "DEVISE", choices: { A:"invent", B:"plan", C:"imagine", D:"discover" }, answer:"A" },
  { number: 354, word: "DILIGENT", choices: { A:"patient", B:"focused", C:"hardworking", D:"ambitious" }, answer:"C" },
  { number: 355, word: "DISCERN", choices: { A:"imagine", B:"consider", C:"guess", D:"perceive" }, answer:"D" },
  { number: 356, word: "DISCRETE", choices: { A:"hidden", B:"separate", C:"subtle", D:"minor" }, answer:"B" },
  { number: 357, word: "DISPARITY", choices: { A:"disadvantage", B:"conflict", C:"difference", D:"injustice" }, answer:"C" },
  { number: 358, word: "DISPERSE", choices: { A:"scatter", B:"evacuate", C:"flee", D:"dissolve" }, answer:"A" },
  { number: 359, word: "DISSENT", choices: { A:"protest", B:"disagreement", C:"rebellion", D:"conflict" }, answer:"B" },
  { number: 360, word: "DIVERGE", choices: { A:"separate", B:"curve", C:"recede", D:"transform" }, answer:"A" },

  // E words (18 questions: 361-378)
  { number: 361, word: "ECCENTRIC", choices: { A:"unconventional", B:"creative", C:"isolated", D:"foolish" }, answer:"A" },
  { number: 362, word: "EDIFY", choices: { A:"persuade", B:"entertain", C:"comfort", D:"educate" }, answer:"D" },
  { number: 363, word: "ELABORATE", choices: { A:"difficult", B:"detailed", C:"excessive", D:"ornate" }, answer:"B" },
  { number: 364, word: "ELICIT", choices: { A:"demand", B:"draw out", C:"request", D:"deduce" }, answer:"B" },
  { number: 365, word: "ELIGIBLE", choices: { A:"prepared", B:"considered", C:"qualified", D:"accepted" }, answer:"C" },
  { number: 366, word: "ELUCIDATE", choices: { A:"simplify", B:"explain", C:"reveal", D:"prove" }, answer:"B" },
  { number: 367, word: "EMANATE", choices: { A:"originate", B:"escape", C:"radiate", D:"transmit" }, answer:"A" },
  { number: 368, word: "EMANCIPATE", choices: { A:"defend", B:"justify", C:"pardon", D:"free" }, answer:"D" },
  { number: 369, word: "EMBARK", choices: { A:"begin", B:"travel", C:"prepare", D:"board" }, answer:"A" },
  { number: 370, word: "EMERGE", choices: { A:"erupt", B:"develop", C:"appear", D:"advance" }, answer:"C" },
  { number: 371, word: "EMINENT", choices: { A:"distinguished", B:"powerful", C:"wealthy", D:"arrogant" }, answer:"A" },
  { number: 372, word: "EMPHASIZE", choices: { A:"prioritize", B:"focus on", C:"exaggerate", D:"stress" }, answer:"D" },
  { number: 373, word: "EMPIRICAL", choices: { A:"theoretical", B:"logical", C:"experimental", D:"statistical" }, answer:"C" },
  { number: 374, word: "EMULATE", choices: { A:"imitate", B:"admire", C:"challenge", D:"envy" }, answer:"A" },
  { number: 375, word: "ENCOMPASS", choices: { A:"confine", B:"include", C:"border", D:"define" }, answer:"B" },
  { number: 376, word: "ENDORSE", choices: { A:"authorize", B:"publicize", C:"recommend", D:"support" }, answer:"D" },
  { number: 377, word: "ENHANCE", choices: { A:"improve", B:"intensify", C:"decorate", D:"strengthen" }, answer:"A" },
  { number: 378, word: "ENLIGHTEN", choices: { A:"advise", B:"persuade", C:"inform", D:"reveal" }, answer:"C" },

  // F words (18 questions: 379-396)
  { number: 379, word: "FACILITATE", choices: { A:"approve", B:"assist", C:"generate", D:"supervise" }, answer:"B" },
  { number: 380, word: "FACILE", choices: { A:"effortless", B:"shallow", C:"easy", D:"obvious" }, answer:"C" },
  { number: 381, word: "FALLOW", choices: { A:"dry", B:"abandoned", C:"barren", D:"unused" }, answer:"D" },
  { number: 382, word: "FEASIBLE", choices: { A:"possible", B:"reasonable", C:"desirable", D:"affordable" }, answer:"A" },
  { number: 383, word: "FEIGN", choices: { A:"deceive", B:"imitate", C:"pretend", D:"imagine" }, answer:"C" },
  { number: 384, word: "FINITE", choices: { A:"temporary", B:"measurable", C:"incomplete", D:"limited" }, answer:"D" },
  { number: 385, word: "FLAGRANT", choices: { A:"harmful", B:"offensive", C:"blatant", D:"unlawful" }, answer:"C" },
  { number: 386, word: "FLAW", choices: { A:"complaint", B:"error", C:"defect", D:"crack" }, answer:"C" },
  { number: 387, word: "FLUCTUATE", choices: { A:"hesitate", B:"vary", C:"alternate", D:"vibrate" }, answer:"B" },
  { number: 388, word: "FLUENT", choices: { A:"natural", B:"eloquent", C:"smooth", D:"persuasive" }, answer:"C" },
  { number: 389, word: "FOIBLE", choices: { A:"weakness", B:"bad habit", C:"mistake", D:"secret" }, answer:"A" },
  { number: 390, word: "FORBEAR", choices: { A:"refrain", B:"resist", C:"postpone", D:"hesitate" }, answer:"A" },
  { number: 391, word: "FORESTALL", choices: { A:"warn", B:"delay", C:"prevent", D:"defeat" }, answer:"C" },
  { number: 392, word: "FORGE", choices: { A:"imitate", B:"create", C:"design", D:"assemble" }, answer:"B" },
  { number: 393, word: "FORSAKE", choices: { A:"betray", B:"neglect", C:"abandon", D:"disown" }, answer:"C" },
  { number: 394, word: "FORTIFY", choices: { A:"strengthen", B:"prepare", C:"defend", D:"enclose" }, answer:"A" },
  { number: 395, word: "FOSTER", choices: { A:"advise", B:"adopt", C:"shelter", D:"encourage" }, answer:"D" },
  { number: 396, word: "FRAUGHT", choices: { A:"filled", B:"risky", C:"complicated", D:"upsetting" }, answer:"A" },

  // G words (12 questions: 397-408)
  { number: 397, word: "GARNER", choices: { A:"gather", B:"achieve", C:"deserve", D:"request" }, answer:"A" },
  { number: 398, word: "GAUNT", choices: { A:"thin", B:"pale", C:"aged", D:"exhausted" }, answer:"A" },
  { number: 399, word: "GENERIC", choices: { A:"simple", B:"inferior", C:"standard", D:"general" }, answer:"D" },
  { number: 400, word: "GENIAL", choices: { A:"respectful", B:"sincere", C:"friendly", D:"patient" }, answer:"C" },
  { number: 401, word: "GESTURE", choices: { A:"reaction", B:"custom", C:"signal", D:"habit" }, answer:"C" },
  { number: 402, word: "GHASTLY", choices: { A:"frightening", B:"violent", C:"horrible", D:"grotesque" }, answer:"C" },
  { number: 403, word: "GIST", choices: { A:"an opinion", B:"a summary", C:"essence", D:"a conclusion" }, answer:"C" },
  { number: 404, word: "GLEAN", choices: { A:"discover", B:"examine", C:"deduce", D:"gather" }, answer:"D" },
  { number: 405, word: "GLIB", choices: { A:"deceptive", B:"clever", C:"smooth", D:"persuasive" }, answer:"C" },
  { number: 406, word: "GRACIOUS", choices: { A:"courteous", B:"welcoming", C:"formal", D:"forgiving" }, answer:"A" },
  { number: 407, word: "GRADUAL", choices: { A:"subtle", B:"unhurried", C:"slight", D:"slow" }, answer:"D" },
  { number: 408, word: "GRATIFY", choices: { A:"reward", B:"please", C:"appreciate", D:"approve" }, answer:"B" },

  // H words (12 questions: 409-420)
  { number: 409, word: "HACKNEYED", choices: { A:"silly", B:"predictable", C:"overused", D:"outdated" }, answer:"C" },
  { number: 410, word: "HAMPER", choices: { A:"hinder", B:"entangle", C:"weaken", D:"damage" }, answer:"A" },
  { number: 411, word: "HARMONIOUS", choices: { A:"melodic", B:"balanced", C:"agreeable", D:"cooperative" }, answer:"C" },
  { number: 412, word: "HASTEN", choices: { A:"chase", B:"urge", C:"propel", D:"hurry" }, answer:"D" },
  { number: 413, word: "HAUGHTY", choices: { A:"strict", B:"boastful", C:"bossy", D:"arrogant" }, answer:"D" },
  { number: 414, word: "HAVOC", choices: { A:"chaos", B:"fear", C:"panic", D:"anarchy" }, answer:"A" },
  { number: 415, word: "HEED", choices: { A:"obey", B:"acknowledge", C:"notice", D:"consider" }, answer:"C" },
  { number: 416, word: "HEINOUS", choices: { A:"evil", B:"unforgivable", C:"violent", D:"depraved" }, answer:"A" },
  { number: 417, word: "HERALD", choices: { A:"deliver", B:"present", C:"signal", D:"forecast" }, answer:"C" },
  { number: 418, word: "HERMIT", choices: { A:"misfit", B:"exile", C:"recluse", D:"monk" }, answer:"C" },
  { number: 419, word: "HINDER", choices: { A:"complicate", B:"obstruct", C:"sabotage", D:"postpone" }, answer:"B" },
  { number: 420, word: "HUMBLE", choices: { A:"modest", B:"insignificant", C:"ashamed", D:"apologetic" }, answer:"A" },

  // I words (12 questions: 421-432)
  { number: 421, word: "IDEOLOGY", choices: { A:"culture", B:"agenda", C:"belief system", D:"constitution" }, answer:"C" },
  { number: 422, word: "IGNITE", choices: { A:"agitate", B:"light", C:"trigger", D:"launch" }, answer:"B" },
  { number: 423, word: "ILLICIT", choices: { A:"illegal", B:"secretive", C:"immoral", D:"harmful" }, answer:"A" },
  { number: 424, word: "ILLUMINATE", choices: { A:"light up", B:"feature", C:"expose", D:"decorate" }, answer:"A" },
  { number: 425, word: "IMMACULATE", choices: { A:"holy", B:"perfect", C:"brand new", D:"ideal" }, answer:"B" },
  { number: 426, word: "IMMERSE", choices: { A:"drown", B:"moisten", C:"submerge", D:"saturate" }, answer:"C" },
  { number: 427, word: "IMMINENT", choices: { A:"unsettling", B:"dangerous", C:"guaranteed", D:"impending" }, answer:"D" },
  { number: 428, word: "IMPAIR", choices: { A:"damage", B:"frustrate", C:"disrupt", D:"annoy" }, answer:"A" },
  { number: 429, word: "IMPECCABLE", choices: { A:"precise", B:"professional", C:"flawless", D:"admirable" }, answer:"C" },
  { number: 430, word: "IMPEDE", choices: { A:"ruin", B:"challenge", C:"hinder", D:"complicate" }, answer:"C" },
  { number: 431, word: "IMPERATIVE", choices: { A:"essential", B:"official", C:"immediate", D:"forceful" }, answer:"A" },
  { number: 432, word: "IMPERVIOUS", choices: { A:"durable", B:"unbreakable", C:"impenetrable", D:"resistant" }, answer:"D" },

  // J words (6 questions: 433-438)
  { number: 433, word: "JEOPARDIZE", choices: { A:"endanger", B:"worsen", C:"compromise", D:"ruin" }, answer:"A" },
  { number: 434, word: "JUBILANT", choices: { A:"celebratory", B:"relieved", C:"joyful", D:"ecstatic" }, answer:"C" },
  { number: 435, word: "JUDICIOUS", choices: { A:"wise", B:"cautious", C:"legal", D:"official" }, answer:"A" },
  { number: 436, word: "JUNCTION", choices: { A:"boundary", B:"intersection", C:"union", D:"merger" }, answer:"B" },
  { number: 437, word: "JUSTIFY", choices: { A:"clarify", B:"advocate", C:"confirm", D:"defend" }, answer:"D" },
  { number: 438, word: "JUXTAPOSE", choices: { A:"analyze", B:"place side by side", C:"rearrange", D:"combine" }, answer:"B" },

  // K words (4 questions: 439-442)
  { number: 439, word: "KINDLE", choices: { A:"generate", B:"grasp", C:"encourage", D:"ignite" }, answer:"D" },
  { number: 440, word: "KNACK", choices: { A:"talent", B:"preference", C:"quirk", D:"specialty" }, answer:"A" },
  { number: 441, word: "KNOLL", choices: { A:"clearing", B:"ridge", C:"hill", D:"meadow" }, answer:"C" },
  { number: 442, word: "KUDOS", choices: { A:"reward", B:"praise", C:"gratitude", D:"acknowledgement" }, answer:"B" },

  // L words (12 questions: 443-454)
  { number: 443, word: "LABORIOUS", choices: { A:"strenuous", B:"lengthy", C:"repetitive", D:"difficult" }, answer:"D" },
  { number: 444, word: "LAMPOON", choices: { A:"caricature", B:"belittle", C:"expose", D:"satirize" }, answer:"D" },
  { number: 445, word: "LANGUID", choices: { A:"sluggish", B:"droopy", C:"indifferent", D:"lethargic" }, answer:"A" },
  { number: 446, word: "LATENT", choices: { A:"old", B:"forgotten", C:"hidden", D:"undeveloped" }, answer:"C" },
  { number: 447, word: "LAUDABLE", choices: { A:"effective", B:"beneficial", C:"praiseworthy", D:"virtuous" }, answer:"C" },
  { number: 448, word: "LAVISH", choices: { A:"extravagant", B:"ornate", C:"wasteful", D:"excessive" }, answer:"A" },
  { number: 449, word: "LEGACY", choices: { A:"legend", B:"history", C:"inheritance", D:"estate" }, answer:"C" },
  { number: 450, word: "LEGITIMATE", choices: { A:"reasonable", B:"sincere", C:"authentic", D:"legal" }, answer:"D" },
  { number: 451, word: "LETHARGY", choices: { A:"depression", B:"sluggishness", C:"exhaustion", D:"illness" }, answer:"B" },
  { number: 452, word: "LEVITY", choices: { A:"playfulness", B:"amusement", C:"joy", D:"humor" }, answer:"D" },
  { number: 453, word: "LUCID", choices: { A:"logical", B:"clear", C:"brilliant", D:"vivid" }, answer:"B" },
  { number: 454, word: "LUMINOUS", choices: { A:"bright", B:"vivid", C:"dazzling", D:"glowing" }, answer:"A" },

  // M words (12 questions: 455-466)
  { number: 455, word: "MAGNANIMOUS", choices: { A:"merciful", B:"humble", C:"generous", D:"formal" }, answer:"C" },
  { number: 456, word: "MAGNITUDE", choices: { A:"weight", B:"difficulty", C:"severity", D:"size" }, answer:"D" },
  { number: 457, word: "MALICIOUS", choices: { A:"destructive", B:"spiteful", C:"deceitful", D:"violent" }, answer:"B" },
  { number: 458, word: "MANDATE", choices: { A:"law", B:"command", C:"expectation", D:"suggestion" }, answer:"B" },
  { number: 459, word: "MANIFEST", choices: { A:"proven", B:"unmistakable", C:"evident", D:"obvious" }, answer:"D" },
  { number: 460, word: "MEAGER", choices: { A:"miserable", B:"trivial", C:"unhealthy", D:"scanty" }, answer:"D" },
  { number: 461, word: "MELLOW", choices: { A:"ripe", B:"gentle", C:"sweet", D:"relaxed" }, answer:"B" },
  { number: 462, word: "MENACE", choices: { A:"bully", B:"nuisance", C:"threat", D:"criminal" }, answer:"C" },
  { number: 463, word: "MENTOR", choices: { A:"guide", B:"patron", C:"professional", D:"sponsor" }, answer:"A" },
  { number: 464, word: "METICULOUS", choices: { A:"diligent", B:"obsessive", C:"thorough", D:"methodical" }, answer:"C" },
  { number: 465, word: "MIRTH", choices: { A:"pleasure", B:"excitement", C:"merriment", D:"celebration" }, answer:"C" },
  { number: 466, word: "MITIGATE", choices: { A:"lessen", B:"resolve", C:"soothe", D:"delay" }, answer:"A" },

  // N words (10 questions: 467-476)
  { number: 467, word: "NASCENT", choices: { A:"experimental", B:"minor", C:"emerging", D:"fragile" }, answer:"C" },
  { number: 468, word: "NEGLIGIBLE", choices: { A:"irrelevant", B:"insignificant", C:"overlooked", D:"ignored" }, answer:"B" },
  { number: 469, word: "NIMBLE", choices: { A:"graceful", B:"lively", C:"swift", D:"agile" }, answer:"D" },
  { number: 470, word: "NOMINAL", choices: { A:"token", B:"approximate", C:"official", D:"suggested" }, answer:"A" },
  { number: 471, word: "NONCHALANT", choices: { A:"casual", B:"distracted", C:"uninterested", D:"aloof" }, answer:"A" },
  { number: 472, word: "NURTURE", choices: { A:"influence", B:"care for", C:"train", D:"instruct" }, answer:"B" },
  { number: 473, word: "NOMADIC", choices: { A:"solitary", B:"inquisitive", C:"primitive", D:"wandering" }, answer:"D" },
  { number: 474, word: "NULLIFY", choices: { A:"contradict", B:"erase", C:"cancel", D:"disprove" }, answer:"C" },
  { number: 475, word: "NOTABLE", choices: { A:"obvious", B:"remarkable", C:"celebrated", D:"unique" }, answer:"B" },
  { number: 476, word: "NOTION", choices: { A:"hunch", B:"memory", C:"theory", D:"idea" }, answer:"D" },

  // O words (10 questions: 477-486)
  { number: 477, word: "OBLIGE", choices: { A:"serve", B:"assist", C:"require", D:"persuade" }, answer:"C" },
  { number: 478, word: "OBLITERATE", choices: { A:"destroy", B:"spoil", C:"overwhelm", D:"defeat" }, answer:"A" },
  { number: 479, word: "OBLIVIOUS", choices: { A:"daydreaming", B:"confused", C:"inattentive", D:"unaware" }, answer:"D" },
  { number: 480, word: "OBSCURE", choices: { A:"complex", B:"abstract", C:"unclear", D:"mysterious" }, answer:"C" },
  { number: 481, word: "OBSTRUCT", choices: { A:"interfere with", B:"disrupt", C:"delay", D:"block" }, answer:"D" },
  { number: 482, word: "OMINOUS", choices: { A:"gloomy", B:"unpleasant", C:"threatening", D:"mysterious" }, answer:"C" },
  { number: 483, word: "OPPRESS", choices: { A:"control", B:"persecute", C:"harass", D:"intimidate" }, answer:"B" },
  { number: 484, word: "OPTIMUM", choices: { A:"ideal", B:"best", C:"flawless", D:"supreme" }, answer:"B" },
  { number: 485, word: "OPULENT", choices: { A:"valuable", B:"pretentious", C:"luxurious", D:"ostentatious" }, answer:"C" },
  { number: 486, word: "OVERT", choices: { A:"public", B:"unashamed", C:"deliberate", D:"obvious" }, answer:"D" },

  // P words (18 questions: 487-504)
  { number: 487, word: "PACIFY", choices: { A:"comfort", B:"distract", C:"calm", D:"appease" }, answer:"C" },
  { number: 488, word: "PALPABLE", choices: { A:"intense", B:"obvious", C:"unmistakable", D:"tangible" }, answer:"D" },
  { number: 489, word: "PARAMOUNT", choices: { A:"fundamental", B:"urgent", C:"supreme", D:"dominant" }, answer:"C" },
  { number: 490, word: "PARDON", choices: { A:"absolve", B:"liberate", C:"acquit", D:"forgive" }, answer:"D" },
  { number: 491, word: "PARODY", choices: { A:"farce", B:"satire", C:"comedy", D:"performance" }, answer:"B" },
  { number: 492, word: "PARTIAL", choices: { A:"opinionated", B:"incomplete", C:"unfair", D:"subjective" }, answer:"B" },
  { number: 493, word: "PARTITION", choices: { A:"divide", B:"obstacle", C:"border", D:"segment" }, answer:"A" },
  { number: 494, word: "PATENT", choices: { A:"blatant", B:"guaranteed", C:"certain", D:"obvious" }, answer:"D" },
  { number: 495, word: "PAUCITY", choices: { A:"poverty", B:"absence", C:"deficiency", D:"shortage" }, answer:"D" },
  { number: 496, word: "PECULIAR", choices: { A:"memorable", B:"specific", C:"unfamiliar", D:"strange" }, answer:"D" },
  { number: 497, word: "PENSIVE", choices: { A:"philosophical", B:"preoccupied", C:"thoughtful", D:"melancholy" }, answer:"C" },
  { number: 498, word: "PERENNIAL", choices: { A:"cyclical", B:"enduring", C:"long-lived", D:"predictable" }, answer:"B" },
  { number: 499, word: "PERIL", choices: { A:"adversity", B:"vulnerability", C:"uncertainty", D:"danger" }, answer:"D" },
  { number: 500, word: "PERIPHERAL", choices: { A:"superficial", B:"irrelevant", C:"outer", D:"adjacent" }, answer:"C" },
  { number: 501, word: "PERPETUAL", choices: { A:"continuous", B:"recurrent", C:"boring", D:"relentless" }, answer:"A" },
  { number: 502, word: "PERSIST", choices: { A:"repeat", B:"resist", C:"endure", D:"continue" }, answer:"D" },
  { number: 503, word: "PERTURB", choices: { A:"disturb", B:"confuse", C:"frighten", D:"inconvenience" }, answer:"A" },
  { number: 504, word: "PIVOTAL", choices: { A:"difficult", B:"transformative", C:"crucial", D:"complex" }, answer:"C" },

  // Q words (6 questions: 505-510)
  { number: 505, word: "QUAINT", choices: { A:"delightful", B:"humble", C:"charming", D:"antique" }, answer:"C" },
  { number: 506, word: "QUALIFY", choices: { A:"define", B:"clarify", C:"limit", D:"elaborate" }, answer:"C" },
  { number: 507, word: "QUALM", choices: { A:"anxiety", B:"objection", C:"suspicion", D:"doubt" }, answer:"D" },
  { number: 508, word: "QUELL", choices: { A:"silence", B:"tame", C:"conquer", D:"suppress" }, answer:"D" },
  { number: 509, word: "QUEST", choices: { A:"search", B:"expedition", C:"pilgrimage", D:"challenge" }, answer:"A" },
  { number: 510, word: "QUIBBLE", choices: { A:"gossip", B:"protest", C:"argue", D:"hesitate" }, answer:"C" },

  // R words (12 questions: 511-522)
  { number: 511, word: "RAMBLE", choices: { A:"hike", B:"digress", C:"stroll", D:"wander" }, answer:"D" },
  { number: 512, word: "RANCOR", choices: { A:"hostility", B:"bitterness", C:"disgust", D:"jealousy" }, answer:"B" },
  { number: 513, word: "RATIFY", choices: { A:"endorse", B:"enact", C:"authorize", D:"approve" }, answer:"D" },
  { number: 514, word: "REBUKE", choices: { A:"threaten", B:"insult", C:"admonish", D:"reprimand" }, answer:"D" },
  { number: 515, word: "RECANT", choices: { A:"deny", B:"amend", C:"retract", D:"apologize" }, answer:"C" },
  { number: 516, word: "RECEPTIVE", choices: { A:"open", B:"agreeable", C:"curious", D:"attentive" }, answer:"A" },
  { number: 517, word: "RECLUSE", choices: { A:"troglodyte", B:"coward", C:"hermit", D:"misfit" }, answer:"C" },
  { number: 518, word: "RECONCILE", choices: { A:"apologize to", B:"mediate", C:"settle", D:"reunite" }, answer:"C" },
  { number: 519, word: "REFUTE", choices: { A:"counter", B:"debate", C:"challenge", D:"disprove" }, answer:"D" },
  { number: 520, word: "RELENTLESS", choices: { A:"merciless", B:"persistent", C:"determined", D:"brutal" }, answer:"B" },
  { number: 521, word: "RENOUNCE", choices: { A:"betray", B:"protest", C:"reject", D:"denounce" }, answer:"C" },
  { number: 522, word: "REPUDIATE", choices: { A:"challenge", B:"disobey", C:"contradict", D:"reject" }, answer:"D" },

  // S words (18 questions: 523-540)
  { number: 523, word: "SABOTAGE", choices: { A:"destroy", B:"undermine", C:"frustrate", D:"complicate" }, answer:"B" },
  { number: 524, word: "SAGE", choices: { A:"spiritual", B:"calm", C:"ancient", D:"wise" }, answer:"D" },
  { number: 525, word: "SALIENT", choices: { A:"critical", B:"relevant", C:"prominent", D:"apparent" }, answer:"C" },
  { number: 526, word: "SALVAGE", choices: { A:"save", B:"seize", C:"collect", D:"restore" }, answer:"A" },
  { number: 527, word: "SANCTION", choices: { A:"subsidize", B:"approve", C:"reward", D:"permit" }, answer:"B" },
  { number: 528, word: "SATURATE", choices: { A:"overflow", B:"submerge", C:"contaminate", D:"soak" }, answer:"D" },
  { number: 529, word: "SCANTY", choices: { A:"trivial", B:"meager", C:"flimsy", D:"inadequate" }, answer:"B" },
  { number: 530, word: "SCRUTINIZE", choices: { A:"examine", B:"judge", C:"scan", D:"question" }, answer:"A" },
  { number: 531, word: "SECLUDE", choices: { A:"imprison", B:"isolate", C:"conceal", D:"quarantine" }, answer:"B" },
  { number: 532, word: "SEDATE", choices: { A:"dignified", B:"somber", C:"calm", D:"leisurely" }, answer:"C" },
  { number: 533, word: "SEQUEL", choices: { A:"aftermath", B:"repetition", C:"epilogue", D:"continuation" }, answer:"D" },
  { number: 534, word: "SHREWD", choices: { A:"astute", B:"ambitious", C:"cynical", D:"calculating" }, answer:"A" },
  { number: 535, word: "SIMULTANEOUS", choices: { A:"instantaneous", B:"coordinated", C:"identical", D:"concurrent" }, answer:"D" },
  { number: 536, word: "SINGULAR", choices: { A:"unfamiliar", B:"superior", C:"solitary", D:"unique" }, answer:"D" },
  { number: 537, word: "SKEPTICAL", choices: { A:"cautious", B:"doubtful", C:"pessimistic", D:"cynical" }, answer:"B" },
  { number: 538, word: "SLUGGISH", choices: { A:"boring", B:"slow", C:"feeble", D:"exhausted" }, answer:"B" },
  { number: 539, word: "SOMBER", choices: { A:"dull", B:"formal", C:"mournful", D:"serious" }, answer:"D" },
  { number: 540, word: "SPORADIC", choices: { A:"irregular", B:"uncommon", C:"accidental", D:"rare" }, answer:"A" },

  // T words (12 questions: 541-552)
  { number: 541, word: "TACITURN", choices: { A:"introspective", B:"quiet", C:"antisocial", D:"melancholy" }, answer:"B" },
  { number: 542, word: "TANGIBLE", choices: { A:"visible", B:"durable", C:"valuable", D:"real" }, answer:"D" },
  { number: 543, word: "TARNISH", choices: { A:"damage", B:"weaken", C:"disgrace", D:"discolor" }, answer:"A" },
  { number: 544, word: "TAUT", choices: { A:"inflexible", B:"tight", C:"strained", D:"stiff" }, answer:"B" },
  { number: 545, word: "TEEM", choices: { A:"drizzle", B:"overflow", C:"congregate", D:"swarm" }, answer:"D" },
  { number: 546, word: "TEMPER", choices: { A:"moderate", B:"adjust", C:"influence", D:"weaken" }, answer:"A" },
  { number: 547, word: "TENUOUS", choices: { A:"unlikely", B:"dubious", C:"insubstantial", D:"weak" }, answer:"D" },
  { number: 548, word: "TERMINATE", choices: { A:"end", B:"interrupt", C:"dismiss", D:"postpone" }, answer:"A" },
  { number: 549, word: "THWART", choices: { A:"distract", B:"outwit", C:"prevent", D:"sabotage" }, answer:"C" },
  { number: 550, word: "TIMOROUS", choices: { A:"overwhelmed", B:"cautious", C:"fearful", D:"hesitant" }, answer:"C" },
  { number: 551, word: "TOIL", choices: { A:"suffer", B:"endure", C:"persevere", D:"work hard" }, answer:"D" },
  { number: 552, word: "TURBULENT", choices: { A:"frightening", B:"unpredictable", C:"chaotic", D:"dangerous" }, answer:"C" },

  // U words (8 questions: 553-560)
  { number: 553, word: "UBIQUITOUS", choices: { A:"fashionable", B:"inescapable", C:"pervasive", D:"everywhere" }, answer:"D" },
  { number: 554, word: "ULTIMATE", choices: { A:"definitive", B:"final", C:"supreme", D:"concluding" }, answer:"B" },
  { number: 555, word: "UNASSUMING", choices: { A:"modest", B:"insecure", C:"reserved", D:"timid" }, answer:"A" },
  { number: 556, word: "UNCANNY", choices: { A:"remarkable", B:"coincidental", C:"strange", D:"supernatural" }, answer:"C" },
  { number: 557, word: "UNDERMINE", choices: { A:"corrupt", B:"discredit", C:"weaken", D:"attack" }, answer:"C" },
  { number: 558, word: "UNIFORM", choices: { A:"rigid", B:"consistent", C:"orderly", D:"level" }, answer:"B" },
  { number: 559, word: "UNPRECEDENTED", choices: { A:"miraculous", B:"groundbreaking", C:"extraordinary", D:"unparalleled" }, answer:"D" },
  { number: 560, word: "UPHOLD", choices: { A:"advocate", B:"justify", C:"support", D:"defend" }, answer:"C" },

  // V words (12 questions: 561-572)
  { number: 561, word: "VALID", choices: { A:"convincing", B:"sound", C:"factual", D:"logical" }, answer:"B" },
  { number: 562, word: "VALOR", choices: { A:"gallantry", B:"fortitude", C:"determination", D:"bravery" }, answer:"D" },
  { number: 563, word: "VANQUISH", choices: { A:"exile", B:"humiliate", C:"defeat", D:"eliminate" }, answer:"C" },
  { number: 564, word: "VENERATE", choices: { A:"revere", B:"cherish", C:"idolize", D:"obey" }, answer:"A" },
  { number: 565, word: "VERBOSE", choices: { A:"boring", B:"pompous", C:"descriptive", D:"wordy" }, answer:"D" },
  { number: 566, word: "VERSATILE", choices: { A:"adaptable", B:"ingenious", C:"gifted", D:"accomplished" }, answer:"A" },
  { number: 567, word: "VETO", choices: { A:"invalidate", B:"reverse", C:"overrule", D:"reject" }, answer:"D" },
  { number: 568, word: "VIABLE", choices: { A:"effective", B:"profitable", C:"promising", D:"feasible" }, answer:"D" },
  { number: 569, word: "VICIOUS", choices: { A:"malicious", B:"aggressive", C:"cruel", D:"sadistic" }, answer:"C" },
  { number: 570, word: "VINDICATE", choices: { A:"defend", B:"clear", C:"avenge", D:"absolve" }, answer:"B" },
  { number: 571, word: "VIRTUAL", choices: { A:"theoretical", B:"unofficial", C:"potential", D:"nearly" }, answer:"D" },
  { number: 572, word: "VIRULENT", choices: { A:"destructive", B:"malevolent", C:"poisonous", D:"infectious" }, answer:"C" },

  // W words (8 questions: 573-580)
  { number: 573, word: "WAIVE", choices: { A:"forfeit", B:"relinquish", C:"postpone", D:"cancel" }, answer:"B" },
  { number: 574, word: "WANE", choices: { A:"decrease", B:"falter", C:"subside", D:"recede" }, answer:"A" },
  { number: 575, word: "WARY", choices: { A:"skeptical", B:"cautious", C:"vigilant", D:"paranoid" }, answer:"B" },
  { number: 576, word: "WHOLESOME", choices: { A:"healthy", B:"decent", C:"pure", D:"moral" }, answer:"A" },
  { number: 577, word: "WIELD", choices: { A:"employ", B:"manipulate", C:"hold", D:"brandish" }, answer:"C" },
  { number: 578, word: "WILLFUL", choices: { A:"childish", B:"malicious", C:"obstinate", D:"deliberate" }, answer:"D" },
  { number: 579, word: "WITHER", choices: { A:"atrophy", B:"shrivel", C:"disintegrate", D:"spoil" }, answer:"B" },
  { number: 580, word: "WRATH", choices: { A:"violence", B:"vengeance", C:"hatred", D:"anger" }, answer:"D" },

  // X, Y, Z words (4 questions: 581-584)
  { number: 581, word: "XENOPHOBIA", choices: { A:"nationalism", B:"ignorance", C:"hostility", D:"fear of foreigners" }, answer:"D" },
  { number: 582, word: "YEARN", choices: { A:"long for", B:"envy", C:"reminisce", D:"anticipate" }, answer:"A" },
  { number: 583, word: "YIELD", choices: { A:"sacrifice", B:"result in", C:"concede", D:"produce" }, answer:"D" },
  { number: 584, word: "ZENITH", choices: { A:"objective", B:"peak", C:"destination", D:"completion" }, answer:"B" },
  
  // Padding questions 585-600 to reach exactly 300
  { number: 585, word: "ACCLAIM", choices: { A:"popularity", B:"praise", C:"reputation", D:"acknowledgment" }, answer:"B" },
  { number: 586, word: "BENEVOLENT", choices: { A:"humble", B:"tolerant", C:"thoughtful", D:"kind" }, answer:"D" },
  { number: 587, word: "COHERENT", choices: { A:"comprehensive", B:"eloquent", C:"logical", D:"well-written" }, answer:"C" },
  { number: 588, word: "DAUNTING", choices: { A:"unpleasant", B:"stressful", C:"tiresome", D:"intimidating" }, answer:"D" },
  { number: 589, word: "ENHANCE", choices: { A:"decorate", B:"improve", C:"expand", D:"exaggerate" }, answer:"B" },
  { number: 590, word: "FACILITATE", choices: { A:"approve", B:"monitor", C:"expedite", D:"assist" }, answer:"D" },
  { number: 591, word: "GARNER", choices: { A:"accept", B:"claim", C:"gather", D:"absorb" }, answer:"C" },
  { number: 592, word: "HAMPER", choices: { A:"spoil", B:"weaken", C:"hinder", D:"disrupt" }, answer:"C" },
  { number: 593, word: "IMMINENT", choices: { A:"impending", B:"sudden", C:"possible", D:"inevitable" }, answer:"A" },
  { number: 594, word: "JUDICIOUS", choices: { A:"objective", B:"wise", C:"lawful", D:"impartial" }, answer:"B" },
  { number: 595, word: "KINDLE", choices: { A:"provoke", B:"nurture", C:"ignite", D:"influence" }, answer:"C" },
  { number: 596, word: "LAVISH", choices: { A:"wasteful", B:"pretentious", C:"generous", D:"extravagant" }, answer:"D" },
  { number: 597, word: "MAGNANIMOUS", choices: { A:"impressive", B:"dignified", C:"generous", D:"noble" }, answer:"C" },
  { number: 598, word: "NASCENT", choices: { A:"emerging", B:"immature", C:"unproven", D:"temporary" }, answer:"A" },
  { number: 599, word: "OPULENT", choices: { A:"expensive", B:"elegant", C:"ostentatious", D:"luxurious" }, answer:"D" },
  { number: 600, word: "PIVOTAL", choices: { A:"preliminary", B:"crucial", C:"unexpected", D:"complicated" }, answer:"B" },
];

// Optional sentinel
window.__VOCAB_ENHANCED1_LOADED__ = true;

