// isee_vocab_data.js
// IMPORTANT: define globals on `window` so the app can see them.
// Do NOT use type="module" on the script tag that loads this file.

window.DEFINITIONS = {
  // Paste ALL entries from your current DEFINITIONS here (verbatim) …
  // Example few (from your file):
  
  ABRIDGED: "compressed, reduced, shortened — Example: The student read the abridged version of Moby Dick for his book report.",
  ABRUPT: "sudden, blunt, rude — Example: The meeting came to an abrupt end when the fire alarm sounded.",
  ABSOLUTE: "complete, full, entire — Example: The coach had absolute confidence in her team’s preparation.",
  ABUNDANT: "ample, plenty, enough — Example: Wildflowers were abundant along the hillside trail after the spring rains.",
  ACCENTUATE: "emphasize, highlight, focus on — Example: A dash of lemon will accentuate the flavor of the soup.",
  ADAGE: "proverb, saying, motto — Example: The old adage about practice rang true as her skills improved.",
  ADAMANT: "determined, unyielding, firm — Example: He was adamant that the deadline would not be extended.",
  ADEPT: "capable, proficient, skilled — Example: The pianist is adept at improvising during live shows.",
  ADMONISH: "reprimand, scold, criticize — Example: The teacher had to admonish the class for talking during the quiz.",
  ADORN: "embellish, enhance, garnish — Example: Paper lanterns adorn the courtyard during the festival.",
  ADVERSARY: "enemy, attacker, rival — Example: The chess champion studied every move of her toughest adversary.",
  AFFLUENT: "rich, prosperous, well-off — Example: The affluent neighborhood funded a new community theater.",
  AFFRONT: "insult, criticize, offend — Example: He took the comment as an affront to his integrity.",
  AGHAST: "very surprised, appalled, shocked — Example: We were aghast at the damage the storm left behind.",
  AGILE: "athletic, energetic, lively — Example: The agile cat leapt from the fence to the balcony with ease.",
  AILMENT: "illness, disease, sickness — Example: A simple ailment kept him home from school for two days.",
  ALLEVIATE: "relieve, lessen, ease — Example: A short walk can alleviate stress during a long workday.",
  ALOOF: "standoffish, detached, haughty — Example: He seemed aloof at first, but soon warmed up to the group.",
  AMBIGUOUS: "unclear, vague, obscure — Example: The instructions were ambiguous and caused several mistakes.",
  AMBIVALENCE: "doubt, hesitation, uncertainty — Example: Her ambivalence about the offer made the decision difficult.",
  AMIABLE: "friendly, pleasant, agreeable — Example: The receptionist’s amiable greeting set a welcoming tone.",
  AMPLE: "abundant, plentiful, sufficient — Example: There was ample seating for everyone at the ceremony.",
  ANECDOTE: "story, tale, account — Example: He opened his speech with a brief anecdote from his childhood.",
  ANIMOSITY: "extreme dislike, hatred, hostility — Example: Years of rivalry had fostered animosity between the teams.",
  ANOMALOUS: "unusual, atypical, unnatural — Example: Scientists investigated the anomalous reading from the sensor.",
  ANTAGONIST: "enemy, opponent, competitor — Example: The novel’s antagonist plotted quietly in the shadows.",
  APPEASE: "satisfy, pacify, calm — Example: A sincere apology can appease even a frustrated customer.",
  ARDUOUS: "difficult, hard to endure, exhausting — Example: The hikers completed the arduous climb before sunset.",
  ARID: "dry, parched, moistureless — Example: The arid landscape stretched for miles without a single tree.",
  ASPIRE: "aim, hope, strive — Example: She aspires to become a marine biologist one day.",
  BARREN: "desolate, empty, unproductive — Example: The once fertile field had become barren after the drought.",
  BIAS: "favoritism, partiality, preference — Example: The committee worked to reduce bias during the selection process.",
  BIZARRE: "strange, wild, unusual — Example: The sculpture looked bizarre yet strangely beautiful at dusk.",
  BLATANT: "shameless, conspicuous, obvious — Example: It was a blatant foul, and the referee had to call it.",
  BLISS: "gladness, joy, euphoria — Example: They spent a week of pure bliss on the quiet island.",
  BOISTEROUS: "noisy, rowdy, raucous — Example: The boisterous crowd cheered as the band took the stage.",
  BOYCOTT: "avoid, ban, exclude — Example: Several customers decided to boycott the brand after the scandal.",
  BRAZEN: "bold, impudent, insolent — Example: It was a brazen attempt to take credit for the team’s work.",
  CALAMITY: "disaster, tragedy, mishap — Example: The flood was a calamity that affected the entire region.",
  CALLOUS: "merciless, ruthless, heartless — Example: His callous remark silenced the room.",
  CANDID: "honest, blunt, outspoken — Example: She gave a candid assessment of the risks involved.",
  CAPTIVATE: "fascinate, entice, enchant — Example: The storyteller’s voice can captivate any audience.",
  CATER: "help, provide, supply — Example: The new service will cater to busy families.",
  CERTIFY: "approve, authorize, verify — Example: A licensed inspector must certify the building’s safety.",
  CHRONIC: "persistent, lingering, constant — Example: He manages chronic pain with daily stretching.",
  CHRONOLOGY: "timeline, itinerary, program — Example: The museum exhibit presented the chronology of the dynasty.",
  CLICHE: "unoriginal, trite, overdone — Example: The movie’s ending felt like a cliché we’d seen before.",
  CLINCH: "secure, confirm, finalize — Example: Her final lap time will clinch the championship if it holds.",
  COHESIVE: "united, connected, close-knit — Example: The team remained cohesive despite the setback.",
  COLLABORATE: "work together, cooperate, participate — Example: The two labs will collaborate on a joint study.",
  COLOSSAL: "very large, enormous, gigantic — Example: The bridge is a colossal feat of engineering.",
  COMPRISE: "contain, include, consist (of) — Example: The board will comprise five elected members.",
  CONCISE: "to the point, succinct, brief — Example: Keep your cover letter concise and specific.",
  CONCUR: "agree, approve, assent — Example: All panelists concur that transparency is essential.",
  CONDESCENDING: "patronizing, arrogant, disdainful — Example: The memo’s condescending tone upset the staff.",
  CONFOUND: "confuse, perplex, bewilder — Example: The unexpected twist will confound even seasoned readers.",
  CONTRITE: "remorseful, apologetic, repentant — Example: He offered a contrite apology after the mistake.",
  CONTROVERSIAL: "disputable, polarizing, contentious — Example: The controversial policy sparked a heated debate.",
  CONVOLUTED: "complicated, intricate, confusing — Example: The plot becomes convoluted halfway through the series.",
  COPIOUS: "abundant, extensive, ample — Example: She took copious notes during the lecture.",
  CORDIAL: "friendly, gracious, warm — Example: We received a cordial welcome from our hosts.",
  CORROSIVE: "erosive, caustic, destructive — Example: Store corrosive chemicals in clearly labeled containers.",
  COWER: "cringe, flinch, recoil — Example: The puppy would cower during thunderstorms.",
  CRUCIAL: "important, necessary, essential — Example: Accurate data is crucial for a fair analysis.",
  CRYPTIC: "mysterious, obscure, enigmatic — Example: He left a cryptic message on the whiteboard.",
  CULPABLE: "guilty, at fault, blameworthy — Example: The report found no one person culpable for the error.",
  DEARTH: "shortage, lack, deficiency — Example: There is a dearth of parking near the stadium on weekends.",
  DEBACLE: "disaster, catastrophe, tragedy — Example: The launch became a debacle when the system crashed.",
  DEBILITATE: "disable, cripple, harm — Example: The long illness threatened to debilitate the athlete’s strength.",
  DECOR: "furnishing, ornamentation, scenery — Example: The café’s rustic decor attracts weekend brunch crowds.",
  DEDUCTION: "conclusion, answer, inference — Example: The detective’s deduction solved the riddle quickly.",
  DEFACE: "destroy, vandalize, ruin — Example: It’s illegal to deface public property with graffiti.",
  DEFICIENT: "imperfect, inadequate, faulty — Example: The report was deficient in citations and data.",
  DELIBERATE: "intentional, purposeful, planned — Example: They made a deliberate choice to reduce screen time.",
  DEPICTION: "drawing, illustration, representation — Example: The painting is a vivid depiction of city life.",
  DESIST: "cease, stop, discontinue — Example: The sign warned visitors to desist from feeding the animals.",
  DESPONDENT: "dejected, discouraged, hopeless — Example: After the loss, the team looked despondent in the locker room.",
  DESTITUTE: "poor, impoverished, penniless — Example: The shelter provides meals for destitute families.",
  DETAIN: "hold, delay, confine — Example: Security may detain passengers for additional screening.",
  DETEST: "loathe, hate, despise — Example: She detests waking up before sunrise.",
  DETRIMENTAL: "harmful, damaging, deleterious — Example: Skipping maintenance can be detrimental to engine health.",
  DEVOUR: "consume, gobble, eat — Example: We devoured the fresh bread right out of the oven.",
  DIDACTIC: "instructive, educational, pedagogical — Example: The novel’s didactic tone sometimes overshadows the plot.",
  DIMINISH: "decrease, lessen, reduce — Example: Clouds began to diminish as the wind shifted east.",
  DISCARD: "throw away, dispose of, jettison — Example: Discard the packaging in the recycling bin.",
  DISDAIN: "scorn, contempt, derision — Example: He looked at the muddy shoes with open disdain.",
  DISPARATE: "dissimilar, different, distinct — Example: The committee united several disparate viewpoints.",
  DISPOSE: "eliminate, throw away, discard — Example: Please dispose of batteries at a designated drop-off.",
  DISTORT: "warp, twist, misrepresent — Example: A wide-angle lens can distort the edges of the photo.",
  DIVISIVE: "conflicting, polarizing, contentious — Example: The proposal proved divisive among voters.",
  DORMANT: "inactive, asleep, latent — Example: The volcano has been dormant for centuries.",
  DUBIOUS: "doubtful, questionable, suspicious — Example: The claim sounds dubious without supporting evidence.",
  ECLECTIC: "diverse, varied, wide-ranging — Example: Her playlist is eclectic, mixing jazz with indie rock.",
  EFFECTIVE: "productive, efficient, successful — Example: Brief daily drills are effective for memory retention.",
  ELATION: "delight, joy, exhilaration — Example: Their elation was obvious when the results were announced.",
  ELOQUENT: "expressive, articulate, persuasive — Example: The keynote speaker delivered an eloquent address.",
  ELUSIVE: "mysterious, evasive, hard to grasp — Example: A workable compromise remained elusive after hours of talks.",
  EMBARGO: "restriction, ban, prohibition — Example: The country announced an embargo on certain exports.",
  EMBEZZLE: "pilfer, steal, misappropriate — Example: The accountant was charged for attempting to embezzle funds.",
  ENDEAVOR: "attempt, effort, enterprise — Example: Launching the nonprofit is their most ambitious endeavor yet.",
  ENMITY: "hostility, animosity, antagonism — Example: Years of distrust bred enmity between the groups.",
  EQUITY: "fairness, impartiality, justice — Example: The board discussed equity in access to resources.",
  ERADICATE: "eliminate, abolish, wipe out — Example: Public health campaigns aim to eradicate the disease.",
  ERODE: "wear away, deteriorate, crumble — Example: Ocean waves steadily erode the cliffside.",
  ESOTERIC: "obscure, arcane, specialized — Example: The lecture covered esoteric topics in number theory.",
  EVICT: "expel, remove, oust — Example: The landlord moved to evict tenants who violated the lease.",
  EVOKE: "elicit, summon, call forth — Example: The old photos evoke memories of summer camp.",
  EXAGGERATED: "embellished, overstated, inflated — Example: The advertisement made exaggerated claims about the product.",
  EXCLUSIVE: "restrictive, limited, select — Example: The club offers exclusive access to its rooftop lounge.",
  EXHAUSTIVE: "extensive, comprehensive, thorough — Example: The team conducted an exhaustive review of the data.",
  EXULT: "rejoice, celebrate, triumph — Example: Fans began to exult as the final seconds ticked down.",
  EXTOL: "praise, commend, laud — Example: Critics extol the film for its cinematography.",
  EXTRACT: "remove, withdraw, take out — Example: Dentists can extract a tooth with minimal discomfort.",
  FABRICATE: "invent, concoct, manufacture — Example: The witness tried to fabricate an alibi.",
  FALLACY: "misconception, error, falsehood — Example: The argument rests on a logical fallacy.",
  FALTER: "stumble, waver, hesitate — Example: She didn’t falter while presenting tough findings.",
  FASTIDIOUS: "careful, meticulous, exacting — Example: He is fastidious about organizing his tools.",
  FATHOMABLE: "understandable, comprehensible, graspable — Example: The concept is fathomable once you see a diagram.",
  FEEBLE: "frail, weak, infirm — Example: After the illness, he felt feeble but optimistic.",
  FERVENT: "intense, zealous, passionate — Example: The crowd offered fervent support for the cause.",
  FIASCO: "catastrophe, failure, disaster — Example: Forgetting the tickets turned the trip into a fiasco.",
  FIGURATIVE: "symbolic, allegorical, descriptive — Example: The poem’s figurative language paints vivid scenes.",
  FLAMBOYANT: "extravagant, showy, flashy — Example: The performer wore a flamboyant costume of feathers and gold.",
  FLORID: "decorative, ornate, embellished — Example: The manor’s florid ceilings drew gasps from visitors.",
  FLOURISH: "thrive, prosper, grow — Example: Community gardens flourish with steady care.",
  FORESEE: "anticipate, predict, foretell — Example: Analysts foresee stronger demand next quarter.",
  FORMIDABLE: "daunting, difficult, intimidating — Example: The marathon posed a formidable challenge.",
  FORTITUDE: "courage, bravery, strength — Example: She showed remarkable fortitude during recovery.",
  FRENETIC: "frantic, frenzied, energetic — Example: The newsroom erupted into frenetic activity at dawn.",
  FRIVOLOUS: "trivial, silly, foolish — Example: The judge dismissed the frivolous complaint.",
  FRUGAL: "economical, thrifty, careful — Example: They stayed frugal by cooking at home.",
  FUTILE: "useless, ineffective, unsuccessful — Example: Arguing with the referee proved futile.",

  GENUINE: "authentic, real, actual — Example: The appraiser confirmed the vase was a genuine antique.",
  GLOAT: "brag, boast, revel — Example: Try not to gloat after winning; congratulate your opponent instead.",
  GRAPPLE: "wrestle, fight, contend with — Example: The city must grapple with rising housing costs.",
  GRAVE: "serious, gloomy, somber — Example: The doctor spoke in a grave tone about the test results.",
  GREGARIOUS: "outgoing, affable, sociable — Example: As a gregarious host, she made every guest feel welcome.",
  GUERRILLA: "mercenary, soldier, rebel — Example: The film follows a guerrilla fighter in the mountains.",
  GULLIBLE: "trusting, foolish, naïve — Example: Scammers target gullible users with too-good-to-be-true offers.",
  HAPHAZARD: "unplanned, careless, random — Example: The haphazard wiring posed a safety risk.",
  HERITAGE: "background, tradition, culture — Example: The festival celebrates the town’s rich heritage.",
  HIERARCHY: "ranking, order, tier system — Example: Promotions moved her up the corporate hierarchy.",
  HYBRID: "mixture, combination, composite — Example: The garden features a hybrid of wildflowers and herbs.",
  HYPOCRISY: "deceitfulness, deception, insincerity — Example: Critics called the sudden policy shift hypocrisy.",
  HYSTERICAL: "very upset, agitated, frantic — Example: The crowd grew hysterical when the lights went out.",
  IMMUNE: "invulnerable, resistant, unaffected — Example: Once vaccinated, most people are immune to the virus.",
  IMPARTIAL: "fair, neutral, detached — Example: A judge must remain impartial throughout the trial.",
  IMPERTINENT: "rude, insolent, disrespectful — Example: His impertinent remark ended the discussion.",
  IMPRUDENT: "thoughtless, foolish, reckless — Example: It would be imprudent to ignore the evacuation order.",
  INCENTIVE: "inducement, enticement, motivation — Example: The bonus provides an incentive to finish early.",
  INCITE: "encourage, provoke, agitate — Example: The speech could incite unrest if shared widely.",
  INDESCRIBABLE: "beyond words, unspeakable, inexpressible — Example: The sunrise over the canyon was indescribable.",
  INDIGENOUS: "native, inborn, homegrown — Example: The park protects plants indigenous to the region.",
  INEPT: "clumsy, unskilled, incompetent — Example: His first attempts at pottery were charmingly inept.",
  INFERENCE: "conclusion, deduction, reasoning — Example: From the footprints, the ranger made an inference about the animal.",
  INITIAL: "beginning, primary, basic — Example: Please send your initial draft by Friday.",
  INNATE: "native, inborn, intrinsic — Example: She has an innate sense of rhythm.",
  INSOLENT: "disrespectful, discourteous, contemptuous — Example: The insolent response earned him detention.",
  INSTIGATE: "provoke, incite, initiate — Example: The findings may instigate further research.",
  INTIMIDATE: "alarm, frighten, threaten — Example: The large dog can intimidate visitors at first.",
  INTRICATE: "complicated, elaborate, complex — Example: The watchmaker repaired the intricate mechanism.",
  INTROSPECTION: "self-analysis, contemplation, reflection — Example: A quiet walk encourages introspection after a busy day.",
  INUNDATE: "drown, overwhelm, engulf — Example: Customer support can inundate the team after a major release.",
  IRATE: "very annoyed, angry, furious — Example: Irate callers flooded the hotline after the outage.",
  JEER: "ridicule, scoff, sneer — Example: It’s unkind to jeer at someone’s first attempt.",
  JOCULAR: "funny, cheerful, playful — Example: His jocular comments eased the tension in the room.",
  JOVIAL: "happy, lighthearted, cheerful — Example: The chef’s jovial personality made the class lively.",
  KEEN: "eager, sharp, perceptive — Example: She has a keen eye for design details.",
  KINSHIP: "family, kindred, relation — Example: He felt a kinship with other volunteers at the shelter.",
  LABYRINTH: "tangle, maze, complication — Example: The alleyways formed a labyrinth around the market.",
  LACKLUSTER: "dull, lifeless, boring — Example: The team gave a lackluster performance in the first half.",
  LACONIC: "brief, terse, to the point — Example: His laconic email contained only the essentials.",
  LAMENT: "mourn, grieve, regret — Example: Fans still lament the closing of the old theater.",
  LANGUID: "drooping, dull, lethargic — Example: The languid afternoon called for iced tea and a book.",
  LAVISH: "extravagant, excessive, abundant — Example: They hosted a lavish celebration after the awards.",
  LENIENT: "permissive, tolerant, forgiving — Example: The teacher was lenient about late assignments this week.",
  LISTLESS: "spiritless, tired, limp — Example: After the long flight, everyone felt listless and hungry.",
  LOFTY: "elevated, superior, arrogant — Example: The project has the lofty goal of reaching zero waste.",
  LUCRATIVE: "profitable, worthwhile, beneficial — Example: Consulting proved to be a lucrative career path.",
  MANEUVER: "navigate, manipulate, steer — Example: She had to maneuver carefully through the narrow streets.",
  MEDIOCRE: "average, commonplace, decent — Example: The sequel received mediocre reviews from critics.",
  MEDLEY: "assortment, combo, variety — Example: The chef served a medley of seasonal vegetables.",
  METICULOUS: "careful, diligent, precise — Example: He is meticulous about documenting each experiment.",
  MINISCULE: "tiny, very small, small-scale — Example: Even a miniscule crack can leak over time.",
  MOSAIC: "collage, patchwork, montage — Example: The plaza features a mosaic of colorful tiles.",
  MOTLEY: "mixed, varied, assorted — Example: A motley crowd gathered for the street performance.",
  MUNDANE: "ordinary, everyday, commonplace — Example: She found meaning in the most mundane chores.",
  MUTATION: "alteration, variation, change — Example: The lab studies the mutation that affects growth.",
  NAIVE: "childlike, innocent, trusting — Example: It was naive to believe the rumor without verification.",
  NEMESIS: "adversary, opponent, rival — Example: In the finals, they finally faced their long-time nemesis.",
  NONCHALANT: "casual, unconcerned, disinterested — Example: He gave a nonchalant shrug and walked away.",
  NOSTALGIA: "longing, remorse, sentimentality — Example: The old photos filled her with nostalgia for summer trips.",
  NOTORIOUS: "infamous, disreputable, ill-famed — Example: The road is notorious for delays during rush hour.",
  NOVEL: "new, original, unique — Example: The team proposed a novel approach to reduce waste.",
  NUANCE: "slight difference, implication, distinction — Example: A skilled translator preserves every nuance of the author’s intent.",
  NUISANCE: "annoyance, irritant, inconvenience — Example: The constant pop‑up alerts became a nuisance during the presentation.",

  OBDURATE: "inflexible, callous, unyielding — Example: Despite the evidence, the committee remained obdurate in its decision.",
  OBSCURE: "vague, murky, darkened — Example: The memo’s purpose was obscure until the final paragraph clarified it.",
  OBSOLETE: "outdated, ancient, antique — Example: Many offices consider fax machines obsolete in the digital era.",
  OBSTINATE: "stubborn, determined, headstrong — Example: The obstinate donkey refused to move another step.",
  OPAQUE: "cloudy, hazy, unclear — Example: The contract language was so opaque that we asked for a plain‑English addendum.",
  ORNATE: "fancy, elaborate, decorated — Example: An ornate frame surrounded the century‑old portrait.",
  OSTENTATIOUS: "excessive, extravagant, gaudy — Example: The lobby’s ostentatious chandelier drew mixed reviews.",
  PACIFY: "appease, placate, smooth over — Example: A quick refund helped pacify the frustrated customer.",
  PALPATE: "touch, press, feel — Example: The doctor will palpate the abdomen to check for tenderness.",
  PARADOX: "contradiction, absurdity, inconsistency — Example: It’s a paradox that the quietest person had the strongest influence.",
  PARAPHRASE: "summarize, rephrase, translate — Example: Please paraphrase the findings for the executive summary.",
  PARASITE: "leech, freeloader, dependent — Example: The tick is a common parasite found on hiking trails.",
  PERCEPTIVE: "alert, knowing, insightful — Example: Her perceptive comments reframed the entire discussion.",
  PERPETUATE: "maintain, preserve, uphold — Example: Unchecked rumors can perpetuate harmful myths.",
  PERSEVERE: "persist, endure, continue — Example: They persevere through daily practice, rain or shine.",
  PESTER: "bother, harass, annoy — Example: Please don’t pester the tech team while they’re deploying updates.",
  PETITE: "dainty, small, miniature — Example: She preferred a petite bouquet for the ceremony.",
  PLATEAU: "stabilize, stagnate, flatten — Example: Sales may plateau without a new product launch.",
  PONDER: "consider, contemplate, think about — Example: Take a moment to ponder the trade‑offs before deciding.",
  PRAGMATIC: "practical, matter-of-fact, realistic — Example: The board took a pragmatic approach to cutting costs.",
  PRECAUTION: "preventative, safeguard, protection — Example: Wearing gloves is a smart precaution in the lab.",
  PRECLUDE: "cease, hinder, prevent — Example: Conflicts of interest preclude him from voting on the measure.",
  PRECOCIOUS: "developed, advanced, mature — Example: The precocious child solved puzzles meant for adults.",
  PROLIFIC: "fruitful, productive, abundant — Example: She’s a prolific writer with four papers this year.",
  PROSE: "essay, speech, written text — Example: His clear prose made a complex topic accessible.",
  PROSPEROUS: "successful, thriving, wealthy — Example: The once‑sleepy town is now prosperous thanks to tourism.",
  PROTAGONIST: "hero, main character, lead role — Example: The protagonist learns empathy by the final chapter.",
  PROVOKE: "anger, aggravate, irritate — Example: The remark was meant to provoke a reaction, and it did.",
  PROXIMITY: "nearness, closeness, vicinity — Example: The school’s proximity to the park makes field trips easy.",
  PULVERIZE: "shatter, crush, break up — Example: The machine can pulverize ice in seconds.",
  QUANDARY: "difficulty, dilemma, predicament — Example: We’re in a quandary about whether to expand or consolidate.",
  QUARANTINE: "isolate, seclude, separate — Example: The clinic placed the new arrivals in quarantine for testing.",
  QUERY: "doubt, suspicion, uncertainty — Example: Submit your query via the help desk portal.",
  QUOTA: "allotment, allowance, portion — Example: Each team has a monthly quota for outreach calls.",
  RAVENOUS: "very hungry, greedy, desirous — Example: After the hike, we were ravenous and ate everything in sight.",
  RECEDE: "withdraw, diminish, decrease — Example: The floodwaters will recede once the rain stops.",
  RECTIFY: "correct, improve, revise — Example: We’ll rectify the billing error on your next statement.",
  REDUNDANT: "repetitive, reiterative, superfluous — Example: Please remove redundant phrases to tighten the draft.",
  RENAISSANCE: "renewal, rebirth, awakening — Example: The district is experiencing a cultural renaissance.",
  REPEAL: "abolish, cancel, dismantle — Example: Lawmakers moved to repeal the outdated ordinance.",
  REPLENISH: "refill, refresh, restock — Example: Remember to replenish the first‑aid kit after each trip.",
  REPOSE: "restfulness, inactivity, calm — Example: The sculpture captured a moment of perfect repose.",
  RESILIENCE: "flexibility, stamina, endurance — Example: Community resilience showed after the storm.",
  RESOLUTE: "determined, strong-willed, persistent — Example: She remained resolute despite early setbacks.",
  RESPECTIVE: "particular, specific, individual — Example: Please return the forms to your respective advisors.",
  RESTORE: "revive, refresh, renew — Example: Volunteers worked to restore the wetlands.",
  REVERE: "admire, adore, worship — Example: Many students revere the professor’s mentorship.",
  ROUSE: "awaken, provoke, excite — Example: A good headline can rouse reader interest instantly.",
  SAGACIOUS: "discerning, wise, insightful — Example: His sagacious advice saved us time and money.",
  SENTIMENTAL: "emotional, affectionate, tender — Example: She keeps a sentimental note from her grandmother.",
  SERENE: "calm, undisturbed, peaceful — Example: The lake was serene at sunrise.",
  SEVER: "cut apart, detach, separate — Example: They chose to sever the contract by mutual agreement.",
  SILHOUETTE: "outline, shadow, shape — Example: The mountain’s silhouette was visible against the sunset.",
  SIMULATE: "pretend, imitate, mimic — Example: The training module can simulate a live outage.",
  SLY: "clever, devious, cunning — Example: With a sly grin, he revealed the surprise plot twist.",
  SOLITARY: "alone, separate, isolated — Example: The eagle perched in a solitary pine.",
  SPECTACLE: "performance, display, show — Example: Fireworks turned the celebration into a grand spectacle.",
  SPECTATOR: "observer, onlooker, watcher — Example: Each spectator received a program at the gate.",
  SPECTRUM: "range, array, scope — Example: Opinions on the proposal spanned the full spectrum.",
  SPONTANEOUS: "unplanned, impulsive, improvised — Example: A spontaneous road trip lifted everyone’s spirits.",
  STARK: "bleak, harsh, severe — Example: The report drew a stark contrast between plans and results.",
  STEALTHY: "secretive, furtive, sneaky — Example: The cat made a stealthy approach toward the toy.",
  STEREOTYPE: "cliché, generalization, label — Example: The campaign challenges the stereotype of who can be a coder.",
  STIFLE: "suppress, restrain, muffle — Example: Close the door to stifle the hallway noise.",
  SUBDUE: "overcome, conquer, defeat — Example: It took hours to subdue the wildfire.",
  SULLEN: "somber, gloomy, dismal — Example: A sullen sky threatened more rain.",
  SURMISE: "guess, assume, suppose — Example: From the footprints, we surmise the deer passed at dawn.",
  SUPERFLUOUS: "extra, unnecessary, expendable — Example: Cut any superfluous slides before the client meeting.",
  SYMBIOSIS: "cooperation, collaboration, mutualism — Example: The startup’s symbiosis with the university fuels innovation.",
  SYNTHETIC: "artificial, manufactured, fake — Example: The jacket is insulated with synthetic fibers.",
  TACIT: "unspoken, implied, implicit — Example: There’s a tacit agreement to mute microphones during the call.",
  TAMPER: "interfere, alter, damage — Example: Do not tamper with the sealed container.",
  TEDIOUS: "boring, tiresome, dull — Example: He automated the most tedious steps of the workflow.",
  TEMPERATE: "moderate, restrained, mild — Example: The region’s temperate climate attracts retirees.",
  TEMPO: "pace, rhythm, rate — Example: Increase the tempo slightly in the final chorus.",
  TENACIOUS: "persistent, stubborn, insistent — Example: Her tenacious research uncovered a key data set.",
  TENTATIVE: "hesitant, uncertain, conditional — Example: We have a tentative date pending venue confirmation.",
  TEPID: "lukewarm, neutral, unenthusiastic — Example: The proposal received a tepid response from investors.",
  TIMID: "shy, bashful, modest — Example: The timid kitten hid behind the couch when guests arrived.",
  TIRADE: "abuse, outburst, rant — Example: After a brief tirade, he apologized for overreacting.",
  TRANSITORY: "temporary, momentary, fleeting — Example: The storm was transitory and passed by noon.",
  TRANQUIL: "quiet, peaceful, calm — Example: The library’s tranquil atmosphere helps with studying.",
  TRIVIAL: "unimportant, insignificant, meaningless — Example: Don’t argue over trivial details during the pitch.",
  TUMULTUOUS: "agitated, confused, disorderly — Example: The market opened to a tumultuous first hour of trading.",
  UNANIMOUS: "in agreement, united, uncontested — Example: The vote was unanimous to approve the plan.",
  UNDERMINE: "weaken, erode, sabotage — Example: Leaks can undermine trust within a team.",
  UNISON: "harmony, agreement, accord — Example: The choir sang in unison for the finale.",
  VACANT: "empty, unoccupied, deserted — Example: The storefront has been vacant since last winter.",
  VACILLATE: "fluctuate, oscillate, waver — Example: Don’t vacillate; choose a direction and commit.",
  VENERABLE: "respectable, revered, esteemed — Example: The venerable museum reopened after renovations.",
  VERIFY: "confirm, authenticate, validate — Example: Always verify the source before sharing a statistic.",
  VIBRANT: "alive, colorful, active — Example: The city’s vibrant arts scene draws visitors year‑round.",
  VIGILANT: "anxious, attentive, watchful — Example: Be vigilant when reviewing permissions for new apps.",
  VIGOR: "power, energy, capability — Example: The team attacked the challenge with fresh vigor.",
  VILE: "offensive, horrible, appalling — Example: A vile smell drifted from the dumpster.",
  VOLATILE: "explosive, unsettled, erratic — Example: Prices can be volatile during holiday travel.",
  VORACIOUS: "ravenous, insatiable, hungry — Example: She’s a voracious reader who finishes a book a week.",
  WANE: "diminish, lessen, decrease — Example: Interest in the fad began to wane by summer.",
  WARY: "careful, cautious, attentive — Example: Investors are wary of untested business models.",
  WHIMSICAL: "impulsive, playful, quirky — Example: The café’s whimsical decor delighted children.",
  WITTY: "funny, clever, amusing — Example: His witty remark broke the ice at the meeting.",
  WOE: "suffering, sorrow, sadness — Example: The article detailed the company’s financial woe last year.",
  WRATH: "anger, fury, hatred — Example: Littering in the park drew the ranger’s wrath.",
  ZEAL: "enthusiasm, devotion, intensity — Example: She tackled the fundraiser with zeal and creativity."
  
};

// ===== QUESTIONS =====
// Each item includes: number, word, choices{A,B,C,D}, answer (letter).
// Source (as noted in your file): Questions pp.22–44; Answer key pp.45–47 of Upper_Level_ISEE_Words_to_Know.pdf [1]

window.QUESTIONS = [
  // Paste ALL entries from your current QUESTIONS array here (verbatim) …
  // Example few (from your file):
  { number: 1,  word: "ABRIDGED",  choices: { A:"reinforced", B:"reiterated", C:"shortened", D:"supported" }, answer:"C" },
  { number: 2,  word: "ABRUPT",  choices: { A:"careful", B:"horizontal", C:"refreshing", D:"sudden" }, answer:"D" },
  { number: 3,  word: "ABSOLUTE",  choices: { A:"identical", B:"innocent", C:"polite", D:"total" }, answer:"D" },
  { number: 4,  word: "ABUNDANT",  choices: { A:"fantastic", B:"needy", C:"plentiful", D:"wholesome" }, answer:"C" },
  { number: 5,  word: "ACCENTUATE",choices: { A:"annoy", B:"expand", C:"instigate", D:"highlight" }, answer:"D" },
  { number: 6,  word: "ADAGE",   choices: { A:"condition", B:"enigma", C:"euphemism", D:"saying" }, answer:"D" },
  { number: 7,  word: "ADAMANT",   choices: { A:"clumsy", B:"common", C:"inflexible", D:"lively" }, answer:"C" },
  { number: 8,  word: "ADEPT",   choices: { A:"capable", B:"energetic", C:"rational", D:"witty" }, answer:"A" },
  { number: 9,  word: "ADMONISH",  choices: { A:"discount", B:"entreat", C:"reprimand", D:"surmise" }, answer:"C" },
  { number:10,  word: "ADORN",   choices: { A:"admire", B:"decorate", C:"encourage", D:"polish" }, answer:"B" },
  { number:11,  word: "ADVERSARY", choices: { A:"aide", B:"novice", C:"opponent", D:"stranger" }, answer:"C" },
  { number:12,  word: "AFFLUENT",  choices: { A:"cautious", B:"confident", C:"persuasive", D:"wealthy" }, answer:"D" },

  { number:13,  word: "AFFRONT",   choices: { A:"bristle", B:"discard", C:"excuse", D:"insult" }, answer:"D" },
  { number:14,  word: "AGHAST",  choices: { A:"reactive", B:"rejected", C:"shocked", D:"subdued" }, answer:"C" },
  { number:15,  word: "AGILE",   choices: { A:"awkward", B:"comfortable", C:"nimble", D:"peaceful" }, answer:"C" },
  { number:16,  word: "AILMENT",   choices: { A:"illness", B:"intensity", C:"manner", D:"origin" }, answer:"A" },
  { number:17,  word: "ALLEVIATE", choices: { A:"approve", B:"consider", C:"examine", D:"relieve" }, answer:"D" },
  { number:18,  word: "ALOOF",   choices: { A:"detached", B:"famished", C:"radiant", D:"unique" }, answer:"A" },
  { number:19,  word: "AMBIGUOUS", choices: { A:"ethical", B:"hasty", C:"probable", D:"unclear" }, answer:"D" },
  { number:20,  word: "AMBIVALENCE",choices:{ A:"accomplishment", B:"equality", C:"regret", D:"uncertainty" }, answer:"D" },

  // 21–26 (p.23; answers p.25)
  { number:21, word:"AMIABLE", choices:{A:"admirable", B:"confident", C:"friendly", D:"gorgeous"}, answer:"C" },
  { number:22, word:"AMPLE", choices:{A:"eccentric", B:"humorous", C:"obligatory", D:"plentiful"}, answer:"D" },
  { number:23, word:"ANECDOTE", choices:{A:"conclusion", B:"foreshadowing", C:"story", D:"twist"}, answer:"C" },
  { number:24, word:"ANIMOSITY", choices:{A:"agony", B:"hostility", C:"misfortune", D:"nervousness"}, answer:"B" },
  { number:25, word:"ANOMALOUS", choices:{A:"abnormal", B:"distinct", C:"invisible", D:"rebellious"}, answer:"A" },
  { number:26, word:"ANTAGONIST", choices:{A:"adversary", B:"ally", C:"politician", D:"pupil"}, answer:"A" },

  // 27–40 (p.24–25; answers p.26)
  { number:27, word:"APPEASE", choices:{A:"concentrate", B:"damage", C:"explain", D:"satisfy"}, answer:"D" },
  { number:28, word:"ARDUOUS", choices:{A:"difficult", B:"unusual", C:"worthy", D:"youthful"}, answer:"A" },
  { number:29, word:"ARID", choices:{A:"dry", B:"fragrant", C:"matching", D:"timely"}, answer:"A" },
  { number:30, word:"ASPIRE", choices:{A:"deceive", B:"forgive", C:"guarantee", D:"hope"}, answer:"D" },
  { number:31, word:"BARREN", choices:{A:"natural", B:"overdue", C:"sterile", D:"unclean"}, answer:"C" },
  { number:32, word:"BIAS", choices:{A:"affection", B:"alteration", C:"pollution", D:"prejudice"}, answer:"D" },
  { number:33, word:"BIZARRE", choices:{A:"glamorous", B:"painful", C:"respectable", D:"strange"}, answer:"D" },
  { number:34, word:"BLATANT", choices:{A:"complimentary", B:"former", C:"immediate", D:"obvious"}, answer:"D" },
  { number:35, word:"BLISS", choices:{A:"comfort", B:"gladness", C:"hope", D:"intrigue"}, answer:"B" },
  { number:36, word:"BOISTEROUS", choices:{A:"bumbling", B:"energizing", C:"noisy", D:"plausible"}, answer:"C" },
  { number:37, word:"BOYCOTT", choices:{A:"avoid", B:"endorse", C:"gratify", D:"narrate"}, answer:"A" },
  { number:38, word:"BRAZEN", choices:{A:"baffled", B:"bold", C:"boring", D:"bitter"}, answer:"B" },
  { number:39, word:"CALAMITY", choices:{A:"disaster", B:"capacity", C:"outcry", D:"ultimatum"}, answer:"A" },
  { number:40, word:"CALLOUS", choices:{A:"informal", B:"punctual", C:"ruthless", D:"satirical"}, answer:"C" },

    // 41–54 (p.25–26; answers p.27)
  { number:41, word:"CANDID", choices:{A:"ailing", B:"critical", C:"enchanting", D:"honest"}, answer:"D" },
  { number:42, word:"CAPTIVATE", choices:{A:"activate", B:"fascinate", C:"originate", D:"resonate"}, answer:"B" },
  { number:43, word:"CATER", choices:{A:"assist", B:"highlight", C:"identify", D:"provide"}, answer:"D" },
  { number:44, word:"CERTIFY", choices:{A:"judge", B:"label", C:"manage", D:"verify"}, answer:"D" },
  { number:45, word:"CHRONIC", choices:{A:"capable", B:"classified", C:"persistent", D:"piteous"}, answer:"C" },
  { number:46, word:"CHRONOLOGY", choices:{A:"institute", B:"movement", C:"settlement", D:"timeline"}, answer:"D" },
  { number:47, word:"CLICHE", choices:{A:"cryptic", B:"harsh", C:"pure", D:"trite"}, answer:"D" },
  { number:48, word:"CLINCH", choices:{A:"mutate", B:"obfuscate", C:"prepare", D:"secure"}, answer:"D" },
  { number:49, word:"COHESIVE", choices:{A:"inevitable", B:"modern", C:"sparse", D:"unified"}, answer:"D" },
  { number:50, word:"COLLABORATE", choices:{A:"continue", B:"contradict", C:"cooperate", D:"corrode"}, answer:"C" },
  { number:51, word:"COLOSSAL", choices:{A:"enormous", B:"hapless", C:"rugged", D:"steady"}, answer:"A" },
  { number:52, word:"COMPRISE", choices:{A:"defeat", B:"dispel", C:"ignite", D:"include"}, answer:"D" },
  { number:53, word:"CONCISE", choices:{A:"brief", B:"critical", C:"shrill", D:"timely"}, answer:"A" },
  { number:54, word:"CONCUR", choices:{A:"agree", B:"deduct", C:"emote", D:"intrude"}, answer:"A" },

    // 55–68 (p.26–27; answers p.28)
  { number:55, word:"CONDESCENDING", choices:{A:"advisable", B:"disdainful", C:"identical", D:"minimal"}, answer:"B" },
  { number:56, word:"CONFOUND", choices:{A:"acquit", B:"blare", C:"mislead", D:"perplex"}, answer:"D" },
  { number:57, word:"CONTRITE", choices:{A:"endangered", B:"mysterious", C:"repentant", D:"tarnished"}, answer:"C" },
  { number:58, word:"CONTROVERSIAL", choices:{A:"abrupt", B:"disputable", C:"episodic", D:"livid"}, answer:"B" },
  { number:59, word:"CONVOLUTED", choices:{A:"doubtful", B:"gaudy", C:"intricate", D:"justified"}, answer:"C" },
  { number:60, word:"COPIOUS", choices:{A:"abundant", B:"flawless", C:"intelligent", D:"grandiose"}, answer:"A" },
  { number:61, word:"CORDIAL", choices:{A:"gracious", B:"pugnacious", C:"satisfying", D:"vindictive"}, answer:"A" },
  { number:62, word:"CORROSIVE", choices:{A:"accessible", B:"destructive", C:"inverted", D:"oppressive"}, answer:"B" },
  { number:63, word:"COWER", choices:{A:"affirm", B:"flinch", C:"invade", D:"recline"}, answer:"B" },
  { number:64, word:"CRUCIAL", choices:{A:"emphasized", B:"genial", C:"necessary", D:"temporary"}, answer:"C" },
  { number:65, word:"CRYPTIC", choices:{A:"absolute", B:"banished", C:"effective", D:"mysterious"}, answer:"D" },
  { number:66, word:"CULPABLE", choices:{A:"direct", B:"guilty", C:"lasting", D:"traditional"}, answer:"B" },
  { number:67, word:"DEARTH", choices:{A:"abundance", B:"chasm", C:"mosaic", D:"shortage"}, answer:"D" },
  { number:68, word:"DEBACLE", choices:{A:"catastrophe", B:"improvisation", C:"persecution", D:"sportsmanship"}, answer:"A" },

    // 69–82 (p.27–29; answers p.29)
  { number:69, word:"DEBILITATE", choices:{A:"disable", B:"distinguish", C:"distrust", D:"disturb"}, answer:"A" },
  { number:70, word:"DECOR", choices:{A:"facsimile", B:"intermission", C:"ornamentation", D:"utility"}, answer:"C" },
  { number:71, word:"DEDUCTION", choices:{A:"design", B:"inference", C:"mainstay", D:"overture"}, answer:"B" },
  { number:72, word:"DEFACE", choices:{A:"incentivize", B:"magnify", C:"petrify", D:"vandalize"}, answer:"D" },
  { number:73, word:"DEFICIENT", choices:{A:"definitive", B:"inadequate", C:"portable", D:"rational"}, answer:"B" },
  { number:74, word:"DELIBERATE", choices:{A:"insidious", B:"jaded", C:"purposeful", D:"reassuring"}, answer:"C" },
  { number:75, word:"DEPICTION", choices:{A:"acceleration", B:"cessation", C:"miscommunication", D:"representation"}, answer:"D" },
  { number:76, word:"DESIST", choices:{A:"cease", B:"inquire", C:"rebel", D:"strive"}, answer:"A" },
  { number:77, word:"DESPONDENT", choices:{A:"civilized", B:"dejected", C:"pristine", D:"ridiculing"}, answer:"B" },
  { number:78, word:"DESTITUTE", choices:{A:"imagined", B:"immersive", C:"imported", D:"impoverished"}, answer:"D" },
  { number:79, word:"DETAIN", choices:{A:"arrest", B:"grovel", C:"hustle", D:"unleash"}, answer:"A" },
  { number:80, word:"DETEST", choices:{A:"abandon", B:"loathe", C:"muffle", D:"pronounce"}, answer:"B" },
  { number:81, word:"DETRIMENTAL", choices:{A:"defensive", B:"harmful", C:"triumphant", D:"unexpected"}, answer:"B" },
  { number:82, word:"DEVOUR", choices:{A:"assume", B:"consume", C:"presume", D:"resume"}, answer:"B" },

    // 83–96 (p.28–30; answers p.30)
  { number:83, word:"DIDACTIC", choices:{A:"devoted", B:"elaborative", C:"functional", D:"instructive"}, answer:"D" },
  { number:84, word:"DIMINISH", choices:{A:"impede", B:"meld", C:"omit", D:"weaken"}, answer:"D" },
  { number:85, word:"DISCARD", choices:{A:"abandon", B:"apply", C:"assemble", D:"conceal"}, answer:"A" },
  { number:86, word:"DISDAIN", choices:{A:"devastation", B:"insight", C:"nonchalance", D:"scorn"}, answer:"D" },
  { number:87, word:"DISPARATE", choices:{A:"dissimilar", B:"generous", C:"harmonious", D:"precious"}, answer:"A" },
  { number:88, word:"DISPOSE", choices:{A:"acquire", B:"eliminate", C:"salvage", D:"tarnish"}, answer:"B" },
  { number:89, word:"DISTORT", choices:{A:"banter", B:"cringe", C:"exhaust", D:"warp"}, answer:"D" },
  { number:90, word:"DIVISIVE", choices:{A:"conflicting", B:"prudent", C:"reasonable", D:"sudden"}, answer:"A" },
  { number:91, word:"DORMANT", choices:{A:"beneficial", B:"inactive", C:"smug", D:"wasteful"}, answer:"B" },
  { number:92, word:"DUBIOUS", choices:{A:"arguable", B:"buoyant", C:"cumbersome", D:"superficial"}, answer:"A" },
  { number:93, word:"ECLECTIC", choices:{A:"diverse", B:"tangible", C:"unruly", D:"vacant"}, answer:"A" },
  { number:94, word:"EFFECTIVE", choices:{A:"immeasurable", B:"laborious", C:"productive", D:"valuable"}, answer:"C" },
  { number:95, word:"ELATION", choices:{A:"contentment", B:"delight", C:"gratitude", D:"serenity"}, answer:"B" },
  { number:96, word:"ELOQUENT", choices:{A:"benevolent", B:"expressive", C:"insufferable", D:"stimulating"}, answer:"B" },

    // 97–110 (p.29–31; answers p.31)
  { number:97, word:"ELUSIVE", choices:{A:"brisk", B:"courageous", C:"mysterious", D:"tantalizing"}, answer:"C" },
  { number:98, word:"EMBARGO", choices:{A:"commitment", B:"legacy", C:"restriction", D:"scavenger"}, answer:"C" },
  { number:99, word:"EMBEZZLE", choices:{A:"distribute", B:"oppose", C:"overwhelm", D:"pilfer"}, answer:"D" },
  { number:100, word:"ENDEAVOR", choices:{A:"attempt", B:"betrothal", C:"cancellation", D:"dialect"}, answer:"A" },
  { number:101, word:"ENMITY", choices:{A:"expression", B:"hostility", C:"intelligence", D:"perfection"}, answer:"B" },
  { number:102, word:"EQUITY", choices:{A:"excursion", B:"fairness", C:"gratification", D:"isolation"}, answer:"B" },
  { number:103, word:"ERADICATE", choices:{A:"decrease", B:"eliminate", C:"isolate", D:"rupture"}, answer:"B" },
  { number:104, word:"ERODE", choices:{A:"deteriorate", B:"originate", C:"reassure", D:"submit"}, answer:"A" },
  { number:105, word:"ESOTERIC", choices:{A:"imaginary", B:"famous", C:"ideal", D:"obscure"}, answer:"D" },
  { number:106, word:"EVICT", choices:{A:"affix", B:"expel", C:"nullify", D:"saturate"}, answer:"B" },
  { number:107, word:"EVOKE", choices:{A:"banish", B:"elicit", C:"obviate", D:"pander"}, answer:"B" },
  { number:108, word:"EXAGGERATED", choices:{A:"assorted", B:"embellished", C:"paraphrased", D:"simplified"}, answer:"B" },
  { number:109, word:"EXCLUSIVE", choices:{A:"anguished", B:"cherished", C:"restrictive", D:"vindictive"}, answer:"C" },
  { number:110, word:"EXHAUSTIVE", choices:{A:"extensive", B:"harmonious", C:"numerous", D:"unnatural"}, answer:"A" },

  { number:111, word:"EXULT", choices:{A:"please", B:"rejoice", C:"shiver", D:"tolerate"}, answer:"B" },
  { number:112, word:"EXTOL", choices:{A:"illuminate", B:"praise", C:"ruminate", D:"rush"}, answer:"B" },
  { number:113, word:"EXTRACT", choices:{A:"emerge", B:"materialize", C:"remove", D:"stagger"}, answer:"C" },
  { number:114, word:"FABRICATE", choices:{A:"crumble", B:"exchange", C:"hasten", D:"invent"}, answer:"D" },
  { number:115, word:"FALLACY", choices:{A:"analogy", B:"dexterity", C:"generalization", D:"misconception"}, answer:"D" },
  { number:116, word:"FALTER", choices:{A:"flatten", B:"purge", C:"rush", D:"stumble"}, answer:"D" },
  { number:117, word:"FASTIDIOUS", choices:{A:"careful", B:"maddening", C:"squeamish", D:"terse"}, answer:"A" },
  { number:118, word:"FATHOMABLE", choices:{A:"understandable", B:"undiscerning", C:"unnatural", D:"unreasonable"}, answer:"A" },
  { number:119, word:"FEEBLE", choices:{A:"abandoned", B:"frail", C:"soothing", D:"useful"}, answer:"B" },
  { number:120, word:"FERVENT", choices:{A:"entitled", B:"hardy", C:"intense", D:"glowering"}, answer:"C" },
  { number:121, word:"FIASCO", choices:{A:"catastrophe", B:"essence", C:"implication", D:"liaison"}, answer:"A" },
  { number:122, word:"FIGURATIVE", choices:{A:"fabled", B:"contradictory", C:"symbolic", D:"transformative"}, answer:"C" },
  { number:123, word:"FLAMBOYANT", choices:{A:"careless", B:"extravagant", C:"immature", D:"sanctioned"}, answer:"B" },
  { number:124, word:"FLORID", choices:{A:"decorative", B:"inquisitive", C:"outstanding", D:"simplistic"}, answer:"A" },

    // 125–132 stems (MC) + keys  
  { number:125, word:"FLOURISH", choices:{A:"contaminate", B:"meander", C:"observe", D:"prosper"}, answer:"D" },
  { number:126, word:"FORESEE", choices:{A:"approve", B:"oppose", C:"predict", D:"reveal"}, answer:"C" },
  { number:127, word:"FORMIDABLE", choices:{A:"cautious", B:"intimidating", C:"rambling", D:"versatile"}, answer:"B" },
  { number:128, word:"FORTITUDE", choices:{A:"dynasty", B:"egotism", C:"relation", D:"strength"}, answer:"D" },
  { number:129, word:"FRENETIC", choices:{A:"frantic", B:"helpless", C:"impassive", D:"patriotic"}, answer:"A" },
  { number:130, word:"FRIVOLOUS", choices:{A:"cluttered", B:"grandiose", C:"ruthless", D:"trivial"}, answer:"D" },
  { number:131, word:"FRUGAL", choices:{A:"economical", B:"fixated", C:"macabre", D:"pungent"}, answer:"A" },
  { number:132, word:"FUTILE", choices:{A:"disparaging", B:"judicious", C:"listless", D:"useless"}, answer:"D" },

    // 133–138 stems (MC) + keys   
  { number:133, word:"GENUINE", choices:{A:"authentic", B:"childlike", C:"intriguing", D:"successive"}, answer:"A" },
  { number:134, word:"GLOAT", choices:{A:"boast", B:"exclaim", C:"ignore", D:"restrict"}, answer:"A" },
  { number:135, word:"GRAPPLE", choices:{A:"besiege", B:"clarify", C:"restrain", D:"wrestle"}, answer:"D" },
  { number:136, word:"GRAVE", choices:{A:"cluttered", B:"elegant", C:"handsome", D:"serious"}, answer:"D" },
  { number:137, word:"GREGARIOUS", choices:{A:"disorderly", B:"elevated", C:"grouchy", D:"outgoing"}, answer:"D" },
  { number:138, word:"GUERRILLA", choices:{A:"connoisseur", B:"passenger", C:"rebel", D:"socialite"}, answer:"C" },

    // 139–152 stems (MC) + keys   
  { number:139, word:"GULLIBLE", choices:{A:"adaptable", B:"anxious", C:"fragile", D:"naive"}, answer:"D" },
  { number:140, word:"HAPHAZARD", choices:{A:"coordinated", B:"enchanted", C:"random", D:"secret"}, answer:"C" },
  { number:141, word:"HERITAGE", choices:{A:"autobiography", B:"background", C:"customization", D:"dichotomy"}, answer:"B" },
  { number:142, word:"HIERARCHY", choices:{A:"constellation", B:"idolization", C:"ranking", D:"subordination"}, answer:"C" },
  { number:143, word:"HYBRID", choices:{A:"combination", B:"distribution", C:"duplication", D:"emancipation"}, answer:"A" },
  { number:144, word:"HYPOCRISY", choices:{A:"advertisement", B:"deformity", C:"establishment", D:"insincerity"}, answer:"D" },
  { number:145, word:"HYSTERICAL", choices:{A:"frantic", B:"observant", C:"private", D:"understanding"}, answer:"A" },
  { number:146, word:"IMMUNE", choices:{A:"classified", B:"delirious", C:"resistant", D:"wretched"}, answer:"C" },
  { number:147, word:"IMPARTIAL", choices:{A:"abnormal", B:"beneficial", C:"neutral", D:"negative"}, answer:"C" },
  { number:148, word:"IMPERTINENT", choices:{A:"glorified", B:"insolent", C:"stealthy", D:"temperamental"}, answer:"B" },
  { number:149, word:"IMPRUDENT", choices:{A:"foolish", B:"fortunate", C:"materialistic", D:"unbecoming"}, answer:"A" },
  { number:150, word:"INCENTIVE", choices:{A:"direction", B:"invention", C:"motivation", D:"observation"}, answer:"C" },
  { number:151, word:"INCITE", choices:{A:"destroy", B:"engrave", C:"provoke", D:"remember"}, answer:"C" },
  { number:152, word:"INDESCRIBABLE",choices:{A:"immaculate", B:"indestructible", C:"unmemorable", D:"unspeakable"}, answer:"D" },

    // 153–166 stems (MC) + keys  
  { number:153, word:"INDIGENOUS", choices:{A:"animated", B:"native", C:"puzzling", D:"studious"}, answer:"B" },
  { number:154, word:"INEPT", choices:{A:"clumsy", B:"ethereal", C:"lively", D:"thoughtless"}, answer:"A" },
  { number:155, word:"INFERENCE", choices:{A:"deduction", B:"offer", C:"statement", D:"transmission"}, answer:"A" },
  { number:156, word:"INITIAL", choices:{A:"familiar", B:"first", C:"hollow", D:"legal"}, answer:"B" },
  { number:157, word:"INNATE", choices:{A:"afraid", B:"cluttered", C:"intrinsic", D:"productive"}, answer:"C" },
  { number:158, word:"INSOLENT", choices:{A:"disrespectful", B:"eager", C:"nervous", D:"spiteful"}, answer:"A" },
  { number:159, word:"INSTIGATE", choices:{A:"convince", B:"decline", C:"disappoint", D:"initiate"}, answer:"D" },
  { number:160, word:"INTIMIDATE", choices:{A:"evaluate", B:"frighten", C:"impact", D:"pacify"}, answer:"B" },
  { number:161, word:"INTRICATE", choices:{A:"complicated", B:"damaging", C:"foregoing", D:"taboo"}, answer:"A" },
  { number:162, word:"INTROSPECTION",choices:{A:"competition", B:"contemplation", C:"experience", D:"measurement"}, answer:"B" },
  { number:163, word:"INUNDATE", choices:{A:"advise", B:"expel", C:"follow", D:"overwhelm"}, answer:"D" },
  { number:164, word:"IRATE", choices:{A:"curious", B:"furious", C:"mysterious", D:"repulsive"}, answer:"B" },
  { number:165, word:"JEER", choices:{A:"hurl", B:"ridicule", C:"signal", D:"stumble"}, answer:"B" },
  { number:166, word:"JOCULAR", choices:{A:"defective", B:"hereditary", C:"innocent", D:"playful"}, answer:"D" },

    // 167–180 stems (MC) + keys  
  { number:167, word:"JOVIAL", choices:{A:"cheerful", B:"melodic", C:"obscene", D:"zealous"}, answer:"A" },
  { number:168, word:"KEEN", choices:{A:"active", B:"eager", C:"frigid", D:"prideful"}, answer:"B" },
  { number:169, word:"KINSHIP", choices:{A:"creation", B:"inquisition", C:"relationship", D:"strangeness"}, answer:"C" },
  { number:170, word:"LABYRINTH", choices:{A:"cubicle", B:"faction", C:"maze", D:"ruse"}, answer:"C" },
  { number:171, word:"LACKLUSTER", choices:{A:"dull", B:"irksome", C:"polluted", D:"prim"}, answer:"A" },
  { number:172, word:"LACONIC", choices:{A:"brief", B:"lazy", C:"petite", D:"swift"}, answer:"A" },
  { number:173, word:"LAMENT", choices:{A:"admire", B:"embarrass", C:"mourn", D:"signal"}, answer:"C" },
  { number:174, word:"LANGUID", choices:{A:"complex", B:"lethargic", C:"lovely", D:"unkempt"}, answer:"B" },
  { number:175, word:"LAVISH", choices:{A:"extravagant", B:"gallant", C:"monotonous", D:"prominent"}, answer:"A" },
  { number:176, word:"LENIENT", choices:{A:"hazardous", B:"neutral", C:"reactive", D:"tolerant"}, answer:"D" },
  { number:177, word:"LISTLESS", choices:{A:"discreet", B:"tired", C:"trite", D:"vulgar"}, answer:"B" },
  { number:178, word:"LOFTY", choices:{A:"appeasing", B:"rough", C:"superior", D:"wasteful"}, answer:"C" },
  { number:179, word:"LUCRATIVE", choices:{A:"limber", B:"misleading", C:"profitable", D:"stagnant"}, answer:"C" },
  { number:180, word:"MANEUVER", choices:{A:"approve", B:"develop", C:"navigate", D:"perform"}, answer:"C" },

  { number:181, word:"MEDIOCRE", choices:{A:"advanced", B:"average", C:"delectable", D:"exceptional"}, answer:"B" },
  { number:182, word:"MEDLEY", choices:{A:"assortment", B:"canvas", C:"pact", D:"satchel"}, answer:"A" },
  { number:183, word:"METICULOUS", choices:{A:"ambitious", B:"precise", C:"rambunctious", D:"truthful"}, answer:"B" },
  { number:184, word:"MINISCULE", choices:{A:"kindly", B:"offbeat", C:"silent", D:"tiny"}, answer:"D" },
  { number:185, word:"MOSAIC", choices:{A:"collage", B:"design", C:"occupation", D:"sentiment"}, answer:"A" },
  { number:186, word:"MOTLEY", choices:{A:"distant", B:"substantive", C:"varied", D:"wasteful"}, answer:"C" },
  { number:187, word:"MUNDANE", choices:{A:"momentous", B:"ordinary", C:"questionable", D:"receptive"}, answer:"B" },
  { number:188, word:"MUTATION", choices:{A:"alteration", B:"disqualification", C:"inquiry", D:"rationale"}, answer:"A" },
  { number:189, word:"NAIVE", choices:{A:"clumsy", B:"gullible", C:"joyous", D:"squeamish"}, answer:"A" }, // official key
  { number:190, word:"NEMESIS", choices:{A:"adversary", B:"advocate", C:"interloper", D:"prodigy"}, answer:"A" },
  { number:191, word:"NONCHALANT", choices:{A:"unconcerned", B:"understanding", C:"unerring", D:"unforgiving"}, answer:"A" },
  { number:192, word:"NOSTALGIA", choices:{A:"dilemma", B:"exasperation", C:"sentimentality", D:"tangent"}, answer:"C" },
  { number:193, word:"NOTORIOUS", choices:{A:"competent", B:"infamous", C:"malicious", D:"reverential"}, answer:"B" },
  { number:194, word:"NOVEL", choices:{A:"coordinated", B:"intrepid", C:"original", D:"profuse"}, answer:"C" },

    // 195–200
  { number:195, word:"NUANCE", choices:{A:"apparatus", B:"impression", C:"relation", D:"subtlety"}, answer:"D" },
  { number:196, word:"NUISANCE", choices:{A:"afterthought", B:"inconvenience", C:"elation", D:"sorrow"}, answer:"B" },
  { number:197, word:"OBDURATE", choices:{A:"inflexible", B:"righteous", C:"shocking", D:"wistful"}, answer:"A" },
  { number:198, word:"OBSCURE", choices:{A:"irritable", B:"luminous", C:"murky", D:"sluggish"}, answer:"C" },
  { number:199, word:"OBSOLETE", choices:{A:"lopsided", B:"outdated", C:"resonant", D:"uptight"}, answer:"B" },
  { number:200, word:"OBSTINATE", choices:{A:"abiding", B:"educated", C:"luxuriant", D:"stubborn"}, answer:"D" },

    // 201–208
  { number:201, word:"OPAQUE", choices:{A:"aquatic", B:"cloudy", C:"tangible", D:"vast"}, answer:"B" },
  { number:202, word:"ORNATE", choices:{A:"contemplative", B:"elaborate", C:"judicial", D:"precise"}, answer:"A" },
  { number:203, word:"OSTENTATIOUS",choices:{A:"extravagant", B:"fatalistic", C:"inept", D:"lamentable"}, answer:"A" },
  { number:204, word:"PACIFY", choices:{A:"agitate", B:"appease", C:"bestow", D:"bewitch"}, answer:"B" },
  { number:205, word:"PALPATE", choices:{A:"avoid", B:"claim", C:"touch", D:"vow"}, answer:"C" },
  { number:206, word:"PARADOX", choices:{A:"argument", B:"contradiction", C:"conversation", D:"refusal"}, answer:"B" },
  { number:207, word:"PARAPHRASE", choices:{A:"congregate", B:"impersonate", C:"summarize", D:"transpose"}, answer:"C" },
  { number:208, word:"PARASITE", choices:{A:"graft", B:"leech", C:"organism", D:"stigma"}, answer:"B" },

    // 209–222
  { number:209, word:"PERCEPTIVE", choices:{A:"capable", B:"insightful", C:"luminous", D:"refined"}, answer:"B" },
  { number:210, word:"PERPETUATE", choices:{A:"amplify", B:"expand", C:"smite", D:"uphold"}, answer:"D" },
  { number:211, word:"PERSEVERE", choices:{A:"antagonize", B:"confiscate", C:"endure", D:"propel"}, answer:"C" },
  { number:212, word:"PESTER", choices:{A:"annoy", B:"employ", C:"fasten", D:"suspect"}, answer:"A" },
  { number:213, word:"PETITE", choices:{A:"fragile", B:"hospitable", C:"irresistible", D:"miniature"}, answer:"D" },
  { number:214, word:"PLATEAU", choices:{A:"actualize", B:"legitimize", C:"realize", D:"stabilize"}, answer:"D" },
  { number:215, word:"PONDER", choices:{A:"appreciate", B:"consider", C:"stress", D:"tempt"}, answer:"B" },
  { number:216, word:"PRAGMATIC", choices:{A:"awkward", B:"fathomable", C:"immediate", D:"practical"}, answer:"D" },
  { number:217, word:"PRECAUTION", choices:{A:"partition", B:"possibility", C:"projection", D:"protection"}, answer:"D" },
  { number:218, word:"PRECLUDE", choices:{A:"cure", B:"dispense", C:"prevent", D:"reflect"}, answer:"C" },
  { number:219, word:"PRECOCIOUS", choices:{A:"advanced", B:"bored", C:"comical", D:"deceptive"}, answer:"A" },
  { number:220, word:"PROLIFIC", choices:{A:"amicable", B:"domestic", C:"fruitful", D:"grateful"}, answer:"C" },
  { number:221, word:"PROSE", choices:{A:"fallacy", B:"heirloom", C:"idiom", D:"text"}, answer:"D" },
  { number:222, word:"PROSPEROUS", choices:{A:"honorable", B:"jovial", C:"successful", D:"virtuous"}, answer:"C" },

    // 223–236
  { number:223, word:"PROTAGONIST", choices:{A:"diplomat", B:"fan", C:"hero", D:"nemesis"}, answer:"C" },
  { number:224, word:"PROVOKE", choices:{A:"connect", B:"decide", C:"irritate", D:"receive"}, answer:"C" },
  { number:225, word:"PROXIMITY", choices:{A:"civility", B:"closeness", C:"predicament", D:"tactfulness"}, answer:"B" },
  { number:226, word:"PULVERIZE", choices:{A:"destroy", B:"escape", C:"fail", D:"order"}, answer:"A" },
  { number:227, word:"QUANDARY", choices:{A:"alternative", B:"example", C:"dilemma", D:"insight"}, answer:"C" },
  { number:228, word:"QUARANTINE", choices:{A:"applaud", B:"attach", C:"inject", D:"isolate"}, answer:"D" },
  { number:229, word:"QUERY", choices:{A:"aroma", B:"factoid", C:"inquiry", D:"visualization"}, answer:"C" },
  { number:230, word:"QUOTA", choices:{A:"acceptance", B:"advisory", C:"allowance", D:"atrocity"}, answer:"C" },
  { number:231, word:"RAVENOUS", choices:{A:"diverse", B:"hungry", C:"inert", D:"wily"}, answer:"B" },
  { number:232, word:"RECEDE", choices:{A:"applaud", B:"decay", C:"detect", D:"withdraw"}, answer:"D" },
  { number:233, word:"RECTIFY", choices:{A:"borrow", B:"correct", C:"deserve", D:"satisfy"}, answer:"B" },
  { number:234, word:"REDUNDANT", choices:{A:"aspirational", B:"hypothetical", C:"repetitive", D:"tentative"}, answer:"C" },
  { number:235, word:"RENAISSANCE", choices:{A:"consensus", B:"rebirth", C:"spectacle", D:"zenith"}, answer:"B" },
  { number:236, word:"REPEAL", choices:{A:"cancel", B:"compete", C:"injure", D:"support"}, answer:"A" },

    // 237–240
  { number:237, word:"REPLENISH", choices:{A:"attempt", B:"change", C:"create", D:"refill"}, answer:"D" },
  { number:238, word:"REPOSE", choices:{A:"package", B:"parable", C:"rest", D:"variety"}, answer:"C" },
  { number:239, word:"RESILIENCE", choices:{A:"company", B:"flexibility", C:"mission", D:"remembrance"}, answer:"B" },
  { number:240, word:"RESOLUTE", choices:{A:"contagious", B:"determined", C:"diplomatic", D:"tactful"}, answer:"B" },

    // 241–250
  { number:241, word:"RESPECTIVE", choices:{A:"adjusted", B:"equitable", C:"particular", D:"unstable"}, answer:"C" },
  { number:242, word:"RESTORE", choices:{A:"protect", B:"revive", C:"suspect", D:"tempt"}, answer:"B" },
  { number:243, word:"REVERE", choices:{A:"admire", B:"mourn", C:"reflect", D:"share"}, answer:"A" },
  { number:244, word:"ROUSE", choices:{A:"confess", B:"indict", C:"provoke", D:"suppose"}, answer:"C" },
  { number:245, word:"SAGACIOUS", choices:{A:"abashed", B:"discerning", C:"fervent", D:"incredulous"}, answer:"B" },
  { number:246, word:"SENTIMENTAL",choices:{A:"emotional", B:"impressive", C:"incurable", D:"grateful"}, answer:"A" },
  { number:247, word:"SERENE", choices:{A:"displeasing", B:"expanded", C:"mutual", D:"undisturbed"}, answer:"D" },
  { number:248, word:"SEVER", choices:{A:"depreciate", B:"frighten", C:"revere", D:"separate"}, answer:"D" },
  { number:249, word:"SILHOUETTE", choices:{A:"alternative", B:"example", C:"outline", D:"restoration"}, answer:"C" },
  { number:250, word:"SIMULATE", choices:{A:"educate", B:"imitate", C:"suspend", D:"typify"}, answer:"B" },

    // 251–264
  { number:251, word:"SLY", choices:{A:"blunt", B:"clever", C:"docile", D:"slippery"}, answer:"B" },
  { number:252, word:"SOLITARY", choices:{A:"alone", B:"puzzling", C:"regretful", D:"spiteful"}, answer:"A" },
  { number:253, word:"SPECTACLE", choices:{A:"display", B:"entreaty", C:"faction", D:"obligation"}, answer:"A" },
  { number:254, word:"SPECTATOR", choices:{A:"cynic", B:"observer", C:"ringleader", D:"vandal"}, answer:"B" },
  { number:255, word:"SPECTRUM", choices:{A:"center", B:"entirety", C:"epitome", D:"range"}, answer:"D" },
  { number:256, word:"SPONTANEOUS",choices:{A:"belligerent", B:"deceitful", C:"impulsive", D:"startled"}, answer:"C" },
  { number:257, word:"STARK", choices:{A:"faulty", B:"harsh", C:"quick", D:"supported"}, answer:"B" },
  { number:258, word:"STEALTHY", choices:{A:"avid", B:"furtive", C:"lithe", D:"overt"}, answer:"B" },
  { number:259, word:"STEREOTYPE", choices:{A:"ambiance", B:"generalization", C:"itinerary", D:"reverberation"}, answer:"B" },
  { number:260, word:"STIFLE", choices:{A:"expand", B:"harass", C:"suppress", D:"usurp"}, answer:"C" },
  { number:261, word:"SUBDUE", choices:{A:"argue", B:"delay", C:"overcome", D:"wrest"}, answer:"C" },
  { number:262, word:"SULLEN", choices:{A:"amenable", B:"experienced", C:"gloomy", D:"irrational"}, answer:"C" },
  { number:263, word:"SURMISE", choices:{A:"assume", B:"diffuse", C:"rebuff", D:"terminate"}, answer:"A" },
  { number:264, word:"SUPERFLUOUS",choices:{A:"flexible", B:"minute", C:"precarious", D:"unnecessary"}, answer:"D" },

    // 265–278
  { number:265, word:"SYMBIOSIS", choices:{A:"cooperation", B:"dejection", C:"growth", D:"heresy"}, answer:"A" },
  { number:266, word:"SYNTHETIC", choices:{A:"artificial", B:"emancipated", C:"poignant", D:"stimulated"}, answer:"A" },
  { number:267, word:"TACIT", choices:{A:"affable", B:"inclined", C:"tawdry", D:"unspoken"}, answer:"D" },
  { number:268, word:"TAMPER", choices:{A:"accentuate", B:"cause", C:"interfere", D:"possess"}, answer:"C" },
  { number:269, word:"TEDIOUS", choices:{A:"boring", B:"elated", C:"proud", D:"rotten"}, answer:"A" },
  { number:270, word:"TEMPERATE", choices:{A:"adept", B:"exuberant", C:"moderate", D:"pompous"}, answer:"C" },
  { number:271, word:"TEMPO", choices:{A:"duplication", B:"fallacy", C:"rhythm", D:"torpor"}, answer:"C" },
  { number:272, word:"TENACIOUS", choices:{A:"burgeoning", B:"insistent", C:"placid", D:"systematic"}, answer:"B" },
  { number:273, word:"TENTATIVE", choices:{A:"contagious", B:"deadly", C:"hesitant", D:"impatient"}, answer:"C" },
  { number:274, word:"TEPID", choices:{A:"distraught", B:"genial", C:"laudatory", D:"unenthusiastic"}, answer:"D" },
  { number:275, word:"TIMID", choices:{A:"acclaimed", B:"bashful", C:"content", D:"dispersed"}, answer:"B" },
  { number:276, word:"TIRADE", choices:{A:"insurrection", B:"mishap", C:"outburst", D:"simulation"}, answer:"C" },
  { number:277, word:"TRANSITORY", choices:{A:"communal", B:"fleeting", C:"measured", D:"preliminary"}, answer:"B" },
  { number:278, word:"TRANQUIL", choices:{A:"belligerent", B:"calm", C:"candid", D:"reprehensible"}, answer:"B" },

    // 279–290
  { number:279, word:"TRIVIAL", choices:{A:"amicable", B:"fetid", C:"insignificant", D:"whimsical"}, answer:"C" },
  { number:280, word:"TUMULTUOUS", choices:{A:"arbitrary", B:"disorderly", C:"primitive", D:"zealous"}, answer:"B" },
  { number:281, word:"UNANIMOUS", choices:{A:"uncomprehending", B:"uncontested", C:"unoriginal", D:"unrestrained"}, answer:"B" },
  { number:282, word:"UNDERMINE", choices:{A:"balance", B:"cheat", C:"fabricate", D:"weaken"}, answer:"D" },
  { number:283, word:"UNISON", choices:{A:"agreement", B:"improvisation", C:"stagnation", D:"verification"}, answer:"A" },
  { number:284, word:"VACANT", choices:{A:"empty", B:"foreign", C:"initial", D:"limited"}, answer:"A" },
  { number:285, word:"VACILLATE", choices:{A:"dissipate", B:"fluctuate", C:"revolve", D:"strengthen"}, answer:"B" },
  { number:286, word:"VENERABLE", choices:{A:"diligent", B:"exhilarated", C:"hostile", D:"respectable"}, answer:"D" },
  { number:287, word:"VERIFY", choices:{A:"confirm", B:"emphasize", C:"linger", D:"quench"}, answer:"A" },
  { number:288, word:"VIBRANT", choices:{A:"aloof", B:"excessive", C:"lively", D:"torrid"}, answer:"C" },
  { number:289, word:"VIGILANT", choices:{A:"attentive", B:"majestic", C:"wretched", D:"zealous"}, answer:"A" },
  { number:290, word:"VIGOR", choices:{A:"conclusion", B:"exhaustion", C:"foray", D:"power"}, answer:"D" },

    // --- Items 291–300 (from p.43–44) ---
  { number:291, word: "VILE", choices: { A:"decisive", B:"hesitant", C:"offensive", D:"vague" }, answer:"C" },
  { number:292, word: "VOLATILE", choices: { A:"chagrined", B:"erratic", C:"hypocritical", D:"vigorous" }, answer:"B" },
  { number:293, word: "VORACIOUS", choices: { A:"belligerent", B:"insatiable", C:"morose", D:"undermining" }, answer:"B" },
  { number:294, word: "WANE", choices: { A:"allot", B:"diminish", C:"mend", D:"wander" }, answer:"B" },
  { number:295, word: "WARY", choices: { A:"cautious", B:"frenzied", C:"lethal", D:"pained" }, answer:"A" },
  { number:296, word: "WHIMSICAL", choices: { A:"cynical", B:"obtuse", C:"playful", D:"routine" }, answer:"C" },
  { number:297, word: "WITTY", choices: { A:"clever", B:"coy", C:"stealthy", D:"vogue" }, answer:"A" },
  { number:298, word: "WOE",        choices: { A:"aggravation", B:"felicity", C:"malice", D:"sorrow" }, answer:"D" },
  { number:299, word: "WRATH", choices: { A:"anger", B:"honor", C:"inspiration", D:"vivacity" }, answer:"A" },
  { number:300, word: "ZEAL", choices: { A:"criticism", B:"enthusiasm", C:"humor", D:"redundancy" }, answer:"B" },
];

// Optional sentinel to help debug in the console
window.__VOCAB_DATA_LOADED__ = true;