// isee_vocab_enhanced2.js
// Enhanced Option 2: 300 advanced-level vocabulary words
// These words are more challenging than the original 300 and Enhanced Option 1
// None of these words appear in the original list or Enhanced Option 1
// Words distributed proportionally across all letters A-Z

window.DEFINITIONS_ENHANCED2 = {
  // A words (12)
  ABATE: "reduce, diminish, subside — Example: The storm's fury began to abate by midnight.",
  ABERRATION: "deviation, anomaly, irregularity — Example: The test results were an aberration from the usual pattern.",
  ABHOR: "detest, loathe, despise — Example: She abhors violence in any form.",
  ABJURE: "renounce, reject, recant — Example: The defendant agreed to abjure his criminal activities.",
  ABSTEMIOUS: "moderate, temperate, restrained — Example: His abstemious lifestyle promoted longevity.",
  ACCRUE: "accumulate, amass, increase — Example: Interest will accrue on the account monthly.",
  ACERBIC: "harsh, bitter, caustic — Example: His acerbic wit often offended sensitive colleagues.",
  ACQUIESCE: "consent, comply, submit — Example: She reluctantly acquiesced to their demands.",
  ACRIMONIOUS: "bitter, hostile, caustic — Example: The acrimonious divorce lasted two years.",
  ADROIT: "skillful, dexterous, clever — Example: The diplomat's adroit handling prevented conflict.",
  AESTHETIC: "artistic, beautiful, tasteful — Example: The museum's aesthetic appeal draws visitors worldwide.",
  AFFINITY: "attraction, liking, kinship — Example: She has a natural affinity for mathematics.",
  
  // B words (12)
  BELLICOSE: "warlike, aggressive, hostile — Example: The bellicose rhetoric escalated tensions between nations.",
  BENEFACTOR: "patron, donor, supporter — Example: The anonymous benefactor funded the scholarship program.",
  BENIGN: "harmless, gentle, favorable — Example: The tumor proved to be benign after testing.",
  BERATE: "scold, criticize, reprimand — Example: The coach continued to berate the players for careless errors.",
  BOMBASTIC: "pompous, grandiose, inflated — Example: His bombastic speech failed to convince the audience.",
  BOON: "benefit, blessing, advantage — Example: The new highway proved a boon to local commerce.",
  BUCOLIC: "rural, pastoral, rustic — Example: The bucolic landscape inspired many artists.",
  BULBOUS: "swollen, rounded, protruding — Example: The plant has a distinctive bulbous root.",
  BUREAUCRATIC: "administrative, official, procedural — Example: The bureaucratic process delayed the project.",
  BURGEON: "flourish, grow, expand — Example: Technology companies burgeon in this region.",
  BURNISH: "polish, shine, refine — Example: He worked to burnish his reputation after the scandal.",
  BUTTRESS: "support, strengthen, reinforce — Example: New evidence will buttress the prosecutor's case.",
  
  // C words (18)
  CACOPHONY: "discord, noise, dissonance — Example: The cacophony of city traffic made concentration difficult.",
  CAJOLE: "coax, persuade, wheedle — Example: She tried to cajole him into attending the event.",
  CALLOUS: "insensitive, hardened, unfeeling — Example: His callous disregard for others was troubling.",
  CALUMNY: "slander, defamation, libel — Example: The politician sued for calumny after false accusations.",
  CANDID: "frank, honest, straightforward — Example: The candidate gave a candid assessment of challenges ahead.",
  CANTANKEROUS: "quarrelsome, irritable, grumpy — Example: The cantankerous neighbor complained about everything.",
  CAPITULATE: "surrender, yield, submit — Example: The army refused to capitulate despite overwhelming odds.",
  CAPRICIOUS: "unpredictable, fickle, whimsical — Example: The capricious weather ruined their outdoor plans.",
  CASTIGATE: "criticize, rebuke, reprimand — Example: The editorial castigated officials for corruption.",
  CATALYST: "agent, stimulus, spark — Example: The crisis became a catalyst for reform.",
  CAUSTIC: "corrosive, sarcastic, biting — Example: Her caustic comments alienated potential allies.",
  CHARLATAN: "fraud, impostor, fake — Example: The supposed doctor was exposed as a charlatan.",
  CHICANERY: "deception, trickery, fraud — Example: The scandal revealed widespread financial chicanery.",
  CIRCUMSPECT: "cautious, prudent, wary — Example: The lawyer was circumspect in her public statements.",
  CLANDESTINE: "secret, covert, hidden — Example: They held clandestine meetings to avoid detection.",
  COALESCE: "unite, merge, combine — Example: The various factions coalesced into a single movement.",
  COGENT: "convincing, compelling, persuasive — Example: She presented a cogent argument for policy change.",
  COLLOQUIAL: "informal, conversational, vernacular — Example: The author uses colloquial language to engage readers.",
  
  // D words (18)
  DAUNT: "intimidate, discourage, dismay — Example: The magnitude of the project did not daunt her.",
  DEBUNK: "disprove, refute, discredit — Example: Scientists worked to debunk the popular myth.",
  DECORUM: "propriety, etiquette, dignity — Example: The ceremony was conducted with proper decorum.",
  DEFAME: "slander, malign, vilify — Example: The article attempted to defame the candidate's character.",
  DEFERENCE: "respect, regard, courtesy — Example: She showed deference to her elders at the gathering.",
  DEIGN: "condescend, stoop, lower oneself — Example: The celebrity did not deign to answer reporters' questions.",
  DELETERIOUS: "harmful, damaging, injurious — Example: Smoking has deleterious effects on health.",
  DELINEATE: "describe, outline, portray — Example: The report clearly delineates the boundaries of responsibility.",
  DELUGE: "flood, inundation, torrent — Example: A deluge of complaints followed the announcement.",
  DEMAGOGUE: "agitator, rabble-rouser, instigator — Example: The demagogue exploited public fears for political gain.",
  DEMEANOR: "behavior, conduct, bearing — Example: Her calm demeanor reassured the nervous students.",
  DEMURE: "modest, reserved, shy — Example: Despite her success, she maintained a demure manner.",
  DENIGRATE: "disparage, belittle, criticize — Example: It's wrong to denigrate others' achievements.",
  DERIDE: "mock, ridicule, scoff — Example: Critics derided the plan as impractical.",
  DESPOT: "tyrant, dictator, autocrat — Example: The despot ruled with an iron fist for decades.",
  DESULTORY: "random, aimless, disconnected — Example: His desultory approach to studying hindered progress.",
  DIATRIBE: "tirade, rant, denunciation — Example: The senator launched into a diatribe against opponents.",
  DICHOTOMY: "division, split, contrast — Example: There's a dichotomy between theory and practice.",
  
  // E words (18)
  EBULLIENT: "enthusiastic, exuberant, lively — Example: The team was ebullient after the championship victory.",
  ECCENTRIC: "unconventional, peculiar, quirky — Example: The eccentric inventor created unusual gadgets.",
  ECLECTIC: "diverse, varied, mixed — Example: The restaurant offers an eclectic menu.",
  EFFACE: "erase, obliterate, remove — Example: Time has effaced many ancient inscriptions.",
  EFFICACY: "effectiveness, efficiency, potency — Example: The study confirmed the drug's efficacy.",
  EFFRONTERY: "audacity, impudence, nerve — Example: She had the effrontery to demand a refund.",
  EGALITARIAN: "equal, democratic, fair — Example: The organization promotes egalitarian principles.",
  EGREGIOUS: "outrageous, shocking, flagrant — Example: The company's egregious misconduct led to lawsuits.",
  ELABORATE: "detailed, intricate, complex — Example: The architect presented an elaborate design.",
  ELEGY: "lament, dirge, tribute — Example: The poet wrote an elegy for the fallen soldiers.",
  ELOQUENT: "articulate, fluent, expressive — Example: Her eloquent speech moved the audience to tears.",
  ELUCIDATE: "clarify, explain, illuminate — Example: The professor will elucidate the complex theorem.",
  ELUSIVE: "evasive, intangible, fleeting — Example: Success remained elusive despite their efforts.",
  EMBELLISH: "decorate, ornament, enhance — Example: He tends to embellish stories for dramatic effect.",
  EMBROIL: "involve, entangle, implicate — Example: The scandal embroiled several prominent officials.",
  EMULATE: "imitate, copy, mirror — Example: Young artists often emulate their mentors.",
  ENDEMIC: "native, indigenous, local — Example: Malaria is endemic to tropical regions.",
  ENGENDER: "cause, produce, generate — Example: The policy change will engender public debate.",
  
  // F words (18)
  FACETIOUS: "joking, flippant, frivolous — Example: His facetious remarks were inappropriate for the occasion.",
  FALLACIOUS: "false, erroneous, misleading — Example: The argument rests on fallacious assumptions.",
  FASTIDIOUS: "meticulous, particular, demanding — Example: She is fastidious about cleanliness.",
  FATUOUS: "foolish, silly, inane — Example: The fatuous comment revealed his ignorance.",
  FAWN: "grovel, flatter, kowtow — Example: He refused to fawn over powerful executives.",
  FEALTY: "loyalty, allegiance, devotion — Example: Knights pledged fealty to their lord.",
  FECUND: "fertile, productive, fruitful — Example: The valley's fecund soil yields abundant crops.",
  FERVOR: "passion, zeal, intensity — Example: She spoke with fervor about environmental protection.",
  FESTER: "rot, decay, worsen — Example: Left untreated, the wound began to fester.",
  FIDELITY: "loyalty, faithfulness, devotion — Example: He showed fidelity to his principles throughout.",
  FLACCID: "limp, soft, weak — Example: The flaccid muscles indicated lack of exercise.",
  FLAGITIOUS: "wicked, villainous, heinous — Example: The judge condemned the flagitious crime.",
  FLEDGLING: "beginner, novice, newcomer — Example: The fledgling company struggled in its first year.",
  FOMENT: "incite, instigate, provoke — Example: Propaganda was used to foment rebellion.",
  FORMIDABLE: "intimidating, daunting, impressive — Example: The team faced a formidable opponent.",
  FORTUITOUS: "lucky, fortunate, accidental — Example: Their fortuitous meeting led to collaboration.",
  FRACTIOUS: "unruly, quarrelsome, irritable — Example: The fractious committee could not reach consensus.",
  FRUGAL: "thrifty, economical, sparing — Example: Her frugal habits allowed her to save substantial money.",
  
  // G words (12)
  GARRULOUS: "talkative, loquacious, verbose — Example: The garrulous passenger talked throughout the flight.",
  GERMANE: "relevant, pertinent, applicable — Example: His comments were not germane to the discussion.",
  GLIB: "smooth, slick, superficial — Example: His glib answers failed to address real concerns.",
  GRANDIOSE: "impressive, ambitious, extravagant — Example: The developer proposed grandiose plans for downtown.",
  GRATUITOUS: "unnecessary, unwarranted, unjustified — Example: The film contains gratuitous violence.",
  GREGARIOUS: "sociable, outgoing, friendly — Example: His gregarious nature made him popular.",
  GRIEVOUS: "serious, severe, grave — Example: The accident caused grievous injuries.",
  GUILE: "cunning, deceit, craftiness — Example: The con artist used guile to swindle victims.",
  HACKNEYED: "overused, trite, banal — Example: The speech was full of hackneyed phrases.",
  HAPLESS: "unlucky, unfortunate, ill-fated — Example: The hapless traveler lost his luggage and passport.",
  HEGEMONY: "dominance, supremacy, control — Example: The empire maintained hegemony over the region.",
  HUBRIS: "arrogance, pride, conceit — Example: His hubris led to his eventual downfall.",
  
  // H words (12)
  HACKNEYED: "clichéd, overused, stale — Example: The writer avoided hackneyed expressions.",
  HAPLESS: "unlucky, unfortunate, cursed — Example: The hapless team lost every game.",
  HARBINGER: "herald, sign, forerunner — Example: Dark clouds are harbingers of storms.",
  HAUGHTY: "arrogant, proud, superior — Example: Her haughty attitude alienated coworkers.",
  HEDONISTIC: "pleasure-seeking, self-indulgent, sybaritic — Example: His hedonistic lifestyle eventually caught up with him.",
  HERETICAL: "unorthodox, dissenting, radical — Example: The scientist's heretical ideas challenged conventional wisdom.",
  HIERARCHY: "ranking, pecking order, structure — Example: The corporate hierarchy determines decision-making authority.",
  HISTRIONIC: "theatrical, dramatic, melodramatic — Example: Her histrionic outburst embarrassed everyone present.",
  HOMOGENEOUS: "uniform, consistent, similar — Example: The population is relatively homogeneous.",
  HYPERBOLE: "exaggeration, overstatement, embellishment — Example: His description involved considerable hyperbole.",
  HYPOCRISY: "insincerity, duplicity, deceit — Example: The politician's hypocrisy was evident to voters.",
  HYPOTHETICAL: "theoretical, supposed, speculative — Example: Let's consider a hypothetical scenario.",
  
  // I words (12)
  ICONOCLAST: "rebel, nonconformist, dissenter — Example: The iconoclast challenged established traditions.",
  IDIOSYNCRASY: "quirk, peculiarity, mannerism — Example: Everyone has personal idiosyncrasies.",
  IGNOBLE: "dishonorable, shameful, base — Example: His ignoble actions disappointed supporters.",
  ILLICIT: "illegal, forbidden, unlawful — Example: Police cracked down on illicit activities.",
  IMMUTABLE: "unchangeable, fixed, permanent — Example: Some physical laws appear immutable.",
  IMPASSIVE: "expressionless, unemotional, stoic — Example: The guard remained impassive throughout the ordeal.",
  IMPECUNIOUS: "poor, penniless, broke — Example: The impecunious student worked three jobs.",
  IMPERIOUS: "domineering, overbearing, authoritative — Example: His imperious manner irritated subordinates.",
  IMPERTURBABLE: "calm, unflappable, composed — Example: She remained imperturbable during the crisis.",
  IMPETUOUS: "impulsive, rash, hasty — Example: His impetuous decision had serious consequences.",
  IMPLACABLE: "relentless, unforgiving, inflexible — Example: She was an implacable opponent of injustice.",
  IMPLICIT: "implied, understood, unspoken — Example: There was an implicit agreement between them.",
  
  // J words (6)
  JUDICIOUS: "wise, prudent, sensible — Example: The judge made a judicious ruling.",
  JADED: "tired, weary, cynical — Example: Years in politics left him jaded.",
  JARGON: "terminology, lingo, vocabulary — Example: Medical jargon confuses most patients.",
  JINGOISTIC: "nationalistic, chauvinistic, patriotic — Example: The jingoistic rhetoric inflamed tensions.",
  JOCUND: "cheerful, merry, jovial — Example: His jocund personality brightened every gathering.",
  JUDICIOUS: "sensible, wise, prudent — Example: She made a judicious investment decision.",
  
  // K words (4)
  KINETIC: "active, dynamic, energetic — Example: The sculpture captures kinetic energy.",
  KNAVE: "scoundrel, rogue, villain — Example: The knave deceived many innocent people.",
  KNOTTY: "complex, difficult, intricate — Example: The knotty problem required expert analysis.",
  KUDOS: "praise, acclaim, glory — Example: Kudos to the team for outstanding work.",
  
  // L words (12)
  LACONIC: "brief, concise, terse — Example: His laconic response ended the discussion.",
  LAMENT: "mourn, grieve, bewail — Example: The poet lamented the loss of innocence.",
  LANGUID: "weak, listless, sluggish — Example: The heat made everyone feel languid.",
  LATENT: "dormant, hidden, potential — Example: Her latent abilities emerged under pressure.",
  LAUDABLE: "praiseworthy, commendable, admirable — Example: The volunteers' efforts are laudable.",
  LICENTIOUS: "immoral, promiscuous, dissolute — Example: The emperor's licentious behavior scandalized the court.",
  LIMN: "outline, depict, describe — Example: The author limns a vivid portrait of society.",
  LITHE: "flexible, agile, supple — Example: The dancer's lithe movements captivated audiences.",
  LOQUACIOUS: "talkative, garrulous, verbose — Example: The loquacious guest dominated conversation.",
  LUGUBRIOUS: "mournful, gloomy, sad — Example: The funeral proceeded in a lugubrious atmosphere.",
  LUMINOUS: "bright, radiant, glowing — Example: The painting has a luminous quality.",
  LURID: "sensational, shocking, vivid — Example: The tabloid featured lurid headlines.",
  
  // M words (12)
  MALADROIT: "clumsy, awkward, inept — Example: His maladroit attempt at diplomacy worsened relations.",
  MALEVOLENT: "hostile, malicious, spiteful — Example: The villain's malevolent intentions were clear.",
  MALLEABLE: "pliable, flexible, adaptable — Example: Gold is a highly malleable metal.",
  MAVERICK: "nonconformist, rebel, individualist — Example: The maverick politician defied party leadership.",
  MELANCHOLY: "sad, depressed, gloomy — Example: The melancholy music suited his mood.",
  MENDACIOUS: "dishonest, lying, deceitful — Example: The mendacious testimony was exposed.",
  MERCURIAL: "volatile, unpredictable, changeable — Example: His mercurial temperament made planning difficult.",
  MERITORIOUS: "deserving, worthy, praiseworthy — Example: She received an award for meritorious service.",
  METAMORPHOSIS: "transformation, change, conversion — Example: The caterpillar undergoes metamorphosis.",
  METICULOUS: "careful, precise, thorough — Example: The surgeon's meticulous technique ensured success.",
  MIRE: "entangle, involve, bog down — Example: The company became mired in legal disputes.",
  MITIGATE: "reduce, lessen, alleviate — Example: New policies will mitigate environmental damage.",
  
  // N words (10)
  NEBULOUS: "vague, unclear, indefinite — Example: His plans remained nebulous and unconvincing.",
  NEFARIOUS: "wicked, villainous, evil — Example: The nefarious plot was uncovered just in time.",
  NEOPHYTE: "beginner, novice, newcomer — Example: The neophyte made predictable mistakes.",
  NONCHALANT: "casual, indifferent, unconcerned — Example: He maintained a nonchalant attitude.",
  NOSTALGIC: "sentimental, wistful, yearning — Example: The old photographs made her nostalgic.",
  NOTORIOUS: "infamous, disreputable, scandalous — Example: The notorious criminal was finally captured.",
  NOVICE: "beginner, amateur, learner — Example: The novice painter showed promise.",
  NUANCE: "subtlety, shade, distinction — Example: The translation captures every nuance.",
  NUMINOUS: "spiritual, mystical, divine — Example: The cathedral had a numinous atmosphere.",
  NURTURE: "nourish, foster, cultivate — Example: Good schools nurture students' potential.",
  
  // O words (10)
  OBDURATE: "stubborn, inflexible, unyielding — Example: He remained obdurate despite all arguments.",
  OBFUSCATE: "confuse, obscure, muddle — Example: Complex jargon serves only to obfuscate.",
  OBSEQUIOUS: "servile, fawning, submissive — Example: His obsequious behavior was embarrassing.",
  OBTUSE: "dull, insensitive, slow — Example: He was obtuse to her obvious hints.",
  OMINOUS: "threatening, foreboding, sinister — Example: The ominous clouds suggested severe weather.",
  ONEROUS: "burdensome, oppressive, demanding — Example: The contract imposed onerous obligations.",
  OPAQUE: "unclear, obscure, impenetrable — Example: The legal language was opaque to laypeople.",
  OPPORTUNE: "timely, favorable, convenient — Example: This is an opportune moment to negotiate.",
  ORTHODOX: "conventional, traditional, standard — Example: He challenged orthodox economic theory.",
  OSTENSIBLE: "apparent, seeming, professed — Example: His ostensible reason concealed the truth.",
  
  // P words (18)
  PALPABLE: "tangible, obvious, evident — Example: The tension in the room was palpable.",
  PANACEA: "cure-all, remedy, solution — Example: There's no panacea for economic problems.",
  PARADIGM: "model, pattern, framework — Example: The discovery created a new scientific paradigm.",
  PARADOX: "contradiction, puzzle, anomaly — Example: It's a paradox that wealth creates new problems.",
  PARAGON: "model, exemplar, ideal — Example: She is a paragon of virtue and integrity.",
  PARIAH: "outcast, exile, untouchable — Example: The scandal made him a social pariah.",
  PAROCHIAL: "narrow, provincial, limited — Example: His parochial views limited his understanding.",
  PARSIMONIOUS: "stingy, miserly, frugal — Example: The parsimonious boss refused raises.",
  PARTISAN: "biased, prejudiced, one-sided — Example: The partisan media coverage distorted facts.",
  PATHOS: "emotion, feeling, sympathy — Example: The speech was full of pathos.",
  PAUCITY: "scarcity, shortage, lack — Example: There's a paucity of evidence supporting this theory.",
  PEDANTIC: "overly scholarly, pompous, formal — Example: His pedantic lectures bored students.",
  PENCHANT: "liking, inclination, tendency — Example: She has a penchant for spicy food.",
  PENITENT: "remorseful, sorry, regretful — Example: The penitent criminal apologized to victims.",
  PENSIVE: "thoughtful, reflective, contemplative — Example: She sat in a pensive mood.",
  PENURY: "poverty, destitution, want — Example: The family lived in abject penury.",
  PERFIDIOUS: "treacherous, disloyal, faithless — Example: The perfidious ally betrayed the treaty.",
  PERFUNCTORY: "cursory, superficial, routine — Example: He gave a perfunctory inspection.",
  
  // Q words (6)
  QUAGMIRE: "predicament, difficulty, mess — Example: The war became a quagmire with no exit.",
  QUANDARY: "dilemma, predicament, difficulty — Example: She faced a quandary about career choices.",
  QUARANTINE: "isolate, separate, sequester — Example: Officials quarantined the infected patients.",
  QUASH: "suppress, crush, put down — Example: The military moved to quash the rebellion.",
  QUERULOUS: "complaining, whining, petulant — Example: The querulous customer demanded a refund.",
  QUIXOTIC: "idealistic, impractical, unrealistic — Example: His quixotic quest was doomed to fail.",
  
  // R words (12)
  RANCOROUS: "bitter, spiteful, resentful — Example: The rancorous debate accomplished nothing.",
  RAPACIOUS: "greedy, voracious, predatory — Example: The rapacious corporation exploited workers.",
  RAZE: "demolish, destroy, level — Example: They plan to raze the old building.",
  RECALCITRANT: "defiant, uncooperative, obstinate — Example: The recalcitrant prisoner refused orders.",
  RECAPITULATE: "summarize, repeat, restate — Example: Let me recapitulate the main points.",
  RECLUSIVE: "solitary, withdrawn, hermit-like — Example: The reclusive author avoided publicity.",
  REDOLENT: "fragrant, aromatic, evocative — Example: The garden was redolent with roses.",
  REDRESS: "remedy, correct, compensate — Example: Victims sought redress through the courts.",
  REDUNDANT: "superfluous, unnecessary, repetitive — Example: The redundant clauses confused readers.",
  REFUTE: "disprove, rebut, contradict — Example: Evidence clearly refutes his claims.",
  RELEGATE: "demote, downgrade, banish — Example: The player was relegated to the bench.",
  RELINQUISH: "surrender, give up, abandon — Example: He refused to relinquish control.",
  
  // S words (18)
  SAGACITY: "wisdom, insight, judgment — Example: The elder's sagacity guided the community.",
  SALIENT: "prominent, important, striking — Example: The report highlights the salient features.",
  SANGUINE: "optimistic, hopeful, confident — Example: Despite setbacks, she remained sanguine.",
  SARDONIC: "mocking, sarcastic, cynical — Example: His sardonic wit made people uncomfortable.",
  SAVANT: "expert, genius, scholar — Example: The mathematical savant solved complex equations mentally.",
  SCRUPULOUS: "careful, conscientious, ethical — Example: She was scrupulous in her research methods.",
  SECTARIAN: "narrow, partisan, factional — Example: Sectarian violence plagued the region.",
  SEDITIOUS: "rebellious, subversive, traitorous — Example: The government prosecuted seditious speech.",
  SEMINAL: "influential, groundbreaking, pivotal — Example: Darwin's seminal work revolutionized biology.",
  SENSUOUS: "pleasurable, gratifying, aesthetic — Example: The sensuous music enchanted listeners.",
  SERENDIPITY: "chance, luck, fortune — Example: Meeting her mentor was pure serendipity.",
  SOBRIETY: "seriousness, temperance, moderation — Example: The occasion called for sobriety.",
  SOLICITOUS: "concerned, attentive, caring — Example: The nurse was solicitous of patients' comfort.",
  SOMNOLENT: "sleepy, drowsy, lethargic — Example: The warm room made everyone somnolent.",
  SPECIOUS: "false, misleading, deceptive — Example: His specious argument deceived few people.",
  SPURIOUS: "false, fake, bogus — Example: The document proved to be spurious.",
  STOIC: "unemotional, impassive, resigned — Example: She remained stoic throughout the ordeal.",
  STRIDENT: "harsh, shrill, grating — Example: His strident voice dominated the meeting.",
  
  // T words (12)
  TACIT: "implied, understood, unspoken — Example: They had a tacit agreement to disagree.",
  TANGENTIAL: "peripheral, irrelevant, divergent — Example: His tangential comments distracted from the issue.",
  TAUTOLOGY: "redundancy, repetition, pleonasm — Example: 'Free gift' is a tautology.",
  TEMERITY: "audacity, boldness, nerve — Example: He had the temerity to criticize his boss.",
  TEMPERANCE: "moderation, restraint, self-control — Example: She practiced temperance in all things.",
  TENACIOUS: "persistent, determined, stubborn — Example: The tenacious lawyer never gave up.",
  TENET: "principle, belief, doctrine — Example: Free speech is a core tenet of democracy.",
  TEPID: "lukewarm, halfhearted, unenthusiastic — Example: The proposal received tepid support.",
  TERSE: "brief, concise, abrupt — Example: His terse reply ended the conversation.",
  TIMOROUS: "timid, fearful, nervous — Example: The timorous rabbit fled at any sound.",
  TIRADE: "outburst, harangue, diatribe — Example: The customer launched into a tirade.",
  TORPOR: "lethargy, sluggishness, inactivity — Example: The heat induced a state of torpor.",
  
  // U words (8)
  UBIQUITOUS: "omnipresent, everywhere, universal — Example: Smartphones are ubiquitous in society.",
  ULTERIOR: "hidden, concealed, covert — Example: She suspected he had ulterior motives.",
  UMBRAGE: "offense, resentment, displeasure — Example: He took umbrage at the criticism.",
  UNASSUMING: "modest, humble, unpretentious — Example: Despite wealth, he remained unassuming.",
  UNCTUOUS: "oily, ingratiating, smarmy — Example: The unctuous salesman repelled customers.",
  UNDULATE: "wave, ripple, fluctuate — Example: The flag undulated in the breeze.",
  UNEQUIVOCAL: "clear, definite, unambiguous — Example: She gave an unequivocal denial.",
  UNSCRUPULOUS: "dishonest, immoral, unprincipled — Example: The unscrupulous dealer cheated customers.",
  
  // V words (12)
  VACILLATE: "waver, hesitate, fluctuate — Example: Don't vacillate; make a decision.",
  VAGARY: "whim, caprice, quirk — Example: The vagaries of weather affected the harvest.",
  VAPID: "dull, insipid, lifeless — Example: The vapid conversation bored everyone.",
  VARIEGATED: "varied, diverse, multicolored — Example: The garden had variegated foliage.",
  VEHEMENT: "intense, passionate, forceful — Example: She gave a vehement defense of her position.",
  VENEER: "facade, surface, pretense — Example: His politeness was merely a veneer.",
  VERACIOUS: "truthful, honest, accurate — Example: The witness proved to be veracious.",
  VERBATIM: "word-for-word, exact, literal — Example: Quote me verbatim, without changes.",
  VERBOSE: "wordy, long-winded, prolix — Example: His verbose speech lasted two hours.",
  VERISIMILITUDE: "realism, authenticity, plausibility — Example: The novel has remarkable verisimilitude.",
  VERNACULAR: "dialect, language, idiom — Example: He wrote in the local vernacular.",
  VICARIOUS: "indirect, secondhand, substitute — Example: She lived vicariously through her children.",
  
  // W words (8)
  WANE: "decline, decrease, diminish — Example: His influence began to wane.",
  WANTON: "reckless, malicious, deliberate — Example: The wanton destruction shocked observers.",
  WIZENED: "shriveled, wrinkled, withered — Example: The wizened old man told ancient stories.",
  WRATH: "anger, rage, fury — Example: The king's wrath was terrible to behold.",
  WROUGHT: "formed, shaped, created — Example: The sculpture was beautifully wrought.",
  WILY: "cunning, crafty, shrewd — Example: The wily fox escaped the hunters.",
  WINSOME: "charming, attractive, appealing — Example: Her winsome smile won hearts.",
  WREAK: "inflict, cause, bring about — Example: The storm will wreak havoc on the coast.",
  
  // X, Y, Z words (4)
  XENOPHOBIC: "intolerant, prejudiced, bigoted — Example: Xenophobic attitudes harm society.",
  YOKE: "burden, bond, harness — Example: They threw off the yoke of oppression.",
  ZEALOT: "fanatic, extremist, radical — Example: The zealot refused to compromise.",
  ZEPHYR: "breeze, wind, draft — Example: A gentle zephyr cooled the afternoon."
};

window.QUESTIONS_ENHANCED2 = [
  // A words (12 questions: 601-612)
  { number: 601, word: "ABATE", choices: { A:"to shift", B:"to lessen", C:"to pause", D:"to change" }, answer:"B" },
  { number: 602, word: "ABERRATION", choices: { A:"a mystery", B:"a deviation", C:"an oversight", D:"a mistake" }, answer:"B" },
  { number: 603, word: "ABHOR", choices: { A:"to criticize", B:"to disagree with", C:"to detest", D:"to disappoint" }, answer:"C" },
  { number: 604, word: "ABJURE", choices: { A:"to disobey", B:"to regret", C:"to forget", D:"to renounce" }, answer:"D" },
  { number: 605, word: "ABSTEMIOUS", choices: { A:"healthy", B:"simple", C:"moderate", D:"cautious" }, answer:"C" },
  { number: 606, word: "ACCRUE", choices: { A:"to invest", B:"to spend", C:"to accumulate", D:"to save" }, answer:"C" },
  { number: 607, word: "ACERBIC", choices: { A:"harsh", B:"loud", C:"formal", D:"indirect" }, answer:"A" },
  { number: 608, word: "ACQUIESCE", choices: { A:"to consent", B:"to argue", C:"to ignore", D:"to propose" }, answer:"A" },
  { number: 609, word: "ACRIMONIOUS", choices: { A:"loud", B:"bitter", C:"tense", D:"serious" }, answer:"B" },
  { number: 610, word: "ADROIT", choices: { A:"intelligent", B:"careful", C:"skillful", D:"brave" }, answer:"C" },
  { number: 611, word: "AESTHETIC", choices: { A:"valuable", B:"historic", C:"artistic", D:"colorful" }, answer:"C" },
  { number: 612, word: "AFFINITY", choices: { A:"a requirement", B:"an attraction", C:"an opinion", D:"a memory" }, answer:"B" },

  // B words (12 questions: 613-624)
  { number: 613, word: "BELLICOSE", choices: { A:"courageous", B:"patriotic", C:"warlike", D:"reckless" }, answer:"C" },
  { number: 614, word: "BENEFACTOR", choices: { A:"a donor", B:"an employer", C:"a volunteer", D:"an official" }, answer:"A" },
  { number: 615, word: "BENIGN", choices: { A:"calm", B:"harmless", C:"treatable", D:"minor" }, answer:"B" },
  { number: 616, word: "BERATE", choices: { A:"to punish", B:"to dislike", C:"to correct", D:"to scold" }, answer:"D" },
  { number: 617, word: "BOMBASTIC", choices: { A:"pompous", B:"arrogant", C:"lengthy", D:"boastful" }, answer:"A" },
  { number: 618, word: "BOON", choices: { A:"a gift", B:"a miracle", C:"a benefit", D:"a discovery" }, answer:"C" },
  { number: 619, word: "BUCOLIC", choices: { A:"isolated", B:"unpopulated", C:"rural", D:"traditional" }, answer:"C" },
  { number: 620, word: "BULBOUS", choices: { A:"swollen", B:"fat", C:"spherical", D:"heavy" }, answer:"A" },
  { number: 621, word: "BUREAUCRATIC", choices: { A:"inefficient", B:"administrative", C:"governmental", D:"slow" }, answer:"B" },
  { number: 622, word: "BURGEON", choices: { A:"to spread", B:"to appear", C:"to flourish", D:"to accelerate" }, answer:"C" },
  { number: 623, word: "BURNISH", choices: { A:"to restore", B:"to clean", C:"to decorate", D:"to polish" }, answer:"D" },
  { number: 624, word: "BUTTRESS", choices: { A:"to construct", B:"to support", C:"to build", D:"to design" }, answer:"B" },

  // C words (18 questions: 625-642)
  { number: 625, word: "CACOPHONY", choices: { A:"a loud argument", B:"a musical performance", C:"a harsh mixture of sounds", D:"an unfamiliar language" }, answer:"C" },
  { number: 626, word: "CAJOLE", choices: { A:"to praise", B:"to trick", C:"to persuade", D:"to bribe" }, answer:"C" },
  { number: 627, word: "CALLOUS", choices: { A:"insensitive", B:"cruel", C:"thoughtless", D:"arrogant" }, answer:"A" },
  { number: 628, word: "CALUMNY", choices: { A:"a rumor", B:"an accusation", C:"slander", D:"a complaint" }, answer:"C" },
  { number: 629, word: "CANDID", choices: { A:"brave", B:"frank", C:"simple", D:"clear" }, answer:"B" },
  { number: 630, word: "CANTANKEROUS", choices: { A:"impolite", B:"unfriendly", C:"stubborn", D:"quarrelsome" }, answer:"D" },
  { number: 631, word: "CAPITULATE", choices: { A:"to surrender", B:"to withdraw", C:"to retreat", D:"to agree" }, answer:"A" },
  { number: 632, word: "CAPRICIOUS", choices: { A:"unpredictable", B:"spontaneous", C:"inconsistent", D:"careless" }, answer:"A" },
  { number: 633, word: "CASTIGATE", choices: { A:"to punish", B:"to dislike", C:"to criticize", D:"to judge" }, answer:"C" },
  { number: 634, word: "CATALYST", choices: { A:"an ingredient", B:"a stimulus", C:"a result", D:"a reaction" }, answer:"B" },
  { number: 635, word: "CAUSTIC", choices: { A:"hurtful", B:"unpleasant", C:"insulting", D:"corrosive" }, answer:"D" },
  { number: 636, word: "CHARLATAN", choices: { A:"a criminal", B:"a fraud", C:"a liar", D:"an actor" }, answer:"B" },
  { number: 637, word: "CHICANERY", choices: { A:"forgery", B:"deception", C:"corruption", D:"theft" }, answer:"B" },
  { number: 638, word: "CIRCUMSPECT", choices: { A:"cautious", B:"suspicious", C:"reluctant", D:"thoughtful" }, answer:"A" },
  { number: 639, word: "CLANDESTINE", choices: { A:"forbidden", B:"illegal", C:"secret", D:"dangerous" }, answer:"C" },
  { number: 640, word: "COALESCE", choices: { A:"to combine", B:"to grow", C:"to form", D:"to arrange" }, answer:"A" },
  { number: 641, word: "COGENT", choices: { A:"intelligent", B:"convincing", C:"logical", D:"well-spoken" }, answer:"B" },
  { number: 642, word: "COLLOQUIAL", choices: { A:"regional", B:"common", C:"informal", D:"improper" }, answer:"C" },

  // D words (18 questions: 643-660)
  { number: 643, word: "DAUNT", choices: { A:"to frighten", B:"to challenge", C:"to intimidate", D:"to worry" }, answer:"C" },
  { number: 644, word: "DEBUNK", choices: { A:"to expose", B:"to disprove", C:"to ridicule", D:"to question" }, answer:"B" },
  { number: 645, word: "DECORUM", choices: { A:"formality", B:"politeness", C:"propriety", D:"respect" }, answer:"C" },
  { number: 646, word: "DEFAME", choices: { A:"to slander", B:"to criticize", C:"to accuse", D:"to expose" }, answer:"A" },
  { number: 647, word: "DEFERENCE", choices: { A:"respect", B:"obedience", C:"civility", D:"admiration" }, answer:"A" },
  { number: 648, word: "DEIGN", choices: { A:"to permit", B:"to condescend", C:"to accept", D:"to notice" }, answer:"B" },
  { number: 649, word: "DELETERIOUS", choices: { A:"annoying", B:"harmful", C:"disgusting", D:"ineffective" }, answer:"B" },
  { number: 650, word: "DELINEATE", choices: { A:"to draw", B:"to illustrate", C:"to describe", D:"to argue" }, answer:"C" },
  { number: 651, word: "DELUGE", choices: { A:"a downpour", B:"a disaster", C:"a flood", D:"an overflow" }, answer:"C" },
  { number: 652, word: "DEMAGOGUE", choices: { A:"a tyrant", B:"a politician", C:"an agitator", D:"a celebrity" }, answer:"C" },
  { number: 653, word: "DEMEANOR", choices: { A:"a mood", B:"a personality", C:"behavior", D:"a reputation" }, answer:"C" },
  { number: 654, word: "DEMURE", choices: { A:"shy", B:"delicate", C:"modest", D:"feminine" }, answer:"C" },
  { number: 655, word: "DENIGRATE", choices: { A:"to challenge", B:"to insult", C:"to belittle", D:"to challenge" }, answer:"C" },
  { number: 656, word: "DERIDE", choices: { A:"to mock", B:"to tease", C:"to question", D:"to reject" }, answer:"A" },
  { number: 657, word: "DESPOT", choices: { A:"a monarch", B:"a tyrant", C:"a ruler", D:"a judge" }, answer:"B" },
  { number: 658, word: "DESULTORY", choices: { A:"lazy", B:"random", C:"ineffective", D:"slow" }, answer:"B" },
  { number: 659, word: "DIATRIBE", choices: { A:"a protest", B:"a sermon", C:"a tirade", D:"a debate" }, answer:"C" },
  { number: 660, word: "DICHOTOMY", choices: { A:"a disagreement", B:"a conflict", C:"a division", D:"a puzzle" }, answer:"C" },

  // E words (18 questions: 661-678)
  { number: 661, word: "EBULLIENT", choices: { A:"cheerful", B:"upbeat", C:"enthusiastic", D:"agitated" }, answer:"C" },
  { number: 662, word: "ECCENTRIC", choices: { A:"creative", B:"unconventional", C:"strange", D:"solitary" }, answer:"B" },
  { number: 663, word: "ECLECTIC", choices: { A:"diverse", B:"unusual", C:"extensive", D:"international" }, answer:"A" },
  { number: 664, word: "EFFACE", choices: { A:"to remove", B:"to scratch out", C:"to erase", D:"to cancel" }, answer:"C" },
  { number: 665, word: "EFFICACY", choices: { A:"strength", B:"potential", C:"effectiveness", D:"value" }, answer:"C" },
  { number: 666, word: "EFFRONTERY", choices: { A:"arrogance", B:"rudeness", C:"audacity", D:"disrespect" }, answer:"C" },
  { number: 667, word: "EGALITARIAN", choices: { A:"socialist", B:"fair-minded", C:"equal", D:"democratic" }, answer:"C" },
  { number: 668, word: "EGREGIOUS", choices: { A:"shocking", B:"harmful", C:"unethical", D:"unacceptable" }, answer:"A" },
  { number: 669, word: "ELABORATE", choices: { A:"ornate", B:"fancy", C:"detailed", D:"expensive" }, answer:"C" },
  { number: 670, word: "ELEGY", choices: { A:"a sad story", B:"a lament", C:"a formal speech", D:"a short poem" }, answer:"B" },
  { number: 671, word: "ELOQUENT", choices: { A:"poetic", B:"articulate", C:"heartfelt", D:"beautiful" }, answer:"B" },
  { number: 672, word: "ELUCIDATE", choices: { A:"to clarify", B:"to demonstrate", C:"to prove", D:"to reveal" }, answer:"A" },
  { number: 673, word: "ELUSIVE", choices: { A:"puzzling", B:"evasive", C:"secretive", D:"unpredictable" }, answer:"B" },
  { number: 674, word: "EMBELLISH", choices: { A:"to fabricate", B:"to decorate", C:"to augment", D:"to overstate" }, answer:"B" },
  { number: 675, word: "EMBROIL", choices: { A:"to involve", B:"to accuse", C:"to confuse", D:"to trap" }, answer:"A" },
  { number: 676, word: "EMULATE", choices: { A:"to compete with", B:"to imitate", C:"to praise", D:"to follow" }, answer:"B" },
  { number: 677, word: "ENDEMIC", choices: { A:"contagious", B:"native", C:"dangerous", D:"isolated" }, answer:"B" },
  { number: 678, word: "ENGENDER", choices: { A:"to cause", B:"to require", C:"to include", D:"to begin" }, answer:"A" },

  // F words (18 questions: 679-696)
  { number: 679, word: "FACETIOUS", choices: { A:"sarcastic", B:"clever", C:"joking", D:"inappropriate" }, answer:"C" },
  { number: 680, word: "FALLACIOUS", choices: { A:"unproven", B:"false", C:"illogical", D:"unlikely" }, answer:"B" },
  { number: 681, word: "FASTIDIOUS", choices: { A:"orderly", B:"meticulous", C:"polite", D:"intellectual" }, answer:"B" },
  { number: 682, word: "FATUOUS", choices: { A:"foolish", B:"thoughtless", C:"ignorant", D:"comical" }, answer:"A" },
  { number: 683, word: "FAWN", choices: { A:"to flatter", B:"to serve", C:"to praise", D:"to grovel" }, answer:"D" },
  { number: 684, word: "FEALTY", choices: { A:"loyalty", B:"respect", C:"a promise", D:"a tribute" }, answer:"A" },
  { number: 685, word: "FECUND", choices: { A:"healthy", B:"natural", C:"fertile", D:"numerous" }, answer:"C" },
  { number: 686, word: "FERVOR", choices: { A:"passion", B:"excitement", C:"anger", D:"determination" }, answer:"A" },
  { number: 687, word: "FESTER", choices: { A:"to hurt", B:"to swell", C:"to rot", D:"to darken" }, answer:"C" },
  { number: 688, word: "FIDELITY", choices: { A:"honesty", B:"loyalty", C:"trustworthiness", D:"commitment" }, answer:"B" },
  { number: 689, word: "FLACCID", choices: { A:"weak", B:"loose", C:"limp", D:"empty" }, answer:"C" },
  { number: 690, word: "FLAGITIOUS", choices: { A:"illegal", B:"immoral", C:"wicked", D:"shameful" }, answer:"C" },
  { number: 691, word: "FLEDGLING", choices: { A:"an intern", B:"a young bird", C:"a beginner", D:"a child" }, answer:"C" },
  { number: 692, word: "FOMENT", choices: { A:"to influence", B:"to encourage", C:"to start", D:"to incite" }, answer:"D" },
  { number: 693, word: "FORMIDABLE", choices: { A:"dangerous", B:"aggressive", C:"intimidating", D:"powerful" }, answer:"C" },
  { number: 694, word: "FORTUITOUS", choices: { A:"lucky", B:"random", C:"opportune", D:"unplanned" }, answer:"A" },
  { number: 695, word: "FRACTIOUS", choices: { A:"disagreeable", B:"unruly", C:"impatient", D:"stubborn" }, answer:"B" },
  { number: 696, word: "FRUGAL", choices: { A:"stingy", B:"thrifty", C:"sensible", D:"miserly" }, answer:"B" },

  // G words (12 questions: 697-708)
  { number: 697, word: "GARRULOUS", choices: { A:"outgoing", B:"talkative", C:"annoying", D:"loud" }, answer:"B" },
  { number: 698, word: "GERMANE", choices: { A:"appropriate", B:"connected", C:"relevant", D:"useful" }, answer:"C" },
  { number: 699, word: "GLIB", choices: { A:"slick", B:"charming", C:"insincere", D:"dishonest" }, answer:"A" },
  { number: 700, word: "GRANDIOSE", choices: { A:"arrogant", B:"ostentatious", C:"impressive", D:"expensive" }, answer:"C" },
  { number: 701, word: "GRATUITOUS", choices: { A:"unnecessary", B:"excessive", C:"inappropriate", D:"rude" }, answer:"A" },
  { number: 702, word: "GREGARIOUS", choices: { A:"welcoming", B:"sociable", C:"talkative", D:"popular" }, answer:"B" },
  { number: 703, word: "GRIEVOUS", choices: { A:"unfortunate", B:"serious", C:"sad", D:"painful" }, answer:"B" },
  { number: 704, word: "GUILE", choices: { A:"cunning", B:"deviousness", C:"intelligence", D:"secrecy" }, answer:"A" },
  { number: 705, word: "HACKNEYED", choices: { A:"boring", B:"overused", C:"predictable", D:"outdated" }, answer:"B" },
  { number: 706, word: "HAPLESS", choices: { A:"unlucky", B:"miserable", C:"awkward", D:"powerless" }, answer:"A" },
  { number: 707, word: "HEGEMONY", choices: { A:"authority", B:"control", C:"dominance", D:"tyranny" }, answer:"C" },
  { number: 708, word: "HUBRIS", choices: { A:"self-importance", B:"arrogance", C:"confidence", D:"vanity" }, answer:"B" },

  // H words (12 questions: 709-720)
  { number: 709, word: "HACKNEYED", choices: { A:"clichéd", B:"repetitive", C:"common", D:"predictable" }, answer:"A" },
  { number: 710, word: "HAPLESS", choices: { A:"incapable", B:"unlucky", C:"unhappy", D:"clumsy" }, answer:"B" },
  { number: 711, word: "HARBINGER", choices: { A:"a warning", B:"a prediction", C:"a messenger", D:"a herald" }, answer:"D" },
  { number: 712, word: "HAUGHTY", choices: { A:"conceited", B:"arrogant", C:"snobbish", D:"bossy" }, answer:"B" },
  { number: 713, word: "HEDONISTIC", choices: { A:"selfish", B:"materialistic", C:"pleasure-seeking", D:"lazy" }, answer:"C" },
  { number: 714, word: "HERETICAL", choices: { A:"unorthodox", B:"blasphemous", C:"radical", D:"subversive" }, answer:"A" },
  { number: 715, word: "HIERARCHY", choices: { A:"a government", B:"a tradition", C:"a ranking", D:"an organization" }, answer:"C" },
  { number: 716, word: "HISTRIONIC", choices: { A:"emotional", B:"theatrical", C:"childish", D:"loud" }, answer:"B" },
  { number: 717, word: "HOMOGENEOUS", choices: { A:"pure", B:"simple", C:"uniform", D:"bland" }, answer:"C" },
  { number: 718, word: "HYPERBOLE", choices: { A:"a fiction", B:"an exaggeration", C:"a deception", D:"a figure of speech" }, answer:"B" },
  { number: 719, word: "HYPOCRISY", choices: { A:"deceit", B:"insincerity", C:"immorality", D:"a lie" }, answer:"B" },
  { number: 720, word: "HYPOTHETICAL", choices: { A:"a guess", B:"theoretical", C:"an opinion", D:"an idea" }, answer:"B" },

  // I words (12 questions: 721-732)
  { number: 721, word: "ICONOCLAST", choices: { A:"a revolutionary", B:"a rebel", C:"an atheist", D:"a troublemaker" }, answer:"B" },
  { number: 722, word: "IDIOSYNCRASY", choices: { A:"a habit", B:"a behavior", C:"a quirk", D:"a flaw" }, answer:"C" },
  { number: 723, word: "IGNOBLE", choices: { A:"dishonorable", B:"cowardly", C:"selfish", D:"common" }, answer:"A" },
  { number: 724, word: "ILLICIT", choices: { A:"illegal", B:"secretive", C:"immoral", D:"improper" }, answer:"A" },
  { number: 725, word: "IMMUTABLE", choices: { A:"ancient", B:"unchangeable", C:"agreed-upon", D:"forceful" }, answer:"B" },
  { number: 726, word: "IMPASSIVE", choices: { A:"uninterested", B:"calm", C:"expressionless", D:"aloof" }, answer:"C" },
  { number: 727, word: "IMPECUNIOUS", choices: { A:"unfortunate", B:"unsuccessful", C:"poor", D:"thrifty" }, answer:"C" },
  { number: 728, word: "IMPERIOUS", choices: { A:"forceful", B:"domineering", C:"royal", D:"demanding" }, answer:"B" },
  { number: 729, word: "IMPERTURBABLE", choices: { A:"calm", B:"patient", C:"steadfast", D:"quiet" }, answer:"A" },
  { number: 730, word: "IMPETUOUS", choices: { A:"impulsive", B:"reckless", C:"energetic", D:"angry" }, answer:"A" },
  { number: 731, word: "IMPLACABLE", choices: { A:"stubborn", B:"relentless", C:"hostile", D:"determined" }, answer:"B" },
  { number: 732, word: "IMPLICIT", choices: { A:"indirect", B:"secret", C:"implied", D:"assumed" }, answer:"C" },

  // J words (6 questions: 733-738)
  { number: 733, word: "JUDICIOUS", choices: { A:"thoughtful", B:"wise", C:"cautious", D:"impartial" }, answer:"B" },
  { number: 734, word: "JADED", choices: { A:"bored", B:"tired", C:"cynical", D:"pessimistic" }, answer:"C" },
  { number: 735, word: "JARGON", choices: { A:"gossip", B:"terminology", C:"dialect", D:"abbreviations" }, answer:"B" },
  { number: 736, word: "JINGOISTIC", choices: { A:"aggressive", B:"nationalistic", C:"prejudiced", D:"proud" }, answer:"B" },
  { number: 737, word: "JOCUND", choices: { A:"cheerful", B:"humorous", C:"optimistic", D:"amusing" }, answer:"A" },
  { number: 738, word: "JUDICIOUS", choices: { A:"honest", B:"sensible", C:"lawful", D:"official" }, answer:"B" },

  // K words (4 questions: 739-742)
  { number: 739, word: "KINETIC", choices: { A:"powerful", B:"mechanical", C:"active", D:"fast" }, answer:"C" },
  { number: 740, word: "KNAVE", choices: { A:"a thief", B:"a scoundrel", C:"a trickster", D:"a liar" }, answer:"B" },
  { number: 741, word: "KNOTTY", choices: { A:"frustrating", B:"complex", C:"confusing", D:"unsolvable" }, answer:"B" },
  { number: 742, word: "KUDOS", choices: { A:"appreciation", B:"congratulations", C:"praise", D:"a bonus" }, answer:"C" },

  // L words (12 questions: 743-754)
  { number: 743, word: "LACONIC", choices: { A:"brief", B:"rude", C:"informal", D:"short" }, answer:"A" },
  { number: 744, word: "LAMENT", choices: { A:"to cry", B:"to mourn", C:"to regret", D:"to protest" }, answer:"B" },
  { number: 745, word: "LANGUID", choices: { A:"lazy", B:"weak", C:"relaxed", D:"slow" }, answer:"B" },
  { number: 746, word: "LATENT", choices: { A:"hidden", B:"secret", C:"inactive", D:"forgotten" }, answer:"A" },
  { number: 747, word: "LAUDABLE", choices: { A:"humble", B:"praiseworthy", C:"noble", D:"generous" }, answer:"B" },
  { number: 748, word: "LICENTIOUS", choices: { A:"immoral", B:"illegal", C:"selfish", D:"decadent" }, answer:"A" },
  { number: 749, word: "LIMN", choices: { A:"to illustrate", B:"to sketch", C:"to copy", D:"to describe" }, answer:"D" },
  { number: 750, word: "LITHE", choices: { A:"graceful", B:"flexible", C:"athletic", D:"slender" }, answer:"B" },
  { number: 751, word: "LOQUACIOUS", choices: { A:"rambling", B:"talkative", C:"outgoing", D:"boastful" }, answer:"B" },
  { number: 752, word: "LUGUBRIOUS", choices: { A:"serious", B:"mournful", C:"depressing", D:"somber" }, answer:"B" },
  { number: 753, word: "LUMINOUS", choices: { A:"gleaming", B:"shining", C:"bright", D:"vivid" }, answer:"C" },
  { number: 754, word: "LURID", choices: { A:"shocking", B:"graphic", C:"inappropriate", D:"disturbing" }, answer:"A" },

  // M words (12 questions: 755-766)
  { number: 755, word: "MALADROIT", choices: { A:"clumsy", B:"impolite", C:"thoughtless", D:"inexperienced" }, answer:"A" },
  { number: 756, word: "MALEVOLENT", choices: { A:"hateful", B:"hostile", C:"vicious", D:"vengeful" }, answer:"B" },
  { number: 757, word: "MALLEABLE", choices: { A:"bendable", B:"yielding", C:"pliable", D:"changeable" }, answer:"C" },
  { number: 758, word: "MAVERICK", choices: { A:"a genius", B:"an adventurer", C:"a nonconformist", D:"an agitator" }, answer:"C" },
  { number: 759, word: "MELANCHOLY", choices: { A:"sad", B:"nostalgic", C:"pensive", D:"somber" }, answer:"A" },
  { number: 760, word: "MENDACIOUS", choices: { A:"clever", B:"dishonest", C:"deceptive", D:"sly" }, answer:"B" },
  { number: 761, word: "MERCURIAL", choices: { A:"unpredictable", B:"rapid", C:"emotional", D:"dramatic" }, answer:"A" },
  { number: 762, word: "MERITORIOUS", choices: { A:"worthy", B:"excellent", C:"exceptional", D:"honorable" }, answer:"A" },
  { number: 763, word: "METAMORPHOSIS", choices: { A:"a maturation", B:"a transformation", C:"a variation", D:"an evolution" }, answer:"B" },
  { number: 764, word: "METICULOUS", choices: { A:"cautious", B:"organized", C:"perfectionistic", D:"thorough" }, answer:"D" },
  { number: 765, word: "MIRE", choices: { A:"to complicate", B:"to entangle", C:"to dirty", D:"to slow down" }, answer:"B" },
  { number: 766, word: "MITIGATE", choices: { A:"to lessen", B:"to solve", C:"to ease", D:"to postpone" }, answer:"A" },

  // N words (10 questions: 767-776)
  { number: 767, word: "NEBULOUS", choices: { A:"hazy", B:"confusing", C:"vague", D:"hypothetical" }, answer:"C" },
  { number: 768, word: "NEFARIOUS", choices: { A:"wicked", B:"illegal", C:"secretive", D:"dangerous" }, answer:"A" },
  { number: 769, word: "NEOPHYTE", choices: { A:"a convert", B:"a beginner", C:"an assistant", D:"an apprentice" }, answer:"B" },
  { number: 770, word: "NONCHALANT", choices: { A:"uninterested", B:"casual", C:"unfriendly", D:"tired" }, answer:"B" },
  { number: 771, word: "NOSTALGIC", choices: { A:"homesick", B:"sentimental", C:"melancholy", D:"regretful" }, answer:"B" },
  { number: 772, word: "NOTORIOUS", choices: { A:"criminal", B:"infamous", C:"unpopular", D:"dangerous" }, answer:"B" },
  { number: 773, word: "NOVICE", choices: { A:"a trainee", B:"a beginner", C:"a player", D:"an enthusiast" }, answer:"B" },
  { number: 774, word: "NUANCE", choices: { A:"a detail", B:"a subtlety", C:"an implication", D:"a suggestion" }, answer:"B" },
  { number: 775, word: "NUMINOUS", choices: { A:"spiritual", B:"ancient", C:"mysterious", D:"powerful" }, answer:"A" },
  { number: 776, word: "NURTURE", choices: { A:"to protect", B:"to cultivate", C:"to discipline", D:"to teach" }, answer:"B" },

  // O words (10 questions: 777-786)
  { number: 777, word: "OBDURATE", choices: { A:"angry", B:"stubborn", C:"hostile", D:"unreasonable" }, answer:"B" },
  { number: 778, word: "OBFUSCATE", choices: { A:"to confuse", B:"to complicate", C:"to lie", D:"to distract" }, answer:"A" },
  { number: 779, word: "OBSEQUIOUS", choices: { A:"servile", B:"polite", C:"enthusiastic", D:"official" }, answer:"A" },
  { number: 780, word: "OBTUSE", choices: { A:"awkward", B:"unintelligent", C:"dull", D:"ignorant" }, answer:"C" },
  { number: 781, word: "OMINOUS", choices: { A:"frightening", B:"dark", C:"threatening", D:"serious" }, answer:"C" },
  { number: 782, word: "ONEROUS", choices: { A:"unpleasant", B:"burdensome", C:"tedious", D:"challenging" }, answer:"B" },
  { number: 783, word: "OPAQUE", choices: { A:"unclear", B:"solid", C:"dark", D:"thick" }, answer:"A" },
  { number: 784, word: "OPPORTUNE", choices: { A:"ideal", B:"timely", C:"fortunate", D:"helpful" }, answer:"B" },
  { number: 785, word: "ORTHODOX", choices: { A:"religious", B:"conventional", C:"old-fashioned", D:"strict" }, answer:"B" },
  { number: 786, word: "OSTENSIBLE", choices: { A:"apparent", B:"official", C:"supposed", D:"unproven" }, answer:"A" },

  // P words (18 questions: 787-804)
  { number: 787, word: "PALPABLE", choices: { A:"tangible", B:"obvious", C:"powerful", D:"unsettling" }, answer:"A" },
  { number: 788, word: "PANACEA", choices: { A:"a medicine", B:"a solution", C:"a cure-all", D:"an invention" }, answer:"C" },
  { number: 789, word: "PARADIGM", choices: { A:"a principle", B:"a model", C:"a theory", D:"a rule" }, answer:"B" },
  { number: 790, word: "PARADOX", choices: { A:"a mystery", B:"a contradiction", C:"an illusion", D:"a difficult problem" }, answer:"B" },
  { number: 791, word: "PARAGON", choices: { A:"a champion", B:"a hero", C:"a model", D:"a leader" }, answer:"C" },
  { number: 792, word: "PARIAH", choices: { A:"an outcast", B:"a criminal", C:"an exile", D:"a beggar" }, answer:"A" },
  { number: 793, word: "PAROCHIAL", choices: { A:"narrow", B:"regional", C:"old-fashioned", D:"religious" }, answer:"A" },
  { number: 794, word: "PARSIMONIOUS", choices: { A:"greedy", B:"stingy", C:"selfish", D:"careful" }, answer:"B" },
  { number: 795, word: "PARTISAN", choices: { A:"biased", B:"loyal", C:"political", D:"opinionated" }, answer:"A" },
  { number: 796, word: "PATHOS", choices: { A:"emotion", B:"sadness", C:"suffering", D:"drama" }, answer:"A" },
  { number: 797, word: "PAUCITY", choices: { A:"a need", B:"a demand", C:"an absence", D:"a scarcity" }, answer:"D" },
  { number: 798, word: "PEDANTIC", choices: { A:"boring", B:"intellectual", C:"academic", D:"pompous" }, answer:"D" },
  { number: 799, word: "PENCHANT", choices: { A:"a skill", B:"a liking", C:"a habit", D:"a desire" }, answer:"B" },
  { number: 800, word: "PENITENT", choices: { A:"remorseful", B:"apologetic", C:"humble", D:"ashamed" }, answer:"A" },
  { number: 801, word: "PENSIVE", choices: { A:"thoughtful", B:"sad", C:"dreamy", D:"quiet" }, answer:"A" },
  { number: 802, word: "PENURY", choices: { A:"poverty", B:"despair", C:"hunger", D:"misery" }, answer:"A" },
  { number: 803, word: "PERFIDIOUS", choices: { A:"disloyal", B:"sneaky", C:"treacherous", D:"untrustworthy" }, answer:"C" },
  { number: 804, word: "PERFUNCTORY", choices: { A:"cursory", B:"uninterested", C:"lazy", D:"thoughtless" }, answer:"A" },

  // Q words (6 questions: 805-810)
  { number: 805, word: "QUAGMIRE", choices: { A:"a dilemma", B:"a problem", C:"a predicament", D:"a swamp" }, answer:"C" },
  { number: 806, word: "QUANDARY", choices: { A:"a choice", B:"a dilemma", C:"an issue", D:"a mystery" }, answer:"B" },
  { number: 807, word: "QUARANTINE", choices: { A:"to seclude", B:"to isolate", C:"to confine", D:"to imprison" }, answer:"B" },
  { number: 808, word: "QUASH", choices: { A:"to cancel", B:"to suppress", C:"to reject", D:"to defeat" }, answer:"B" },
  { number: 809, word: "QUERULOUS", choices: { A:"complaining", B:"annoying", C:"unhappy", D:"impatient" }, answer:"A" },
  { number: 810, word: "QUIXOTIC", choices: { A:"idealistic", B:"romantic", C:"chivalrous", D:"imaginative" }, answer:"A" },

  // R words (12 questions: 811-822)
  { number: 811, word: "RANCOROUS", choices: { A:"bitter", B:"angry", C:"hateful", D:"negative" }, answer:"A" },
  { number: 812, word: "RAPACIOUS", choices: { A:"greedy", B:"violent", C:"aggressive", D:"demanding" }, answer:"A" },
  { number: 813, word: "RAZE", choices: { A:"to topple", B:"to ruin", C:"to demolish", D:"to break down" }, answer:"C" },
  { number: 814, word: "RECALCITRANT", choices: { A:"disagreeable", B:"defiant", C:"rebellious", D:"unruly" }, answer:"B" },
  { number: 815, word: "RECAPITULATE", choices: { A:"to summarize", B:"to repeat", C:"to review", D:"to emphasize" }, answer:"A" },
  { number: 816, word: "RECLUSIVE", choices: { A:"antisocial", B:"sequestered", C:"solitary", D:"lonely" }, answer:"C" },
  { number: 817, word: "REDOLENT", choices: { A:"reminiscent", B:"fragrant", C:"memorable", D:"perfumed" }, answer:"B" },
  { number: 818, word: "REDRESS", choices: { A:"to avenge", B:"to fix", C:"to remedy", D:"to resolve" }, answer:"C" },
  { number: 819, word: "REDUNDANT", choices: { A:"unhelpful", B:"superfluous", C:"excessive", D:"boring" }, answer:"B" },
  { number: 820, word: "REFUTE", choices: { A:"to deny", B:"to disprove", C:"to argue against", D:"to reject" }, answer:"B" },
  { number: 821, word: "RELEGATE", choices: { A:"to demote", B:"to remove", C:"to assign", D:"to transfer" }, answer:"A" },
  { number: 822, word: "RELINQUISH", choices: { A:"to sacrifice", B:"to lose", C:"to give up", D:"to release" }, answer:"C" },

  // S words (18 questions: 823-840)
  { number: 823, word: "SAGACITY", choices: { A:"intelligence", B:"wisdom", C:"experience", D:"knowledge" }, answer:"B" },
  { number: 824, word: "SALIENT", choices: { A:"noteworthy", B:"prominent", C:"essential", D:"obvious" }, answer:"B" },
  { number: 825, word: "SANGUINE", choices: { A:"enthusiastic", B:"optimistic", C:"cheerful", D:"positive" }, answer:"B" },
  { number: 826, word: "SARDONIC", choices: { A:"mocking", B:"insulting", C:"cynical", D:"disrespectful" }, answer:"A" },
  { number: 827, word: "SAVANT", choices: { A:"a prodigy", B:"an expert", C:"a scholar", D:"a philosopher" }, answer:"B" },
  { number: 828, word: "SCRUPULOUS", choices: { A:"moral", B:"precise", C:"honorable", D:"ethical" }, answer:"D" },
  { number: 829, word: "SECTARIAN", choices: { A:"prejudiced", B:"narrow", C:"religious", D:"divisive" }, answer:"B" },
  { number: 830, word: "SEDITIOUS", choices: { A:"rebellious", B:"treasonous", C:"conspiring", D:"disloyal" }, answer:"A" },
  { number: 831, word: "SEMINAL", choices: { A:"influential", B:"original", C:"fundamental", D:"creative" }, answer:"A" },
  { number: 832, word: "SENSUOUS", choices: { A:"pleasurable", B:"appealing", C:"tactile", D:"aesthetic" }, answer:"A" },
  { number: 833, word: "SERENDIPITY", choices: { A:"fate", B:"chance", C:"a fluke", D:"an accident" }, answer:"B" },
  { number: 834, word: "SOBRIETY", choices: { A:"seriousness", B:"moderation", C:"formality", D:"abstinence" }, answer:"A" },
  { number: 835, word: "SOLICITOUS", choices: { A:"concerned", B:"polite", C:"anxious", D:"helpful" }, answer:"A" },
  { number: 836, word: "SOMNOLENT", choices: { A:"dreamy", B:"sleepy", C:"peaceful", D:"lethargic" }, answer:"B" },
  { number: 837, word: "SPECIOUS", choices: { A:"misleading", B:"unconvincing", C:"tricky", D:"illogical" }, answer:"A" },
  { number: 838, word: "SPURIOUS", choices: { A:"fake", B:"fraudulent", C:"imitation", D:"invalid" }, answer:"A" },
  { number: 839, word: "STOIC", choices: { A:"unemotional", B:"calm", C:"resolute", D:"indifferent" }, answer:"A" },
  { number: 840, word: "STRIDENT", choices: { A:"loud", B:"harsh", C:"forceful", D:"unpleasant" }, answer:"B" },

  // T words (12 questions: 841-852)
  { number: 841, word: "TACIT", choices: { A:"assumed", B:"implied", C:"subtle", D:"secret" }, answer:"B" },
  { number: 842, word: "TANGENTIAL", choices: { A:"irrelevant", B:"unrelated", C:"peripheral", D:"minor" }, answer:"C" },
  { number: 843, word: "TAUTOLOGY", choices: { A:"a complex phrase", B:"redundancy", C:"a grammatical error", D:"a false statement" }, answer:"B" },
  { number: 844, word: "TEMERITY", choices: { A:"bravery", B:"confidence", C:"audacity", D:"impudence" }, answer:"C" },
  { number: 845, word: "TEMPERANCE", choices: { A:"moderation", B:"caution", C:"simplicity", D:"sobriety" }, answer:"A" },
  { number: 846, word: "TENACIOUS", choices: { A:"firm", B:"persistent", C:"strong", D:"courageous" }, answer:"B" },
  { number: 847, word: "TENET", choices: { A:"a goal", B:"a principle", C:"a law", D:"a fact" }, answer:"B" },
  { number: 848, word: "TEPID", choices: { A:"lukewarm", B:"dull", C:"indifferent", D:"mild" }, answer:"A" },
  { number: 849, word: "TERSE", choices: { A:"short", B:"direct", C:"brief", D:"impolite" }, answer:"C" },
  { number: 850, word: "TIMOROUS", choices: { A:"shy", B:"nervous", C:"timid", D:"hesitant" }, answer:"C" },
  { number: 851, word: "TIRADE", choices: { A:"an outburst", B:"a sermon", C:"a denunciation", D:"an argument" }, answer:"A" },
  { number: 852, word: "TORPOR", choices: { A:"exhaustion", B:"lethargy", C:"boredom", D:"inactivity" }, answer:"B" },

  // U words (8 questions: 853-860)
  { number: 853, word: "UBIQUITOUS", choices: { A:"popular", B:"omnipresent", C:"fashionable", D:"widespread" }, answer:"B" },
  { number: 854, word: "ULTERIOR", choices: { A:"hidden", B:"malicious", C:"secondary", D:"selfish" }, answer:"A" },
  { number: 855, word: "UMBRAGE", choices: { A:"offense", B:"annoyance", C:"suspicion", D:"resentment" }, answer:"A" },
  { number: 856, word: "UNASSUMING", choices: { A:"modest", B:"shy", C:"plain", D:"quiet" }, answer:"A" },
  { number: 857, word: "UNCTUOUS", choices: { A:"oily", B:"insincere", C:"flattering", D:"obsequious" }, answer:"A" },
  { number: 858, word: "UNDULATE", choices: { A:"to wave", B:"to sway", C:"to swing", D:"to vibrate" }, answer:"A" },
  { number: 859, word: "UNEQUIVOCAL", choices: { A:"clear", B:"certain", C:"absolute", D:"emphatic" }, answer:"A" },
  { number: 860, word: "UNSCRUPULOUS", choices: { A:"dishonest", B:"unethical", C:"corrupt", D:"criminal" }, answer:"A" },

  // V words (12 questions: 861-872)
  { number: 861, word: "VACILLATE", choices: { A:"to waver", B:"to delay", C:"to be indecisive", D:"to change" }, answer:"A" },
  { number: 862, word: "VAGARY", choices: { A:"a whim", B:"an inconsistency", C:"a journey", D:"an exception" }, answer:"A" },
  { number: 863, word: "VAPID", choices: { A:"dull", B:"shallow", C:"lifeless", D:"boring" }, answer:"A" },
  { number: 864, word: "VARIEGATED", choices: { A:"varied", B:"mismatched", C:"colorful", D:"complex" }, answer:"A" },
  { number: 865, word: "VEHEMENT", choices: { A:"intense", B:"angry", C:"passionate", D:"loud" }, answer:"A" },
  { number: 866, word: "VENEER", choices: { A:"a facade", B:"a disguise", C:"a covering", D:"a lie" }, answer:"A" },
  { number: 867, word: "VERACIOUS", choices: { A:"truthful", B:"reliable", C:"accurate", D:"sincere" }, answer:"A" },
  { number: 868, word: "VERBATIM", choices: { A:"word-for-word", B:"completely", C:"accurately", D:"precisely" }, answer:"A" },
  { number: 869, word: "VERBOSE", choices: { A:"wordy", B:"descriptive", C:"circuitous", D:"boring" }, answer:"A" },
  { number: 870, word: "VERISIMILITUDE", choices: { A:"realism", B:"creativity", C:"accuracy", D:"imagination" }, answer:"A" },
  { number: 871, word: "VERNACULAR", choices: { A:"dialect", B:"local custom", C:"foreign language", D:"formal speech" }, answer:"A" },
  { number: 872, word: "VICARIOUS", choices: { A:"indirect", B:"sympathetic", C:"shared", D:"emotional" }, answer:"A" },

  // W words (8 questions: 873-880)
  { number: 873, word: "WANE", choices: { A:"to decrease", B:"to disappear", C:"to shrink", D:"to fail" }, answer:"A" },
  { number: 874, word: "WANTON", choices: { A:"reckless", B:"unjustified", C:"deliberate", D:"cruel" }, answer:"A" },
  { number: 875, word: "WIZENED", choices: { A:"shriveled", B:"ancient", C:"magical", D:"wise" }, answer:"A" },
  { number: 876, word: "WRATH", choices: { A:"anger", B:"violence", C:"resentment", D:"hatred" }, answer:"A" },
  { number: 877, word: "WROUGHT", choices: { A:"formed", B:"decorated", C:"labored over", D:"built" }, answer:"A" },
  { number: 878, word: "WILY", choices: { A:"cunning", B:"intelligent", C:"tricky", D:"deceptive" }, answer:"A" },
  { number: 879, word: "WINSOME", choices: { A:"charming", B:"beautiful", C:"delicate", D:"cheerful" }, answer:"A" },
  { number: 880, word: "WREAK", choices: { A:"to inflict", B:"to deliver", C:"to create", D:"to unleash" }, answer:"A" },

  // X, Y, Z words (20 questions: 881-900, padding to reach exactly 300)
  { number: 881, word: "XENOPHOBIC", choices: { A:"ignorant", B:"intolerant", C:"paranoid", D:"hostile" }, answer:"B" },
  { number: 882, word: "YOKE", choices: { A:"a burden", B:"a harness", C:"a prison", D:"a connection" }, answer:"A" },
  { number: 883, word: "ZEALOT", choices: { A:"a fanatic", B:"a believer", C:"a protester", D:"a follower" }, answer:"A" },
  { number: 884, word: "ZEPHYR", choices: { A:"a breeze", B:"a whisper", C:"a spirit", D:"a current" }, answer:"A" },
  
  // Additional padding questions to reach 900
  { number: 885, word: "ABERRATION", choices: { A:"a mistake", B:"a deviation", C:"an exception", D:"an error" }, answer:"B" },
  { number: 886, word: "ADROIT", choices: { A:"skillful", B:"quick", C:"clever", D:"graceful" }, answer:"A" },
  { number: 887, word: "BELLICOSE", choices: { A:"aggressive", B:"argumentative", C:"warlike", D:"violent" }, answer:"C" },
  { number: 888, word: "CALUMNY", choices: { A:"an insult", B:"slander", C:"a lie", D:"an accusation" }, answer:"B" },
  { number: 889, word: "EBULLIENT", choices: { A:"joyful", B:"enthusiastic", C:"excited", D:"lively" }, answer:"B" },
  { number: 890, word: "FALLACIOUS", choices: { A:"deceptive", B:"incorrect", C:"false", D:"invalid" }, answer:"C" },
  { number: 891, word: "GREGARIOUS", choices: { A:"talkative", B:"amiable", C:"sociable", D:"popular" }, answer:"C" },
  { number: 892, word: "ICONOCLAST", choices: { A:"a critic", B:"an artist", C:"rebel", D:"a skeptic" }, answer:"C" },
  { number: 893, word: "MALLEABLE", choices: { A:"changeable", B:"soft", C:"weak", D:"pliable" }, answer:"D" },
  { number: 894, word: "NEFARIOUS", choices: { A:"secretive", B:"wicked", C:"devious", D:"illegal" }, answer:"B" },
  { number: 895, word: "OBSEQUIOUS", choices: { A:"servile", B:"flattering", C:"attentive", D:"eager" }, answer:"A" },
  { number: 896, word: "PARAGON", choices: { A:"a hero", B:"a champion", C:"a model", D:"an expert" }, answer:"C" },
  { number: 897, word: "QUIXOTIC", choices: { A:"heroic", B:"idealistic", C:"romantic", D:"dreamy" }, answer:"B" },
  { number: 898, word: "SAGACITY", choices: { A:"insight", B:"experience", C:"wisdom", D:"intelligence" }, answer:"C" },
  { number: 899, word: "TIRADE", choices: { A:"an outburst", B:"a complaint", C:"a criticism", D:"a long speech" }, answer:"A" },
  { number: 900, word: "VEHEMENT", choices: { A:"sudden", B:"intense", C:"loud", D:"angry" }, answer:"B" },
];

// Optional sentinel
window.__VOCAB_ENHANCED2_LOADED__ = true;

