// isee_vocab_enhanced2.js
// Enhanced Option 2: 300 advanced-level vocabulary words
// These words are more challenging than the original 300 and Enhanced Option 1
// None of these words appear in the original list or Enhanced Option 1
// Words distributed proportionally across all letters A-Z

window.DEFINITIONS_ENHANCED2 = {
  // A words (12)
  ABATE: "reduce, diminish, subside — Example: The storm's fury began to abate by midnight.",
  ABERRATION: "deviation, anomaly, irregularity — Example: The test results were an aberration from the usual pattern.",
  ABHOR: "detest, loathe, despise — Example: She abhors violence in any form.",
  ABJURE: "renounce, reject, recant — Example: The defendant agreed to abjure his criminal activities.",
  ABSTEMIOUS: "moderate, temperate, restrained — Example: His abstemious lifestyle promoted longevity.",
  ACCRUE: "accumulate, amass, increase — Example: Interest will accrue on the account monthly.",
  ACERBIC: "harsh, bitter, caustic — Example: His acerbic wit often offended sensitive colleagues.",
  ACQUIESCE: "consent, comply, submit — Example: She reluctantly acquiesced to their demands.",
  ACRIMONIOUS: "bitter, hostile, caustic — Example: The acrimonious divorce lasted two years.",
  ADROIT: "skillful, dexterous, clever — Example: The diplomat's adroit handling prevented conflict.",
  AESTHETIC: "artistic, beautiful, tasteful — Example: The museum's aesthetic appeal draws visitors worldwide.",
  AFFINITY: "attraction, liking, kinship — Example: She has a natural affinity for mathematics.",
  
  // B words (12)
  BELLICOSE: "warlike, aggressive, hostile — Example: The bellicose rhetoric escalated tensions between nations.",
  BENEFACTOR: "patron, donor, supporter — Example: The anonymous benefactor funded the scholarship program.",
  BENIGN: "harmless, gentle, favorable — Example: The tumor proved to be benign after testing.",
  BERATE: "scold, criticize, reprimand — Example: The coach continued to berate the players for careless errors.",
  BOMBASTIC: "pompous, grandiose, inflated — Example: His bombastic speech failed to convince the audience.",
  BOON: "benefit, blessing, advantage — Example: The new highway proved a boon to local commerce.",
  BUCOLIC: "rural, pastoral, rustic — Example: The bucolic landscape inspired many artists.",
  BULBOUS: "swollen, rounded, protruding — Example: The plant has a distinctive bulbous root.",
  BUREAUCRATIC: "administrative, official, procedural — Example: The bureaucratic process delayed the project.",
  BURGEON: "flourish, grow, expand — Example: Technology companies burgeon in this region.",
  BURNISH: "polish, shine, refine — Example: He worked to burnish his reputation after the scandal.",
  BUTTRESS: "support, strengthen, reinforce — Example: New evidence will buttress the prosecutor's case.",
  
  // C words (18)
  CACOPHONY: "discord, noise, dissonance — Example: The cacophony of city traffic made concentration difficult.",
  CAJOLE: "coax, persuade, wheedle — Example: She tried to cajole him into attending the event.",
  CALLOUS: "insensitive, hardened, unfeeling — Example: His callous disregard for others was troubling.",
  CALUMNY: "slander, defamation, libel — Example: The politician sued for calumny after false accusations.",
  CANDID: "frank, honest, straightforward — Example: The candidate gave a candid assessment of challenges ahead.",
  CANTANKEROUS: "quarrelsome, irritable, grumpy — Example: The cantankerous neighbor complained about everything.",
  CAPITULATE: "surrender, yield, submit — Example: The army refused to capitulate despite overwhelming odds.",
  CAPRICIOUS: "unpredictable, fickle, whimsical — Example: The capricious weather ruined their outdoor plans.",
  CASTIGATE: "criticize, rebuke, reprimand — Example: The editorial castigated officials for corruption.",
  CATALYST: "agent, stimulus, spark — Example: The crisis became a catalyst for reform.",
  CAUSTIC: "corrosive, sarcastic, biting — Example: Her caustic comments alienated potential allies.",
  CHARLATAN: "fraud, impostor, fake — Example: The supposed doctor was exposed as a charlatan.",
  CHICANERY: "deception, trickery, fraud — Example: The scandal revealed widespread financial chicanery.",
  CIRCUMSPECT: "cautious, prudent, wary — Example: The lawyer was circumspect in her public statements.",
  CLANDESTINE: "secret, covert, hidden — Example: They held clandestine meetings to avoid detection.",
  COALESCE: "unite, merge, combine — Example: The various factions coalesced into a single movement.",
  COGENT: "convincing, compelling, persuasive — Example: She presented a cogent argument for policy change.",
  COLLOQUIAL: "informal, conversational, vernacular — Example: The author uses colloquial language to engage readers.",
  
  // D words (18)
  DAUNT: "intimidate, discourage, dismay — Example: The magnitude of the project did not daunt her.",
  DEBUNK: "disprove, refute, discredit — Example: Scientists worked to debunk the popular myth.",
  DECORUM: "propriety, etiquette, dignity — Example: The ceremony was conducted with proper decorum.",
  DEFAME: "slander, malign, vilify — Example: The article attempted to defame the candidate's character.",
  DEFERENCE: "respect, regard, courtesy — Example: She showed deference to her elders at the gathering.",
  DEIGN: "condescend, stoop, lower oneself — Example: The celebrity did not deign to answer reporters' questions.",
  DELETERIOUS: "harmful, damaging, injurious — Example: Smoking has deleterious effects on health.",
  DELINEATE: "describe, outline, portray — Example: The report clearly delineates the boundaries of responsibility.",
  DELUGE: "flood, inundation, torrent — Example: A deluge of complaints followed the announcement.",
  DEMAGOGUE: "agitator, rabble-rouser, instigator — Example: The demagogue exploited public fears for political gain.",
  DEMEANOR: "behavior, conduct, bearing — Example: Her calm demeanor reassured the nervous students.",
  DEMURE: "modest, reserved, shy — Example: Despite her success, she maintained a demure manner.",
  DENIGRATE: "disparage, belittle, criticize — Example: It's wrong to denigrate others' achievements.",
  DERIDE: "mock, ridicule, scoff — Example: Critics derided the plan as impractical.",
  DESPOT: "tyrant, dictator, autocrat — Example: The despot ruled with an iron fist for decades.",
  DESULTORY: "random, aimless, disconnected — Example: His desultory approach to studying hindered progress.",
  DIATRIBE: "tirade, rant, denunciation — Example: The senator launched into a diatribe against opponents.",
  DICHOTOMY: "division, split, contrast — Example: There's a dichotomy between theory and practice.",
  
  // E words (18)
  EBULLIENT: "enthusiastic, exuberant, lively — Example: The team was ebullient after the championship victory.",
  ECCENTRIC: "unconventional, peculiar, quirky — Example: The eccentric inventor created unusual gadgets.",
  ECLECTIC: "diverse, varied, mixed — Example: The restaurant offers an eclectic menu.",
  EFFACE: "erase, obliterate, remove — Example: Time has effaced many ancient inscriptions.",
  EFFICACY: "effectiveness, efficiency, potency — Example: The study confirmed the drug's efficacy.",
  EFFRONTERY: "audacity, impudence, nerve — Example: She had the effrontery to demand a refund.",
  EGALITARIAN: "equal, democratic, fair — Example: The organization promotes egalitarian principles.",
  EGREGIOUS: "outrageous, shocking, flagrant — Example: The company's egregious misconduct led to lawsuits.",
  ELABORATE: "detailed, intricate, complex — Example: The architect presented an elaborate design.",
  ELEGY: "lament, dirge, tribute — Example: The poet wrote an elegy for the fallen soldiers.",
  ELOQUENT: "articulate, fluent, expressive — Example: Her eloquent speech moved the audience to tears.",
  ELUCIDATE: "clarify, explain, illuminate — Example: The professor will elucidate the complex theorem.",
  ELUSIVE: "evasive, intangible, fleeting — Example: Success remained elusive despite their efforts.",
  EMBELLISH: "decorate, ornament, enhance — Example: He tends to embellish stories for dramatic effect.",
  EMBROIL: "involve, entangle, implicate — Example: The scandal embroiled several prominent officials.",
  EMULATE: "imitate, copy, mirror — Example: Young artists often emulate their mentors.",
  ENDEMIC: "native, indigenous, local — Example: Malaria is endemic to tropical regions.",
  ENGENDER: "cause, produce, generate — Example: The policy change will engender public debate.",
  
  // F words (18)
  FACETIOUS: "joking, flippant, frivolous — Example: His facetious remarks were inappropriate for the occasion.",
  FALLACIOUS: "false, erroneous, misleading — Example: The argument rests on fallacious assumptions.",
  FASTIDIOUS: "meticulous, particular, demanding — Example: She is fastidious about cleanliness.",
  FATUOUS: "foolish, silly, inane — Example: The fatuous comment revealed his ignorance.",
  FAWN: "grovel, flatter, kowtow — Example: He refused to fawn over powerful executives.",
  FEALTY: "loyalty, allegiance, devotion — Example: Knights pledged fealty to their lord.",
  FECUND: "fertile, productive, fruitful — Example: The valley's fecund soil yields abundant crops.",
  FERVOR: "passion, zeal, intensity — Example: She spoke with fervor about environmental protection.",
  FESTER: "rot, decay, worsen — Example: Left untreated, the wound began to fester.",
  FIDELITY: "loyalty, faithfulness, devotion — Example: He showed fidelity to his principles throughout.",
  FLACCID: "limp, soft, weak — Example: The flaccid muscles indicated lack of exercise.",
  FLAGITIOUS: "wicked, villainous, heinous — Example: The judge condemned the flagitious crime.",
  FLEDGLING: "beginner, novice, newcomer — Example: The fledgling company struggled in its first year.",
  FOMENT: "incite, instigate, provoke — Example: Propaganda was used to foment rebellion.",
  FORMIDABLE: "intimidating, daunting, impressive — Example: The team faced a formidable opponent.",
  FORTUITOUS: "lucky, fortunate, accidental — Example: Their fortuitous meeting led to collaboration.",
  FRACTIOUS: "unruly, quarrelsome, irritable — Example: The fractious committee could not reach consensus.",
  FRUGAL: "thrifty, economical, sparing — Example: Her frugal habits allowed her to save substantial money.",
  
  // G words (12)
  GARRULOUS: "talkative, loquacious, verbose — Example: The garrulous passenger talked throughout the flight.",
  GERMANE: "relevant, pertinent, applicable — Example: His comments were not germane to the discussion.",
  GLIB: "smooth, slick, superficial — Example: His glib answers failed to address real concerns.",
  GRANDIOSE: "impressive, ambitious, extravagant — Example: The developer proposed grandiose plans for downtown.",
  GRATUITOUS: "unnecessary, unwarranted, unjustified — Example: The film contains gratuitous violence.",
  GREGARIOUS: "sociable, outgoing, friendly — Example: His gregarious nature made him popular.",
  GRIEVOUS: "serious, severe, grave — Example: The accident caused grievous injuries.",
  GUILE: "cunning, deceit, craftiness — Example: The con artist used guile to swindle victims.",
  HACKNEYED: "overused, trite, banal — Example: The speech was full of hackneyed phrases.",
  HAPLESS: "unlucky, unfortunate, ill-fated — Example: The hapless traveler lost his luggage and passport.",
  HEGEMONY: "dominance, supremacy, control — Example: The empire maintained hegemony over the region.",
  HUBRIS: "arrogance, pride, conceit — Example: His hubris led to his eventual downfall.",
  
  // H words (12)
  HACKNEYED: "clichéd, overused, stale — Example: The writer avoided hackneyed expressions.",
  HAPLESS: "unlucky, unfortunate, cursed — Example: The hapless team lost every game.",
  HARBINGER: "herald, sign, forerunner — Example: Dark clouds are harbingers of storms.",
  HAUGHTY: "arrogant, proud, superior — Example: Her haughty attitude alienated coworkers.",
  HEDONISTIC: "pleasure-seeking, self-indulgent, sybaritic — Example: His hedonistic lifestyle eventually caught up with him.",
  HERETICAL: "unorthodox, dissenting, radical — Example: The scientist's heretical ideas challenged conventional wisdom.",
  HIERARCHY: "ranking, pecking order, structure — Example: The corporate hierarchy determines decision-making authority.",
  HISTRIONIC: "theatrical, dramatic, melodramatic — Example: Her histrionic outburst embarrassed everyone present.",
  HOMOGENEOUS: "uniform, consistent, similar — Example: The population is relatively homogeneous.",
  HYPERBOLE: "exaggeration, overstatement, embellishment — Example: His description involved considerable hyperbole.",
  HYPOCRISY: "insincerity, duplicity, deceit — Example: The politician's hypocrisy was evident to voters.",
  HYPOTHETICAL: "theoretical, supposed, speculative — Example: Let's consider a hypothetical scenario.",
  
  // I words (12)
  ICONOCLAST: "rebel, nonconformist, dissenter — Example: The iconoclast challenged established traditions.",
  IDIOSYNCRASY: "quirk, peculiarity, mannerism — Example: Everyone has personal idiosyncrasies.",
  IGNOBLE: "dishonorable, shameful, base — Example: His ignoble actions disappointed supporters.",
  ILLICIT: "illegal, forbidden, unlawful — Example: Police cracked down on illicit activities.",
  IMMUTABLE: "unchangeable, fixed, permanent — Example: Some physical laws appear immutable.",
  IMPASSIVE: "expressionless, unemotional, stoic — Example: The guard remained impassive throughout the ordeal.",
  IMPECUNIOUS: "poor, penniless, broke — Example: The impecunious student worked three jobs.",
  IMPERIOUS: "domineering, overbearing, authoritative — Example: His imperious manner irritated subordinates.",
  IMPERTURBABLE: "calm, unflappable, composed — Example: She remained imperturbable during the crisis.",
  IMPETUOUS: "impulsive, rash, hasty — Example: His impetuous decision had serious consequences.",
  IMPLACABLE: "relentless, unforgiving, inflexible — Example: She was an implacable opponent of injustice.",
  IMPLICIT: "implied, understood, unspoken — Example: There was an implicit agreement between them.",
  
  // J words (6)
  JUDICIOUS: "wise, prudent, sensible — Example: The judge made a judicious ruling.",
  JADED: "tired, weary, cynical — Example: Years in politics left him jaded.",
  JARGON: "terminology, lingo, vocabulary — Example: Medical jargon confuses most patients.",
  JINGOISTIC: "nationalistic, chauvinistic, patriotic — Example: The jingoistic rhetoric inflamed tensions.",
  JOCUND: "cheerful, merry, jovial — Example: His jocund personality brightened every gathering.",
  JUDICIOUS: "sensible, wise, prudent — Example: She made a judicious investment decision.",
  
  // K words (4)
  KINETIC: "active, dynamic, energetic — Example: The sculpture captures kinetic energy.",
  KNAVE: "scoundrel, rogue, villain — Example: The knave deceived many innocent people.",
  KNOTTY: "complex, difficult, intricate — Example: The knotty problem required expert analysis.",
  KUDOS: "praise, acclaim, glory — Example: Kudos to the team for outstanding work.",
  
  // L words (12)
  LACONIC: "brief, concise, terse — Example: His laconic response ended the discussion.",
  LAMENT: "mourn, grieve, bewail — Example: The poet lamented the loss of innocence.",
  LANGUID: "weak, listless, sluggish — Example: The heat made everyone feel languid.",
  LATENT: "dormant, hidden, potential — Example: Her latent abilities emerged under pressure.",
  LAUDABLE: "praiseworthy, commendable, admirable — Example: The volunteers' efforts are laudable.",
  LICENTIOUS: "immoral, promiscuous, dissolute — Example: The emperor's licentious behavior scandalized the court.",
  LIMN: "outline, depict, describe — Example: The author limns a vivid portrait of society.",
  LITHE: "flexible, agile, supple — Example: The dancer's lithe movements captivated audiences.",
  LOQUACIOUS: "talkative, garrulous, verbose — Example: The loquacious guest dominated conversation.",
  LUGUBRIOUS: "mournful, gloomy, sad — Example: The funeral proceeded in a lugubrious atmosphere.",
  LUMINOUS: "bright, radiant, glowing — Example: The painting has a luminous quality.",
  LURID: "sensational, shocking, vivid — Example: The tabloid featured lurid headlines.",
  
  // M words (12)
  MALADROIT: "clumsy, awkward, inept — Example: His maladroit attempt at diplomacy worsened relations.",
  MALEVOLENT: "hostile, malicious, spiteful — Example: The villain's malevolent intentions were clear.",
  MALLEABLE: "pliable, flexible, adaptable — Example: Gold is a highly malleable metal.",
  MAVERICK: "nonconformist, rebel, individualist — Example: The maverick politician defied party leadership.",
  MELANCHOLY: "sad, depressed, gloomy — Example: The melancholy music suited his mood.",
  MENDACIOUS: "dishonest, lying, deceitful — Example: The mendacious testimony was exposed.",
  MERCURIAL: "volatile, unpredictable, changeable — Example: His mercurial temperament made planning difficult.",
  MERITORIOUS: "deserving, worthy, praiseworthy — Example: She received an award for meritorious service.",
  METAMORPHOSIS: "transformation, change, conversion — Example: The caterpillar undergoes metamorphosis.",
  METICULOUS: "careful, precise, thorough — Example: The surgeon's meticulous technique ensured success.",
  MIRE: "entangle, involve, bog down — Example: The company became mired in legal disputes.",
  MITIGATE: "reduce, lessen, alleviate — Example: New policies will mitigate environmental damage.",
  
  // N words (10)
  NEBULOUS: "vague, unclear, indefinite — Example: His plans remained nebulous and unconvincing.",
  NEFARIOUS: "wicked, villainous, evil — Example: The nefarious plot was uncovered just in time.",
  NEOPHYTE: "beginner, novice, newcomer — Example: The neophyte made predictable mistakes.",
  NONCHALANT: "casual, indifferent, unconcerned — Example: He maintained a nonchalant attitude.",
  NOSTALGIC: "sentimental, wistful, yearning — Example: The old photographs made her nostalgic.",
  NOTORIOUS: "infamous, disreputable, scandalous — Example: The notorious criminal was finally captured.",
  NOVICE: "beginner, amateur, learner — Example: The novice painter showed promise.",
  NUANCE: "subtlety, shade, distinction — Example: The translation captures every nuance.",
  NUMINOUS: "spiritual, mystical, divine — Example: The cathedral had a numinous atmosphere.",
  NURTURE: "nourish, foster, cultivate — Example: Good schools nurture students' potential.",
  
  // O words (10)
  OBDURATE: "stubborn, inflexible, unyielding — Example: He remained obdurate despite all arguments.",
  OBFUSCATE: "confuse, obscure, muddle — Example: Complex jargon serves only to obfuscate.",
  OBSEQUIOUS: "servile, fawning, submissive — Example: His obsequious behavior was embarrassing.",
  OBTUSE: "dull, insensitive, slow — Example: He was obtuse to her obvious hints.",
  OMINOUS: "threatening, foreboding, sinister — Example: The ominous clouds suggested severe weather.",
  ONEROUS: "burdensome, oppressive, demanding — Example: The contract imposed onerous obligations.",
  OPAQUE: "unclear, obscure, impenetrable — Example: The legal language was opaque to laypeople.",
  OPPORTUNE: "timely, favorable, convenient — Example: This is an opportune moment to negotiate.",
  ORTHODOX: "conventional, traditional, standard — Example: He challenged orthodox economic theory.",
  OSTENSIBLE: "apparent, seeming, professed — Example: His ostensible reason concealed the truth.",
  
  // P words (18)
  PALPABLE: "tangible, obvious, evident — Example: The tension in the room was palpable.",
  PANACEA: "cure-all, remedy, solution — Example: There's no panacea for economic problems.",
  PARADIGM: "model, pattern, framework — Example: The discovery created a new scientific paradigm.",
  PARADOX: "contradiction, puzzle, anomaly — Example: It's a paradox that wealth creates new problems.",
  PARAGON: "model, exemplar, ideal — Example: She is a paragon of virtue and integrity.",
  PARIAH: "outcast, exile, untouchable — Example: The scandal made him a social pariah.",
  PAROCHIAL: "narrow, provincial, limited — Example: His parochial views limited his understanding.",
  PARSIMONIOUS: "stingy, miserly, frugal — Example: The parsimonious boss refused raises.",
  PARTISAN: "biased, prejudiced, one-sided — Example: The partisan media coverage distorted facts.",
  PATHOS: "emotion, feeling, sympathy — Example: The speech was full of pathos.",
  PAUCITY: "scarcity, shortage, lack — Example: There's a paucity of evidence supporting this theory.",
  PEDANTIC: "overly scholarly, pompous, formal — Example: His pedantic lectures bored students.",
  PENCHANT: "liking, inclination, tendency — Example: She has a penchant for spicy food.",
  PENITENT: "remorseful, sorry, regretful — Example: The penitent criminal apologized to victims.",
  PENSIVE: "thoughtful, reflective, contemplative — Example: She sat in a pensive mood.",
  PENURY: "poverty, destitution, want — Example: The family lived in abject penury.",
  PERFIDIOUS: "treacherous, disloyal, faithless — Example: The perfidious ally betrayed the treaty.",
  PERFUNCTORY: "cursory, superficial, routine — Example: He gave a perfunctory inspection.",
  
  // Q words (6)
  QUAGMIRE: "predicament, difficulty, mess — Example: The war became a quagmire with no exit.",
  QUANDARY: "dilemma, predicament, difficulty — Example: She faced a quandary about career choices.",
  QUARANTINE: "isolate, separate, sequester — Example: Officials quarantined the infected patients.",
  QUASH: "suppress, crush, put down — Example: The military moved to quash the rebellion.",
  QUERULOUS: "complaining, whining, petulant — Example: The querulous customer demanded a refund.",
  QUIXOTIC: "idealistic, impractical, unrealistic — Example: His quixotic quest was doomed to fail.",
  
  // R words (12)
  RANCOROUS: "bitter, spiteful, resentful — Example: The rancorous debate accomplished nothing.",
  RAPACIOUS: "greedy, voracious, predatory — Example: The rapacious corporation exploited workers.",
  RAZE: "demolish, destroy, level — Example: They plan to raze the old building.",
  RECALCITRANT: "defiant, uncooperative, obstinate — Example: The recalcitrant prisoner refused orders.",
  RECAPITULATE: "summarize, repeat, restate — Example: Let me recapitulate the main points.",
  RECLUSIVE: "solitary, withdrawn, hermit-like — Example: The reclusive author avoided publicity.",
  REDOLENT: "fragrant, aromatic, evocative — Example: The garden was redolent with roses.",
  REDRESS: "remedy, correct, compensate — Example: Victims sought redress through the courts.",
  REDUNDANT: "superfluous, unnecessary, repetitive — Example: The redundant clauses confused readers.",
  REFUTE: "disprove, rebut, contradict — Example: Evidence clearly refutes his claims.",
  RELEGATE: "demote, downgrade, banish — Example: The player was relegated to the bench.",
  RELINQUISH: "surrender, give up, abandon — Example: He refused to relinquish control.",
  
  // S words (18)
  SAGACITY: "wisdom, insight, judgment — Example: The elder's sagacity guided the community.",
  SALIENT: "prominent, important, striking — Example: The report highlights the salient features.",
  SANGUINE: "optimistic, hopeful, confident — Example: Despite setbacks, she remained sanguine.",
  SARDONIC: "mocking, sarcastic, cynical — Example: His sardonic wit made people uncomfortable.",
  SAVANT: "expert, genius, scholar — Example: The mathematical savant solved complex equations mentally.",
  SCRUPULOUS: "careful, conscientious, ethical — Example: She was scrupulous in her research methods.",
  SECTARIAN: "narrow, partisan, factional — Example: Sectarian violence plagued the region.",
  SEDITIOUS: "rebellious, subversive, traitorous — Example: The government prosecuted seditious speech.",
  SEMINAL: "influential, groundbreaking, pivotal — Example: Darwin's seminal work revolutionized biology.",
  SENSUOUS: "pleasurable, gratifying, aesthetic — Example: The sensuous music enchanted listeners.",
  SERENDIPITY: "chance, luck, fortune — Example: Meeting her mentor was pure serendipity.",
  SOBRIETY: "seriousness, temperance, moderation — Example: The occasion called for sobriety.",
  SOLICITOUS: "concerned, attentive, caring — Example: The nurse was solicitous of patients' comfort.",
  SOMNOLENT: "sleepy, drowsy, lethargic — Example: The warm room made everyone somnolent.",
  SPECIOUS: "false, misleading, deceptive — Example: His specious argument deceived few people.",
  SPURIOUS: "false, fake, bogus — Example: The document proved to be spurious.",
  STOIC: "unemotional, impassive, resigned — Example: She remained stoic throughout the ordeal.",
  STRIDENT: "harsh, shrill, grating — Example: His strident voice dominated the meeting.",
  
  // T words (12)
  TACIT: "implied, understood, unspoken — Example: They had a tacit agreement to disagree.",
  TANGENTIAL: "peripheral, irrelevant, divergent — Example: His tangential comments distracted from the issue.",
  TAUTOLOGY: "redundancy, repetition, pleonasm — Example: 'Free gift' is a tautology.",
  TEMERITY: "audacity, boldness, nerve — Example: He had the temerity to criticize his boss.",
  TEMPERANCE: "moderation, restraint, self-control — Example: She practiced temperance in all things.",
  TENACIOUS: "persistent, determined, stubborn — Example: The tenacious lawyer never gave up.",
  TENET: "principle, belief, doctrine — Example: Free speech is a core tenet of democracy.",
  TEPID: "lukewarm, halfhearted, unenthusiastic — Example: The proposal received tepid support.",
  TERSE: "brief, concise, abrupt — Example: His terse reply ended the conversation.",
  TIMOROUS: "timid, fearful, nervous — Example: The timorous rabbit fled at any sound.",
  TIRADE: "outburst, harangue, diatribe — Example: The customer launched into a tirade.",
  TORPOR: "lethargy, sluggishness, inactivity — Example: The heat induced a state of torpor.",
  
  // U words (8)
  UBIQUITOUS: "omnipresent, everywhere, universal — Example: Smartphones are ubiquitous in society.",
  ULTERIOR: "hidden, concealed, covert — Example: She suspected he had ulterior motives.",
  UMBRAGE: "offense, resentment, displeasure — Example: He took umbrage at the criticism.",
  UNASSUMING: "modest, humble, unpretentious — Example: Despite wealth, he remained unassuming.",
  UNCTUOUS: "oily, ingratiating, smarmy — Example: The unctuous salesman repelled customers.",
  UNDULATE: "wave, ripple, fluctuate — Example: The flag undulated in the breeze.",
  UNEQUIVOCAL: "clear, definite, unambiguous — Example: She gave an unequivocal denial.",
  UNSCRUPULOUS: "dishonest, immoral, unprincipled — Example: The unscrupulous dealer cheated customers.",
  
  // V words (12)
  VACILLATE: "waver, hesitate, fluctuate — Example: Don't vacillate; make a decision.",
  VAGARY: "whim, caprice, quirk — Example: The vagaries of weather affected the harvest.",
  VAPID: "dull, insipid, lifeless — Example: The vapid conversation bored everyone.",
  VARIEGATED: "varied, diverse, multicolored — Example: The garden had variegated foliage.",
  VEHEMENT: "intense, passionate, forceful — Example: She gave a vehement defense of her position.",
  VENEER: "facade, surface, pretense — Example: His politeness was merely a veneer.",
  VERACIOUS: "truthful, honest, accurate — Example: The witness proved to be veracious.",
  VERBATIM: "word-for-word, exact, literal — Example: Quote me verbatim, without changes.",
  VERBOSE: "wordy, long-winded, prolix — Example: His verbose speech lasted two hours.",
  VERISIMILITUDE: "realism, authenticity, plausibility — Example: The novel has remarkable verisimilitude.",
  VERNACULAR: "dialect, language, idiom — Example: He wrote in the local vernacular.",
  VICARIOUS: "indirect, secondhand, substitute — Example: She lived vicariously through her children.",
  
  // W words (8)
  WANE: "decline, decrease, diminish — Example: His influence began to wane.",
  WANTON: "reckless, malicious, deliberate — Example: The wanton destruction shocked observers.",
  WIZENED: "shriveled, wrinkled, withered — Example: The wizened old man told ancient stories.",
  WRATH: "anger, rage, fury — Example: The king's wrath was terrible to behold.",
  WROUGHT: "formed, shaped, created — Example: The sculpture was beautifully wrought.",
  WILY: "cunning, crafty, shrewd — Example: The wily fox escaped the hunters.",
  WINSOME: "charming, attractive, appealing — Example: Her winsome smile won hearts.",
  WREAK: "inflict, cause, bring about — Example: The storm will wreak havoc on the coast.",
  
  // X, Y, Z words (4)
  XENOPHOBIC: "intolerant, prejudiced, bigoted — Example: Xenophobic attitudes harm society.",
  YOKE: "burden, bond, harness — Example: They threw off the yoke of oppression.",
  ZEALOT: "fanatic, extremist, radical — Example: The zealot refused to compromise.",
  ZEPHYR: "breeze, wind, draft — Example: A gentle zephyr cooled the afternoon."
};

window.QUESTIONS_ENHANCED2 = [
  // A words (12 questions: 601-612)
  { number: 601, word: "ABATE", choices: { A:"increase", B:"intensify", C:"reduce", D:"worsen" }, answer:"C" },
  { number: 602, word: "ABERRATION", choices: { A:"norm", B:"standard", C:"deviation", D:"pattern" }, answer:"C" },
  { number: 603, word: "ABHOR", choices: { A:"love", B:"admire", C:"detest", D:"enjoy" }, answer:"C" },
  { number: 604, word: "ABJURE", choices: { A:"embrace", B:"accept", C:"renounce", D:"adopt" }, answer:"C" },
  { number: 605, word: "ABSTEMIOUS", choices: { A:"excessive", B:"indulgent", C:"moderate", D:"gluttonous" }, answer:"C" },
  { number: 606, word: "ACCRUE", choices: { A:"diminish", B:"lose", C:"accumulate", D:"spend" }, answer:"C" },
  { number: 607, word: "ACERBIC", choices: { A:"sweet", B:"gentle", C:"harsh", D:"kind" }, answer:"C" },
  { number: 608, word: "ACQUIESCE", choices: { A:"resist", B:"oppose", C:"consent", D:"fight" }, answer:"C" },
  { number: 609, word: "ACRIMONIOUS", choices: { A:"friendly", B:"pleasant", C:"bitter", D:"cordial" }, answer:"C" },
  { number: 610, word: "ADROIT", choices: { A:"clumsy", B:"awkward", C:"skillful", D:"inept" }, answer:"C" },
  { number: 611, word: "AESTHETIC", choices: { A:"ugly", B:"plain", C:"artistic", D:"crude" }, answer:"C" },
  { number: 612, word: "AFFINITY", choices: { A:"repulsion", B:"hatred", C:"attraction", D:"aversion" }, answer:"C" },
  
  // B words (12 questions: 613-624)
  { number: 613, word: "BELLICOSE", choices: { A:"peaceful", B:"calm", C:"warlike", D:"gentle" }, answer:"C" },
  { number: 614, word: "BENEFACTOR", choices: { A:"enemy", B:"opponent", C:"patron", D:"rival" }, answer:"C" },
  { number: 615, word: "BENIGN", choices: { A:"harmful", B:"malignant", C:"harmless", D:"dangerous" }, answer:"C" },
  { number: 616, word: "BERATE", choices: { A:"praise", B:"compliment", C:"scold", D:"flatter" }, answer:"C" },
  { number: 617, word: "BOMBASTIC", choices: { A:"modest", B:"humble", C:"pompous", D:"understated" }, answer:"C" },
  { number: 618, word: "BOON", choices: { A:"curse", B:"disadvantage", C:"benefit", D:"hindrance" }, answer:"C" },
  { number: 619, word: "BUCOLIC", choices: { A:"urban", B:"industrial", C:"rural", D:"metropolitan" }, answer:"C" },
  { number: 620, word: "BULBOUS", choices: { A:"flat", B:"thin", C:"swollen", D:"narrow" }, answer:"C" },
  { number: 621, word: "BUREAUCRATIC", choices: { A:"efficient", B:"streamlined", C:"administrative", D:"simple" }, answer:"C" },
  { number: 622, word: "BURGEON", choices: { A:"shrink", B:"decline", C:"flourish", D:"wither" }, answer:"C" },
  { number: 623, word: "BURNISH", choices: { A:"tarnish", B:"dull", C:"polish", D:"dirty" }, answer:"C" },
  { number: 624, word: "BUTTRESS", choices: { A:"weaken", B:"undermine", C:"support", D:"destroy" }, answer:"C" },
  
  // C words (18 questions: 625-642)
  { number: 625, word: "CACOPHONY", choices: { A:"harmony", B:"melody", C:"discord", D:"music" }, answer:"C" },
  { number: 626, word: "CAJOLE", choices: { A:"force", B:"threaten", C:"coax", D:"command" }, answer:"C" },
  { number: 627, word: "CALLOUS", choices: { A:"sensitive", B:"caring", C:"insensitive", D:"compassionate" }, answer:"C" },
  { number: 628, word: "CALUMNY", choices: { A:"praise", B:"compliment", C:"slander", D:"tribute" }, answer:"C" },
  { number: 629, word: "CANDID", choices: { A:"dishonest", B:"deceptive", C:"frank", D:"secretive" }, answer:"C" },
  { number: 630, word: "CANTANKEROUS", choices: { A:"pleasant", B:"agreeable", C:"quarrelsome", D:"friendly" }, answer:"C" },
  { number: 631, word: "CAPITULATE", choices: { A:"resist", B:"fight", C:"surrender", D:"attack" }, answer:"C" },
  { number: 632, word: "CAPRICIOUS", choices: { A:"steady", B:"reliable", C:"unpredictable", D:"consistent" }, answer:"C" },
  { number: 633, word: "CASTIGATE", choices: { A:"praise", B:"reward", C:"criticize", D:"honor" }, answer:"C" },
  { number: 634, word: "CATALYST", choices: { A:"hindrance", B:"obstacle", C:"agent", D:"barrier" }, answer:"C" },
  { number: 635, word: "CAUSTIC", choices: { A:"gentle", B:"kind", C:"corrosive", D:"soothing" }, answer:"C" },
  { number: 636, word: "CHARLATAN", choices: { A:"expert", B:"professional", C:"fraud", D:"specialist" }, answer:"C" },
  { number: 637, word: "CHICANERY", choices: { A:"honesty", B:"integrity", C:"deception", D:"truthfulness" }, answer:"C" },
  { number: 638, word: "CIRCUMSPECT", choices: { A:"reckless", B:"careless", C:"cautious", D:"impulsive" }, answer:"C" },
  { number: 639, word: "CLANDESTINE", choices: { A:"open", B:"public", C:"secret", D:"obvious" }, answer:"C" },
  { number: 640, word: "COALESCE", choices: { A:"separate", B:"divide", C:"unite", D:"split" }, answer:"C" },
  { number: 641, word: "COGENT", choices: { A:"weak", B:"unconvincing", C:"convincing", D:"illogical" }, answer:"C" },
  { number: 642, word: "COLLOQUIAL", choices: { A:"formal", B:"academic", C:"informal", D:"technical" }, answer:"C" },
  
  // D words (18 questions: 643-660)
  { number: 643, word: "DAUNT", choices: { A:"encourage", B:"embolden", C:"intimidate", D:"inspire" }, answer:"C" },
  { number: 644, word: "DEBUNK", choices: { A:"prove", B:"confirm", C:"disprove", D:"validate" }, answer:"C" },
  { number: 645, word: "DECORUM", choices: { A:"rudeness", B:"vulgarity", C:"propriety", D:"impropriety" }, answer:"C" },
  { number: 646, word: "DEFAME", choices: { A:"praise", B:"honor", C:"slander", D:"respect" }, answer:"C" },
  { number: 647, word: "DEFERENCE", choices: { A:"disrespect", B:"contempt", C:"respect", D:"scorn" }, answer:"C" },
  { number: 648, word: "DEIGN", choices: { A:"refuse", B:"reject", C:"condescend", D:"elevate" }, answer:"C" },
  { number: 649, word: "DELETERIOUS", choices: { A:"beneficial", B:"helpful", C:"harmful", D:"advantageous" }, answer:"C" },
  { number: 650, word: "DELINEATE", choices: { A:"obscure", B:"confuse", C:"describe", D:"hide" }, answer:"C" },
  { number: 651, word: "DELUGE", choices: { A:"drought", B:"trickle", C:"flood", D:"scarcity" }, answer:"C" },
  { number: 652, word: "DEMAGOGUE", choices: { A:"statesman", B:"diplomat", C:"agitator", D:"peacemaker" }, answer:"C" },
  { number: 653, word: "DEMEANOR", choices: { A:"essence", B:"core", C:"behavior", D:"substance" }, answer:"C" },
  { number: 654, word: "DEMURE", choices: { A:"bold", B:"brash", C:"modest", D:"forward" }, answer:"C" },
  { number: 655, word: "DENIGRATE", choices: { A:"praise", B:"elevate", C:"disparage", D:"honor" }, answer:"C" },
  { number: 656, word: "DERIDE", choices: { A:"praise", B:"admire", C:"mock", D:"respect" }, answer:"C" },
  { number: 657, word: "DESPOT", choices: { A:"democrat", B:"servant", C:"tyrant", D:"follower" }, answer:"C" },
  { number: 658, word: "DESULTORY", choices: { A:"focused", B:"systematic", C:"random", D:"organized" }, answer:"C" },
  { number: 659, word: "DIATRIBE", choices: { A:"praise", B:"compliment", C:"tirade", D:"tribute" }, answer:"C" },
  { number: 660, word: "DICHOTOMY", choices: { A:"unity", B:"similarity", C:"division", D:"agreement" }, answer:"C" },
  
  // E words (18 questions: 661-678)
  { number: 661, word: "EBULLIENT", choices: { A:"depressed", B:"sad", C:"enthusiastic", D:"gloomy" }, answer:"C" },
  { number: 662, word: "ECCENTRIC", choices: { A:"normal", B:"conventional", C:"unconventional", D:"typical" }, answer:"C" },
  { number: 663, word: "ECLECTIC", choices: { A:"uniform", B:"homogeneous", C:"diverse", D:"similar" }, answer:"C" },
  { number: 664, word: "EFFACE", choices: { A:"create", B:"establish", C:"erase", D:"build" }, answer:"C" },
  { number: 665, word: "EFFICACY", choices: { A:"ineffectiveness", B:"failure", C:"effectiveness", D:"uselessness" }, answer:"C" },
  { number: 666, word: "EFFRONTERY", choices: { A:"respect", B:"deference", C:"audacity", D:"humility" }, answer:"C" },
  { number: 667, word: "EGALITARIAN", choices: { A:"hierarchical", B:"unequal", C:"equal", D:"discriminatory" }, answer:"C" },
  { number: 668, word: "EGREGIOUS", choices: { A:"minor", B:"trivial", C:"outrageous", D:"insignificant" }, answer:"C" },
  { number: 669, word: "ELABORATE", choices: { A:"simple", B:"plain", C:"detailed", D:"basic" }, answer:"C" },
  { number: 670, word: "ELEGY", choices: { A:"celebration", B:"comedy", C:"lament", D:"joy" }, answer:"C" },
  { number: 671, word: "ELOQUENT", choices: { A:"inarticulate", B:"clumsy", C:"articulate", D:"awkward" }, answer:"C" },
  { number: 672, word: "ELUCIDATE", choices: { A:"confuse", B:"obscure", C:"clarify", D:"complicate" }, answer:"C" },
  { number: 673, word: "ELUSIVE", choices: { A:"obvious", B:"clear", C:"evasive", D:"apparent" }, answer:"C" },
  { number: 674, word: "EMBELLISH", choices: { A:"simplify", B:"reduce", C:"decorate", D:"strip" }, answer:"C" },
  { number: 675, word: "EMBROIL", choices: { A:"free", B:"release", C:"involve", D:"liberate" }, answer:"C" },
  { number: 676, word: "EMULATE", choices: { A:"ignore", B:"reject", C:"imitate", D:"oppose" }, answer:"C" },
  { number: 677, word: "ENDEMIC", choices: { A:"foreign", B:"alien", C:"native", D:"imported" }, answer:"C" },
  { number: 678, word: "ENGENDER", choices: { A:"prevent", B:"stop", C:"cause", D:"hinder" }, answer:"C" },
  
  // F words (18 questions: 679-696)
  { number: 679, word: "FACETIOUS", choices: { A:"serious", B:"grave", C:"joking", D:"solemn" }, answer:"C" },
  { number: 680, word: "FALLACIOUS", choices: { A:"true", B:"correct", C:"false", D:"accurate" }, answer:"C" },
  { number: 681, word: "FASTIDIOUS", choices: { A:"careless", B:"sloppy", C:"meticulous", D:"negligent" }, answer:"C" },
  { number: 682, word: "FATUOUS", choices: { A:"intelligent", B:"wise", C:"foolish", D:"clever" }, answer:"C" },
  { number: 683, word: "FAWN", choices: { A:"challenge", B:"confront", C:"grovel", D:"oppose" }, answer:"C" },
  { number: 684, word: "FEALTY", choices: { A:"betrayal", B:"treachery", C:"loyalty", D:"disloyalty" }, answer:"C" },
  { number: 685, word: "FECUND", choices: { A:"barren", B:"sterile", C:"fertile", D:"infertile" }, answer:"C" },
  { number: 686, word: "FERVOR", choices: { A:"apathy", B:"indifference", C:"passion", D:"coldness" }, answer:"C" },
  { number: 687, word: "FESTER", choices: { A:"heal", B:"improve", C:"rot", D:"recover" }, answer:"C" },
  { number: 688, word: "FIDELITY", choices: { A:"betrayal", B:"disloyalty", C:"loyalty", D:"treachery" }, answer:"C" },
  { number: 689, word: "FLACCID", choices: { A:"firm", B:"strong", C:"limp", D:"taut" }, answer:"C" },
  { number: 690, word: "FLAGITIOUS", choices: { A:"virtuous", B:"good", C:"wicked", D:"noble" }, answer:"C" },
  { number: 691, word: "FLEDGLING", choices: { A:"expert", B:"veteran", C:"beginner", D:"master" }, answer:"C" },
  { number: 692, word: "FOMENT", choices: { A:"calm", B:"pacify", C:"incite", D:"soothe" }, answer:"C" },
  { number: 693, word: "FORMIDABLE", choices: { A:"weak", B:"easy", C:"intimidating", D:"simple" }, answer:"C" },
  { number: 694, word: "FORTUITOUS", choices: { A:"planned", B:"deliberate", C:"lucky", D:"intentional" }, answer:"C" },
  { number: 695, word: "FRACTIOUS", choices: { A:"cooperative", B:"agreeable", C:"unruly", D:"compliant" }, answer:"C" },
  { number: 696, word: "FRUGAL", choices: { A:"wasteful", B:"extravagant", C:"thrifty", D:"lavish" }, answer:"C" },
  
  // G words (12 questions: 697-708)
  { number: 697, word: "GARRULOUS", choices: { A:"quiet", B:"silent", C:"talkative", D:"taciturn" }, answer:"C" },
  { number: 698, word: "GERMANE", choices: { A:"irrelevant", B:"unrelated", C:"relevant", D:"tangential" }, answer:"C" },
  { number: 699, word: "GLIB", choices: { A:"sincere", B:"genuine", C:"smooth", D:"thoughtful" }, answer:"C" },
  { number: 700, word: "GRANDIOSE", choices: { A:"modest", B:"humble", C:"impressive", D:"simple" }, answer:"C" },
  { number: 701, word: "GRATUITOUS", choices: { A:"necessary", B:"essential", C:"unnecessary", D:"required" }, answer:"C" },
  { number: 702, word: "GREGARIOUS", choices: { A:"antisocial", B:"withdrawn", C:"sociable", D:"shy" }, answer:"C" },
  { number: 703, word: "GRIEVOUS", choices: { A:"minor", B:"trivial", C:"serious", D:"insignificant" }, answer:"C" },
  { number: 704, word: "GUILE", choices: { A:"honesty", B:"sincerity", C:"cunning", D:"frankness" }, answer:"C" },
  { number: 705, word: "HACKNEYED", choices: { A:"original", B:"fresh", C:"overused", D:"novel" }, answer:"C" },
  { number: 706, word: "HAPLESS", choices: { A:"lucky", B:"fortunate", C:"unlucky", D:"blessed" }, answer:"C" },
  { number: 707, word: "HEGEMONY", choices: { A:"weakness", B:"submission", C:"dominance", D:"subservience" }, answer:"C" },
  { number: 708, word: "HUBRIS", choices: { A:"humility", B:"modesty", C:"arrogance", D:"meekness" }, answer:"C" },
  
  // H words (12 questions: 709-720)
  { number: 709, word: "HACKNEYED", choices: { A:"innovative", B:"unique", C:"clichéd", D:"creative" }, answer:"C" },
  { number: 710, word: "HAPLESS", choices: { A:"fortunate", B:"successful", C:"unlucky", D:"prosperous" }, answer:"C" },
  { number: 711, word: "HARBINGER", choices: { A:"conclusion", B:"ending", C:"herald", D:"finale" }, answer:"C" },
  { number: 712, word: "HAUGHTY", choices: { A:"humble", B:"meek", C:"arrogant", D:"modest" }, answer:"C" },
  { number: 713, word: "HEDONISTIC", choices: { A:"ascetic", B:"austere", C:"pleasure-seeking", D:"abstemious" }, answer:"C" },
  { number: 714, word: "HERETICAL", choices: { A:"orthodox", B:"conventional", C:"unorthodox", D:"traditional" }, answer:"C" },
  { number: 715, word: "HIERARCHY", choices: { A:"equality", B:"democracy", C:"ranking", D:"anarchy" }, answer:"C" },
  { number: 716, word: "HISTRIONIC", choices: { A:"understated", B:"subdued", C:"theatrical", D:"calm" }, answer:"C" },
  { number: 717, word: "HOMOGENEOUS", choices: { A:"diverse", B:"varied", C:"uniform", D:"mixed" }, answer:"C" },
  { number: 718, word: "HYPERBOLE", choices: { A:"understatement", B:"moderation", C:"exaggeration", D:"restraint" }, answer:"C" },
  { number: 719, word: "HYPOCRISY", choices: { A:"sincerity", B:"honesty", C:"insincerity", D:"truthfulness" }, answer:"C" },
  { number: 720, word: "HYPOTHETICAL", choices: { A:"actual", B:"real", C:"theoretical", D:"concrete" }, answer:"C" },
  
  // I words (12 questions: 721-732)
  { number: 721, word: "ICONOCLAST", choices: { A:"conformist", B:"traditionalist", C:"rebel", D:"follower" }, answer:"C" },
  { number: 722, word: "IDIOSYNCRASY", choices: { A:"normalcy", B:"conformity", C:"quirk", D:"standard" }, answer:"C" },
  { number: 723, word: "IGNOBLE", choices: { A:"honorable", B:"noble", C:"dishonorable", D:"dignified" }, answer:"C" },
  { number: 724, word: "ILLICIT", choices: { A:"legal", B:"lawful", C:"illegal", D:"permitted" }, answer:"C" },
  { number: 725, word: "IMMUTABLE", choices: { A:"changeable", B:"flexible", C:"unchangeable", D:"variable" }, answer:"C" },
  { number: 726, word: "IMPASSIVE", choices: { A:"emotional", B:"expressive", C:"expressionless", D:"animated" }, answer:"C" },
  { number: 727, word: "IMPECUNIOUS", choices: { A:"wealthy", B:"rich", C:"poor", D:"affluent" }, answer:"C" },
  { number: 728, word: "IMPERIOUS", choices: { A:"submissive", B:"humble", C:"domineering", D:"meek" }, answer:"C" },
  { number: 729, word: "IMPERTURBABLE", choices: { A:"anxious", B:"worried", C:"calm", D:"agitated" }, answer:"C" },
  { number: 730, word: "IMPETUOUS", choices: { A:"cautious", B:"careful", C:"impulsive", D:"deliberate" }, answer:"C" },
  { number: 731, word: "IMPLACABLE", choices: { A:"forgiving", B:"merciful", C:"relentless", D:"lenient" }, answer:"C" },
  { number: 732, word: "IMPLICIT", choices: { A:"explicit", B:"stated", C:"implied", D:"expressed" }, answer:"C" },
  
  // J words (6 questions: 733-738)
  { number: 733, word: "JUDICIOUS", choices: { A:"foolish", B:"reckless", C:"wise", D:"imprudent" }, answer:"C" },
  { number: 734, word: "JADED", choices: { A:"fresh", B:"enthusiastic", C:"tired", D:"energetic" }, answer:"C" },
  { number: 735, word: "JARGON", choices: { A:"plain speech", B:"simplicity", C:"terminology", D:"clarity" }, answer:"C" },
  { number: 736, word: "JINGOISTIC", choices: { A:"international", B:"cosmopolitan", C:"nationalistic", D:"global" }, answer:"C" },
  { number: 737, word: "JOCUND", choices: { A:"sad", B:"gloomy", C:"cheerful", D:"melancholy" }, answer:"C" },
  { number: 738, word: "JUDICIOUS", choices: { A:"rash", B:"hasty", C:"sensible", D:"impulsive" }, answer:"C" },
  
  // K words (4 questions: 739-742)
  { number: 739, word: "KINETIC", choices: { A:"static", B:"stationary", C:"active", D:"motionless" }, answer:"C" },
  { number: 740, word: "KNAVE", choices: { A:"hero", B:"saint", C:"scoundrel", D:"gentleman" }, answer:"C" },
  { number: 741, word: "KNOTTY", choices: { A:"simple", B:"easy", C:"complex", D:"straightforward" }, answer:"C" },
  { number: 742, word: "KUDOS", choices: { A:"criticism", B:"blame", C:"praise", D:"condemnation" }, answer:"C" },
  
  // L words (12 questions: 743-754)
  { number: 743, word: "LACONIC", choices: { A:"verbose", B:"wordy", C:"brief", D:"lengthy" }, answer:"C" },
  { number: 744, word: "LAMENT", choices: { A:"celebrate", B:"rejoice", C:"mourn", D:"cheer" }, answer:"C" },
  { number: 745, word: "LANGUID", choices: { A:"energetic", B:"vigorous", C:"weak", D:"lively" }, answer:"C" },
  { number: 746, word: "LATENT", choices: { A:"obvious", B:"apparent", C:"dormant", D:"visible" }, answer:"C" },
  { number: 747, word: "LAUDABLE", choices: { A:"shameful", B:"disgraceful", C:"praiseworthy", D:"deplorable" }, answer:"C" },
  { number: 748, word: "LICENTIOUS", choices: { A:"moral", B:"virtuous", C:"immoral", D:"righteous" }, answer:"C" },
  { number: 749, word: "LIMN", choices: { A:"obscure", B:"hide", C:"outline", D:"conceal" }, answer:"C" },
  { number: 750, word: "LITHE", choices: { A:"stiff", B:"rigid", C:"flexible", D:"inflexible" }, answer:"C" },
  { number: 751, word: "LOQUACIOUS", choices: { A:"quiet", B:"silent", C:"talkative", D:"reserved" }, answer:"C" },
  { number: 752, word: "LUGUBRIOUS", choices: { A:"cheerful", B:"happy", C:"mournful", D:"joyful" }, answer:"C" },
  { number: 753, word: "LUMINOUS", choices: { A:"dark", B:"dim", C:"bright", D:"shadowy" }, answer:"C" },
  { number: 754, word: "LURID", choices: { A:"mild", B:"subtle", C:"sensational", D:"understated" }, answer:"C" },
  
  // M words (12 questions: 755-766)
  { number: 755, word: "MALADROIT", choices: { A:"graceful", B:"skilled", C:"clumsy", D:"adept" }, answer:"C" },
  { number: 756, word: "MALEVOLENT", choices: { A:"kind", B:"benevolent", C:"hostile", D:"friendly" }, answer:"C" },
  { number: 757, word: "MALLEABLE", choices: { A:"rigid", B:"inflexible", C:"pliable", D:"stiff" }, answer:"C" },
  { number: 758, word: "MAVERICK", choices: { A:"conformist", B:"follower", C:"nonconformist", D:"traditionalist" }, answer:"C" },
  { number: 759, word: "MELANCHOLY", choices: { A:"happy", B:"joyful", C:"sad", D:"cheerful" }, answer:"C" },
  { number: 760, word: "MENDACIOUS", choices: { A:"truthful", B:"honest", C:"dishonest", D:"sincere" }, answer:"C" },
  { number: 761, word: "MERCURIAL", choices: { A:"stable", B:"steady", C:"volatile", D:"constant" }, answer:"C" },
  { number: 762, word: "MERITORIOUS", choices: { A:"unworthy", B:"shameful", C:"deserving", D:"disgraceful" }, answer:"C" },
  { number: 763, word: "METAMORPHOSIS", choices: { A:"stagnation", B:"permanence", C:"transformation", D:"stability" }, answer:"C" },
  { number: 764, word: "METICULOUS", choices: { A:"careless", B:"sloppy", C:"careful", D:"negligent" }, answer:"C" },
  { number: 765, word: "MIRE", choices: { A:"free", B:"release", C:"entangle", D:"liberate" }, answer:"C" },
  { number: 766, word: "MITIGATE", choices: { A:"worsen", B:"aggravate", C:"reduce", D:"intensify" }, answer:"C" },
  
  // N words (10 questions: 767-776)
  { number: 767, word: "NEBULOUS", choices: { A:"clear", B:"definite", C:"vague", D:"specific" }, answer:"C" },
  { number: 768, word: "NEFARIOUS", choices: { A:"virtuous", B:"good", C:"wicked", D:"righteous" }, answer:"C" },
  { number: 769, word: "NEOPHYTE", choices: { A:"expert", B:"veteran", C:"beginner", D:"master" }, answer:"C" },
  { number: 770, word: "NONCHALANT", choices: { A:"anxious", B:"concerned", C:"casual", D:"worried" }, answer:"C" },
  { number: 771, word: "NOSTALGIC", choices: { A:"forward-looking", B:"future-oriented", C:"sentimental", D:"progressive" }, answer:"C" },
  { number: 772, word: "NOTORIOUS", choices: { A:"unknown", B:"respected", C:"infamous", D:"honored" }, answer:"C" },
  { number: 773, word: "NOVICE", choices: { A:"expert", B:"professional", C:"beginner", D:"specialist" }, answer:"C" },
  { number: 774, word: "NUANCE", choices: { A:"obviousness", B:"clarity", C:"subtlety", D:"bluntness" }, answer:"C" },
  { number: 775, word: "NUMINOUS", choices: { A:"mundane", B:"ordinary", C:"spiritual", D:"earthly" }, answer:"C" },
  { number: 776, word: "NURTURE", choices: { A:"neglect", B:"abandon", C:"nourish", D:"ignore" }, answer:"C" },
  
  // O words (10 questions: 777-786)
  { number: 777, word: "OBDURATE", choices: { A:"flexible", B:"yielding", C:"stubborn", D:"compliant" }, answer:"C" },
  { number: 778, word: "OBFUSCATE", choices: { A:"clarify", B:"explain", C:"confuse", D:"illuminate" }, answer:"C" },
  { number: 779, word: "OBSEQUIOUS", choices: { A:"assertive", B:"bold", C:"servile", D:"confident" }, answer:"C" },
  { number: 780, word: "OBTUSE", choices: { A:"sharp", B:"perceptive", C:"dull", D:"keen" }, answer:"C" },
  { number: 781, word: "OMINOUS", choices: { A:"promising", B:"hopeful", C:"threatening", D:"encouraging" }, answer:"C" },
  { number: 782, word: "ONEROUS", choices: { A:"easy", B:"light", C:"burdensome", D:"simple" }, answer:"C" },
  { number: 783, word: "OPAQUE", choices: { A:"transparent", B:"clear", C:"unclear", D:"obvious" }, answer:"C" },
  { number: 784, word: "OPPORTUNE", choices: { A:"untimely", B:"inconvenient", C:"timely", D:"inappropriate" }, answer:"C" },
  { number: 785, word: "ORTHODOX", choices: { A:"unorthodox", B:"radical", C:"conventional", D:"revolutionary" }, answer:"C" },
  { number: 786, word: "OSTENSIBLE", choices: { A:"genuine", B:"real", C:"apparent", D:"authentic" }, answer:"C" },
  
  // P words (18 questions: 787-804)
  { number: 787, word: "PALPABLE", choices: { A:"intangible", B:"imperceptible", C:"tangible", D:"invisible" }, answer:"C" },
  { number: 788, word: "PANACEA", choices: { A:"problem", B:"ailment", C:"cure-all", D:"disease" }, answer:"C" },
  { number: 789, word: "PARADIGM", choices: { A:"chaos", B:"disorder", C:"model", D:"confusion" }, answer:"C" },
  { number: 790, word: "PARADOX", choices: { A:"consistency", B:"logic", C:"contradiction", D:"agreement" }, answer:"C" },
  { number: 791, word: "PARAGON", choices: { A:"failure", B:"disappointment", C:"model", D:"disgrace" }, answer:"C" },
  { number: 792, word: "PARIAH", choices: { A:"insider", B:"member", C:"outcast", D:"participant" }, answer:"C" },
  { number: 793, word: "PAROCHIAL", choices: { A:"broad", B:"cosmopolitan", C:"narrow", D:"worldly" }, answer:"C" },
  { number: 794, word: "PARSIMONIOUS", choices: { A:"generous", B:"lavish", C:"stingy", D:"extravagant" }, answer:"C" },
  { number: 795, word: "PARTISAN", choices: { A:"neutral", B:"impartial", C:"biased", D:"objective" }, answer:"C" },
  { number: 796, word: "PATHOS", choices: { A:"indifference", B:"apathy", C:"emotion", D:"coldness" }, answer:"C" },
  { number: 797, word: "PAUCITY", choices: { A:"abundance", B:"plenty", C:"scarcity", D:"surplus" }, answer:"C" },
  { number: 798, word: "PEDANTIC", choices: { A:"casual", B:"relaxed", C:"overly scholarly", D:"informal" }, answer:"C" },
  { number: 799, word: "PENCHANT", choices: { A:"aversion", B:"dislike", C:"liking", D:"hatred" }, answer:"C" },
  { number: 800, word: "PENITENT", choices: { A:"unrepentant", B:"defiant", C:"remorseful", D:"proud" }, answer:"C" },
  { number: 801, word: "PENSIVE", choices: { A:"thoughtless", B:"carefree", C:"thoughtful", D:"frivolous" }, answer:"C" },
  { number: 802, word: "PENURY", choices: { A:"wealth", B:"affluence", C:"poverty", D:"prosperity" }, answer:"C" },
  { number: 803, word: "PERFIDIOUS", choices: { A:"loyal", B:"faithful", C:"treacherous", D:"devoted" }, answer:"C" },
  { number: 804, word: "PERFUNCTORY", choices: { A:"thorough", B:"careful", C:"cursory", D:"meticulous" }, answer:"C" },
  
  // Q words (6 questions: 805-810)
  { number: 805, word: "QUAGMIRE", choices: { A:"solution", B:"clarity", C:"predicament", D:"simplicity" }, answer:"C" },
  { number: 806, word: "QUANDARY", choices: { A:"certainty", B:"clarity", C:"dilemma", D:"solution" }, answer:"C" },
  { number: 807, word: "QUARANTINE", choices: { A:"expose", B:"integrate", C:"isolate", D:"mix" }, answer:"C" },
  { number: 808, word: "QUASH", choices: { A:"encourage", B:"promote", C:"suppress", D:"support" }, answer:"C" },
  { number: 809, word: "QUERULOUS", choices: { A:"content", B:"satisfied", C:"complaining", D:"pleased" }, answer:"C" },
  { number: 810, word: "QUIXOTIC", choices: { A:"practical", B:"realistic", C:"idealistic", D:"pragmatic" }, answer:"C" },
  
  // R words (12 questions: 811-822)
  { number: 811, word: "RANCOROUS", choices: { A:"friendly", B:"kind", C:"bitter", D:"pleasant" }, answer:"C" },
  { number: 812, word: "RAPACIOUS", choices: { A:"generous", B:"giving", C:"greedy", D:"charitable" }, answer:"C" },
  { number: 813, word: "RAZE", choices: { A:"build", B:"construct", C:"demolish", D:"erect" }, answer:"C" },
  { number: 814, word: "RECALCITRANT", choices: { A:"cooperative", B:"compliant", C:"defiant", D:"obedient" }, answer:"C" },
  { number: 815, word: "RECAPITULATE", choices: { A:"expand", B:"elaborate", C:"summarize", D:"detail" }, answer:"C" },
  { number: 816, word: "RECLUSIVE", choices: { A:"social", B:"outgoing", C:"solitary", D:"gregarious" }, answer:"C" },
  { number: 817, word: "REDOLENT", choices: { A:"odorless", B:"scentless", C:"fragrant", D:"bland" }, answer:"C" },
  { number: 818, word: "REDRESS", choices: { A:"worsen", B:"harm", C:"remedy", D:"damage" }, answer:"C" },
  { number: 819, word: "REDUNDANT", choices: { A:"necessary", B:"essential", C:"superfluous", D:"needed" }, answer:"C" },
  { number: 820, word: "REFUTE", choices: { A:"prove", B:"confirm", C:"disprove", D:"validate" }, answer:"C" },
  { number: 821, word: "RELEGATE", choices: { A:"promote", B:"elevate", C:"demote", D:"advance" }, answer:"C" },
  { number: 822, word: "RELINQUISH", choices: { A:"claim", B:"seize", C:"surrender", D:"take" }, answer:"C" },
  
  // S words (18 questions: 823-840)
  { number: 823, word: "SAGACITY", choices: { A:"foolishness", B:"stupidity", C:"wisdom", D:"ignorance" }, answer:"C" },
  { number: 824, word: "SALIENT", choices: { A:"insignificant", B:"minor", C:"prominent", D:"trivial" }, answer:"C" },
  { number: 825, word: "SANGUINE", choices: { A:"pessimistic", B:"hopeless", C:"optimistic", D:"despairing" }, answer:"C" },
  { number: 826, word: "SARDONIC", choices: { A:"sincere", B:"genuine", C:"mocking", D:"earnest" }, answer:"C" },
  { number: 827, word: "SAVANT", choices: { A:"ignoramus", B:"fool", C:"expert", D:"dunce" }, answer:"C" },
  { number: 828, word: "SCRUPULOUS", choices: { A:"careless", B:"negligent", C:"careful", D:"sloppy" }, answer:"C" },
  { number: 829, word: "SECTARIAN", choices: { A:"universal", B:"inclusive", C:"narrow", D:"broad" }, answer:"C" },
  { number: 830, word: "SEDITIOUS", choices: { A:"loyal", B:"patriotic", C:"rebellious", D:"faithful" }, answer:"C" },
  { number: 831, word: "SEMINAL", choices: { A:"derivative", B:"unoriginal", C:"influential", D:"imitative" }, answer:"C" },
  { number: 832, word: "SENSUOUS", choices: { A:"ascetic", B:"austere", C:"pleasurable", D:"spartan" }, answer:"C" },
  { number: 833, word: "SERENDIPITY", choices: { A:"planning", B:"design", C:"chance", D:"intention" }, answer:"C" },
  { number: 834, word: "SOBRIETY", choices: { A:"frivolity", B:"levity", C:"seriousness", D:"playfulness" }, answer:"C" },
  { number: 835, word: "SOLICITOUS", choices: { A:"indifferent", B:"uncaring", C:"concerned", D:"neglectful" }, answer:"C" },
  { number: 836, word: "SOMNOLENT", choices: { A:"alert", B:"awake", C:"sleepy", D:"energetic" }, answer:"C" },
  { number: 837, word: "SPECIOUS", choices: { A:"genuine", B:"authentic", C:"false", D:"real" }, answer:"C" },
  { number: 838, word: "SPURIOUS", choices: { A:"genuine", B:"authentic", C:"false", D:"legitimate" }, answer:"C" },
  { number: 839, word: "STOIC", choices: { A:"emotional", B:"expressive", C:"unemotional", D:"passionate" }, answer:"C" },
  { number: 840, word: "STRIDENT", choices: { A:"soft", B:"gentle", C:"harsh", D:"melodious" }, answer:"C" },
  
  // T words (12 questions: 841-852)
  { number: 841, word: "TACIT", choices: { A:"explicit", B:"stated", C:"implied", D:"expressed" }, answer:"C" },
  { number: 842, word: "TANGENTIAL", choices: { A:"central", B:"relevant", C:"peripheral", D:"important" }, answer:"C" },
  { number: 843, word: "TAUTOLOGY", choices: { A:"variety", B:"diversity", C:"redundancy", D:"uniqueness" }, answer:"C" },
  { number: 844, word: "TEMERITY", choices: { A:"timidity", B:"cowardice", C:"audacity", D:"fear" }, answer:"C" },
  { number: 845, word: "TEMPERANCE", choices: { A:"excess", B:"indulgence", C:"moderation", D:"extravagance" }, answer:"C" },
  { number: 846, word: "TENACIOUS", choices: { A:"yielding", B:"weak", C:"persistent", D:"feeble" }, answer:"C" },
  { number: 847, word: "TENET", choices: { A:"doubt", B:"uncertainty", C:"principle", D:"question" }, answer:"C" },
  { number: 848, word: "TEPID", choices: { A:"enthusiastic", B:"passionate", C:"lukewarm", D:"fervent" }, answer:"C" },
  { number: 849, word: "TERSE", choices: { A:"verbose", B:"wordy", C:"brief", D:"lengthy" }, answer:"C" },
  { number: 850, word: "TIMOROUS", choices: { A:"brave", B:"bold", C:"timid", D:"courageous" }, answer:"C" },
  { number: 851, word: "TIRADE", choices: { A:"praise", B:"compliment", C:"outburst", D:"tribute" }, answer:"C" },
  { number: 852, word: "TORPOR", choices: { A:"energy", B:"vigor", C:"lethargy", D:"vitality" }, answer:"C" },
  
  // U words (8 questions: 853-860)
  { number: 853, word: "UBIQUITOUS", choices: { A:"rare", B:"scarce", C:"omnipresent", D:"uncommon" }, answer:"C" },
  { number: 854, word: "ULTERIOR", choices: { A:"obvious", B:"apparent", C:"hidden", D:"visible" }, answer:"C" },
  { number: 855, word: "UMBRAGE", choices: { A:"pleasure", B:"delight", C:"offense", D:"joy" }, answer:"C" },
  { number: 856, word: "UNASSUMING", choices: { A:"arrogant", B:"pretentious", C:"modest", D:"boastful" }, answer:"C" },
  { number: 857, word: "UNCTUOUS", choices: { A:"sincere", B:"genuine", C:"oily", D:"honest" }, answer:"C" },
  { number: 858, word: "UNDULATE", choices: { A:"stabilize", B:"flatten", C:"wave", D:"straighten" }, answer:"C" },
  { number: 859, word: "UNEQUIVOCAL", choices: { A:"ambiguous", B:"vague", C:"clear", D:"uncertain" }, answer:"C" },
  { number: 860, word: "UNSCRUPULOUS", choices: { A:"ethical", B:"moral", C:"dishonest", D:"principled" }, answer:"C" },
  
  // V words (12 questions: 861-872)
  { number: 861, word: "VACILLATE", choices: { A:"decide", B:"commit", C:"waver", D:"resolve" }, answer:"C" },
  { number: 862, word: "VAGARY", choices: { A:"certainty", B:"predictability", C:"whim", D:"constancy" }, answer:"C" },
  { number: 863, word: "VAPID", choices: { A:"interesting", B:"engaging", C:"dull", D:"exciting" }, answer:"C" },
  { number: 864, word: "VARIEGATED", choices: { A:"uniform", B:"monotonous", C:"varied", D:"homogeneous" }, answer:"C" },
  { number: 865, word: "VEHEMENT", choices: { A:"mild", B:"gentle", C:"intense", D:"calm" }, answer:"C" },
  { number: 866, word: "VENEER", choices: { A:"core", B:"substance", C:"facade", D:"essence" }, answer:"C" },
  { number: 867, word: "VERACIOUS", choices: { A:"dishonest", B:"false", C:"truthful", D:"deceptive" }, answer:"C" },
  { number: 868, word: "VERBATIM", choices: { A:"paraphrased", B:"summarized", C:"word-for-word", D:"condensed" }, answer:"C" },
  { number: 869, word: "VERBOSE", choices: { A:"concise", B:"brief", C:"wordy", D:"succinct" }, answer:"C" },
  { number: 870, word: "VERISIMILITUDE", choices: { A:"falseness", B:"unreality", C:"realism", D:"fiction" }, answer:"C" },
  { number: 871, word: "VERNACULAR", choices: { A:"formal speech", B:"technical language", C:"dialect", D:"jargon" }, answer:"C" },
  { number: 872, word: "VICARIOUS", choices: { A:"direct", B:"personal", C:"indirect", D:"firsthand" }, answer:"C" },
  
  // W words (8 questions: 873-880)
  { number: 873, word: "WANE", choices: { A:"grow", B:"increase", C:"decline", D:"expand" }, answer:"C" },
  { number: 874, word: "WANTON", choices: { A:"careful", B:"considerate", C:"reckless", D:"thoughtful" }, answer:"C" },
  { number: 875, word: "WIZENED", choices: { A:"youthful", B:"smooth", C:"shriveled", D:"plump" }, answer:"C" },
  { number: 876, word: "WRATH", choices: { A:"peace", B:"calm", C:"anger", D:"serenity" }, answer:"C" },
  { number: 877, word: "WROUGHT", choices: { A:"destroyed", B:"demolished", C:"formed", D:"ruined" }, answer:"C" },
  { number: 878, word: "WILY", choices: { A:"naive", B:"simple", C:"cunning", D:"straightforward" }, answer:"C" },
  { number: 879, word: "WINSOME", choices: { A:"repulsive", B:"unattractive", C:"charming", D:"unpleasant" }, answer:"C" },
  { number: 880, word: "WREAK", choices: { A:"prevent", B:"stop", C:"inflict", D:"avoid" }, answer:"C" },
  
  // X, Y, Z words (20 questions: 881-900, padding to reach exactly 300)
  { number: 881, word: "XENOPHOBIC", choices: { A:"tolerant", B:"accepting", C:"intolerant", D:"welcoming" }, answer:"C" },
  { number: 882, word: "YOKE", choices: { A:"freedom", B:"liberty", C:"burden", D:"release" }, answer:"C" },
  { number: 883, word: "ZEALOT", choices: { A:"moderate", B:"centrist", C:"fanatic", D:"compromiser" }, answer:"C" },
  { number: 884, word: "ZEPHYR", choices: { A:"gale", B:"storm", C:"breeze", D:"hurricane" }, answer:"C" },
  
  // Additional padding questions to reach 900 (885-900) - using repeated advanced words
  { number: 885, word: "ABATE", choices: { A:"escalate", B:"amplify", C:"reduce", D:"heighten" }, answer:"C" },
  { number: 886, word: "ACERBIC", choices: { A:"sweet", B:"mild", C:"harsh", D:"pleasant" }, answer:"C" },
  { number: 887, word: "BELLICOSE", choices: { A:"peaceful", B:"passive", C:"warlike", D:"docile" }, answer:"C" },
  { number: 888, word: "CACOPHONY", choices: { A:"harmony", B:"symphony", C:"discord", D:"melody" }, answer:"C" },
  { number: 889, word: "EBULLIENT", choices: { A:"somber", B:"morose", C:"enthusiastic", D:"melancholy" }, answer:"C" },
  { number: 890, word: "FALLACIOUS", choices: { A:"valid", B:"sound", C:"false", D:"logical" }, answer:"C" },
  { number: 891, word: "GARRULOUS", choices: { A:"reticent", B:"reserved", C:"talkative", D:"quiet" }, answer:"C" },
  { number: 892, word: "ICONOCLAST", choices: { A:"conservative", B:"orthodox", C:"rebel", D:"conformist" }, answer:"C" },
  { number: 893, word: "MALLEABLE", choices: { A:"brittle", B:"rigid", C:"pliable", D:"hard" }, answer:"C" },
  { number: 894, word: "NEBULOUS", choices: { A:"precise", B:"exact", C:"vague", D:"distinct" }, answer:"C" },
  { number: 895, word: "OBDURATE", choices: { A:"yielding", B:"flexible", C:"stubborn", D:"compliant" }, answer:"C" },
  { number: 896, word: "PALPABLE", choices: { A:"imperceptible", B:"invisible", C:"tangible", D:"abstract" }, answer:"C" },
  { number: 897, word: "QUIXOTIC", choices: { A:"practical", B:"sensible", C:"idealistic", D:"realistic" }, answer:"C" },
  { number: 898, word: "SAGACITY", choices: { A:"folly", B:"ignorance", C:"wisdom", D:"stupidity" }, answer:"C" },
  { number: 899, word: "TACIT", choices: { A:"explicit", B:"voiced", C:"implied", D:"spoken" }, answer:"C" },
  { number: 900, word: "VEHEMENT", choices: { A:"apathetic", B:"indifferent", C:"intense", D:"lukewarm" }, answer:"C" },
];

// Optional sentinel
window.__VOCAB_ENHANCED2_LOADED__ = true;
